//! End-to-end tests for the `api` tool domain: bounded resolution fallback and
//! compile-only probes across real Cargo fixtures.
//!
//! Every probe creates and discards a server-owned change candidate. The
//! original workspace, its `Cargo.lock`, and its dependency versions must stay
//! byte-identical.

use std::{
    fs,
    path::{Path, PathBuf},
    process::Command,
    sync::Arc,
    time::{Duration, SystemTime, UNIX_EPOCH},
};

use agz_rust_coder::{
    Config,
    change::ChangeService,
    process::ProcessSupervisor,
    tools::{
        ApiAction, ApiAnchor, ApiConfiguration, ApiData, ApiEnvironment, ApiRequest, execute_api,
    },
    workspace::{ClientRoots, MetadataService, RootGuard, WorkspaceRoot, WorkspaceSnapshot},
};
use sha2::{Digest, Sha256};
use tokio_util::sync::CancellationToken;

struct Fixture {
    root: PathBuf,
    guard: Arc<RootGuard>,
    config: Config,
    service: Arc<ChangeService>,
}

impl Fixture {
    fn new(label: &str) -> Self {
        let stamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map_or(0, |duration| duration.as_nanos());
        let base = fs::canonicalize(std::env::temp_dir())
            .expect("canonical temp directory")
            .join(format!(
                "agz-rust-coder-api-{label}-{}-{stamp}",
                std::process::id()
            ));
        let root = base.join("workspace");
        let state = base.join("state");
        fs::create_dir_all(root.join("src")).expect("create source directory");
        fs::create_dir_all(root.join("dep/src")).expect("create dependency source directory");
        fs::create_dir_all(&state).expect("create state directory");
        fs::write(
            root.join("Cargo.toml"),
            "[package]\nname = \"probe-fixture\"\nversion = \"0.1.0\"\nedition = \"2024\"\n\n[workspace]\n\n[dependencies]\ndep = { path = \"dep\" }\n",
        )
        .expect("write manifest");
        fs::write(
            root.join("Cargo.lock"),
            "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"dep\"\nversion = \"0.1.0\"\n\n[[package]]\nname = \"probe-fixture\"\nversion = \"0.1.0\"\ndependencies = [\n \"dep\",\n]\n",
        )
        .expect("write lockfile");
        fs::write(
            root.join("src/lib.rs"),
            "pub fn value() -> u8 { 1 }\n\npub fn takes_iter<I: Iterator<Item = u8>>(iter: I) -> usize { iter.count() }\n",
        )
        .expect("write source");
        fs::write(
            root.join("dep/Cargo.toml"),
            "[package]\nname = \"dep\"\nversion = \"0.1.0\"\nedition = \"2024\"\n\n[features]\nextra = []\n",
        )
        .expect("write dependency manifest");
        fs::write(
            root.join("dep/src/lib.rs"),
            "pub fn old_api(value: u8) -> u8 { value }\n\n#[cfg(feature = \"extra\")]\npub fn extra(value: u8) -> u8 { value }\n",
        )
        .expect("write dependency source");
        git_command(&root, &["init", "--quiet"]);
        git_command(&root, &["config", "user.email", "api@example.invalid"]);
        git_command(&root, &["config", "user.name", "Api Fixture"]);
        git_command(&root, &["add", "."]);
        git_command(&root, &["commit", "--quiet", "-m", "fixture"]);

        let mut config = Config::defaults_at(&root);
        config.gate.debounce_ms = 10;
        config.gate.hard_timeout_ms = 120_000;
        config.gate.cache_dir = state.join("gate-cache");
        config.gate.lease_dir = state.join("leases");
        config.change.scratch_dir = state.join("change");
        config.telemetry.enabled = false;
        config.telemetry.path = state.join("activity.jsonl");
        config.api.compile_timeout_ms = 120_000;
        let dependencies = config.server.allow_dependency_roots.clone();
        let guard =
            Arc::new(RootGuard::new([root.clone()], dependencies).expect("create root guard"));
        let service = Arc::new(
            ChangeService::new(
                config.clone(),
                Arc::clone(&guard),
                ProcessSupervisor::without_journal(),
            )
            .expect("create change service"),
        );
        Self {
            root,
            guard,
            config,
            service,
        }
    }

    fn workspace(&self) -> WorkspaceRoot {
        self.guard
            .snapshot(ClientRoots::unsupported())
            .expect("root snapshot")
            .select(Some(&self.root))
            .expect("select workspace")
    }

    fn snapshot(&self) -> Arc<WorkspaceSnapshot> {
        let selection =
            agz_rust_coder::workspace::select_in_root(&self.workspace()).expect("selection");
        MetadataService::new(Arc::clone(&self.guard))
            .acquire(&selection, "cargo")
            .expect("metadata snapshot")
            .snapshot
    }

    async fn probe(
        &self,
        snippets: Vec<String>,
        expected: Option<String>,
        features: Vec<String>,
        anchor: &str,
        cancellation: CancellationToken,
    ) -> ApiData {
        let workspace = self.workspace();
        let snapshot = self.snapshot();
        let env = ApiEnvironment {
            manager: None,
            root: &workspace,
            snapshot: Some(&snapshot),
            snapshot_error: None,
            change: Some(&self.service),
            limits: &self.config.api,
            timeout: Duration::from_secs(5),
            tool_output_bytes: 49_152,
            cancellation,
        };
        execute_api(
            ApiRequest {
                action: ApiAction::Probe,
                anchor: ApiAnchor {
                    path: anchor.to_owned(),
                    symbol: None,
                    line: None,
                    character: None,
                },
                expected_signature: expected,
                snippets,
                change_id: Some("host-change".to_owned()),
                configuration: ApiConfiguration {
                    features,
                    all_features: false,
                    no_default_features: false,
                },
            },
            env,
        )
        .await
    }

    async fn resolve(&self, symbol: &str) -> ApiData {
        let workspace = self.workspace();
        let snapshot = self.snapshot();
        let env = ApiEnvironment {
            manager: None,
            root: &workspace,
            snapshot: Some(&snapshot),
            snapshot_error: None,
            change: Some(&self.service),
            limits: &self.config.api,
            timeout: Duration::from_secs(5),
            tool_output_bytes: 49_152,
            cancellation: CancellationToken::new(),
        };
        execute_api(
            ApiRequest {
                action: ApiAction::Resolve,
                anchor: ApiAnchor {
                    path: "src/lib.rs".to_owned(),
                    symbol: Some(symbol.to_owned()),
                    line: Some(1),
                    character: None,
                },
                expected_signature: None,
                snippets: Vec::new(),
                change_id: Some("host-change".to_owned()),
                configuration: ApiConfiguration::default(),
            },
            env,
        )
        .await
    }

    fn write(&self, relative: &str, contents: impl AsRef<[u8]>) -> PathBuf {
        let path = self.root.join(relative);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).expect("create parent directory");
        }
        fs::write(&path, contents).expect("write fixture file");
        path
    }
}

impl Drop for Fixture {
    fn drop(&mut self) {
        if let Some(base) = self.root.parent() {
            let _ = fs::remove_dir_all(base);
        }
    }
}

fn git_command(root: &Path, arguments: &[&str]) {
    let status = Command::new("git")
        .args(arguments)
        .current_dir(root)
        .status()
        .expect("run git fixture command");
    assert!(status.success(), "git command failed: {arguments:?}");
}

fn digest(path: &Path) -> String {
    let bytes = fs::read(path).expect("read digest target");
    let mut hasher = Sha256::new();
    hasher.update(&bytes);
    format!("{:x}", hasher.finalize())
}

fn messages(data: &ApiData) -> String {
    data.probe
        .as_ref()
        .map(|probe| {
            probe
                .diagnostics
                .iter()
                .map(|diagnostic| diagnostic.message.clone())
                .collect::<Vec<_>>()
                .join("\n")
        })
        .unwrap_or_default()
}

fn probe_status(data: &ApiData) -> &str {
    data.probe
        .as_ref()
        .map(|probe| probe.result.as_str())
        .unwrap_or(data.status.as_str())
}

#[tokio::test]
async fn resolve_without_analyzer_returns_bounded_source_fallback() {
    let fixture = Fixture::new("resolve");
    let data = fixture.resolve("value").await;
    assert_eq!(data.status, "OK", "{data:#?}");
    let resolve = data.resolve.expect("resolve payload");
    assert_eq!(resolve.analyzer, "unavailable");
    assert!(
        resolve
            .anchor_excerpt
            .as_deref()
            .is_some_and(|excerpt| excerpt.contains("value")),
        "offline resolution must return the bounded anchor excerpt"
    );
    assert_eq!(resolve.features.package.as_deref(), Some("probe-fixture"));
    assert!(
        resolve.notes.iter().any(|note| note.contains("advisory")),
        "resolve must label analyzer evidence as advisory"
    );
}

#[tokio::test]
async fn wrong_version_api_is_caught_without_touching_the_workspace() {
    let fixture = Fixture::new("wrong-version");
    let lock = digest(&fixture.root.join("Cargo.lock"));
    let anchor = digest(&fixture.root.join("src/lib.rs"));

    let data = fixture
        .probe(
            vec!["let _ = dep::new_api(1);".to_owned()],
            None,
            Vec::new(),
            "src/lib.rs",
            CancellationToken::new(),
        )
        .await;

    assert_eq!(probe_status(&data), "COMPILE_FAILED", "{data:#?}");
    assert!(
        messages(&data).contains("new_api"),
        "the compiler must attribute the unresolved API: {data:#?}"
    );
    let probe = data.probe.expect("probe payload");
    assert!(!probe.implementation_complete);
    assert_eq!(probe.compile.status, "FAIL");
    assert_eq!(probe.change_id.as_deref(), Some("host-change"));
    assert!(probe.ephemeral);
    assert!(probe.original_unchanged, "the original workspace changed");
    assert!(
        probe
            .proposals
            .iter()
            .any(|proposal| proposal.kind == "dependency_version"
                && proposal.name == "dep"
                && proposal.current_version.as_deref() == Some("0.1.0")
                && proposal.requires_explicit_host_change)
    );
    assert_eq!(digest(&fixture.root.join("Cargo.lock")), lock);
    assert_eq!(digest(&fixture.root.join("src/lib.rs")), anchor);
}

#[tokio::test]
async fn missing_import_is_caught() {
    let fixture = Fixture::new("missing-import");
    let data = fixture
        .probe(
            vec!["let _: HashMap<u8, u8> = HashMap::new();".to_owned()],
            None,
            Vec::new(),
            "src/lib.rs",
            CancellationToken::new(),
        )
        .await;
    assert_eq!(probe_status(&data), "COMPILE_FAILED", "{data:#?}");
    let text = messages(&data);
    assert!(
        text.contains("HashMap") || text.contains("E0412") || text.contains("E0433"),
        "missing import must be attributed: {text}"
    );
}

#[tokio::test]
async fn inactive_feature_fails_and_then_compiles_when_selected() {
    let fixture = Fixture::new("feature");
    let snippet = "let _ = dep::extra(1);".to_owned();

    let failed = fixture
        .probe(
            vec![snippet.clone()],
            None,
            Vec::new(),
            "src/lib.rs",
            CancellationToken::new(),
        )
        .await;
    assert_eq!(probe_status(&failed), "COMPILE_FAILED", "{failed:#?}");
    let probe = failed.probe.expect("probe payload");
    assert!(
        probe
            .proposals
            .iter()
            .any(|proposal| proposal.kind == "feature"
                && proposal.name == "dep/extra"
                && proposal.requires_explicit_host_change),
        "an inactive feature must surface as a proposal: {probe:#?}"
    );

    let selected = fixture
        .probe(
            vec![snippet],
            None,
            vec!["dep/extra".to_owned()],
            "src/lib.rs",
            CancellationToken::new(),
        )
        .await;
    assert_eq!(
        probe_status(&selected),
        "COMPILES_IN_CONFIGURATION",
        "{selected:#?}"
    );
    let probe = selected.probe.expect("probe payload");
    assert_eq!(probe.configuration.features, vec!["dep/extra".to_owned()]);
    assert!(
        probe.compile.command.contains("--features dep/extra"),
        "{}",
        probe.compile.command
    );
}

#[tokio::test]
async fn generic_bound_failure_is_caught() {
    let fixture = Fixture::new("generic-bound");
    let data = fixture
        .probe(
            vec!["let _ = crate::takes_iter(vec![\"nope\".to_string()].into_iter());".to_owned()],
            None,
            Vec::new(),
            "src/lib.rs",
            CancellationToken::new(),
        )
        .await;
    assert_eq!(probe_status(&data), "COMPILE_FAILED", "{data:#?}");
    let text = messages(&data);
    assert!(
        text.to_lowercase().contains("iterator") || text.contains("E0277"),
        "generic bound failure must be attributed: {text}"
    );
}

#[tokio::test]
async fn expected_signature_is_asserted_and_harness_is_reported() {
    let fixture = Fixture::new("expected");
    let lock = digest(&fixture.root.join("Cargo.lock"));

    let passed = fixture
        .probe(
            vec!["crate::value()".to_owned()],
            Some("u8".to_owned()),
            Vec::new(),
            "src/lib.rs",
            CancellationToken::new(),
        )
        .await;
    assert_eq!(
        probe_status(&passed),
        "COMPILES_IN_CONFIGURATION",
        "{passed:#?}"
    );
    let probe = passed.probe.expect("probe payload");
    assert_eq!(probe.assertion, "expected-type-return");
    assert!(probe.implementation_complete);
    assert_eq!(probe.harness.len(), 2);
    assert!(probe.harness.iter().any(|file| file.kind == "patched"));
    assert!(probe.harness.iter().any(|file| file.kind == "created"));
    assert_eq!(probe.input_hash.len(), 64);
    assert!(
        probe
            .input_hash
            .chars()
            .all(|character| character.is_ascii_hexdigit())
    );
    assert_eq!(probe.budget.max_snippets, fixture.config.api.max_snippets);
    assert_eq!(
        probe.budget.compile_timeout_ms,
        fixture.config.api.compile_timeout_ms
    );
    assert!(probe.original_unchanged);
    assert_eq!(digest(&fixture.root.join("Cargo.lock")), lock);

    let failed = fixture
        .probe(
            vec!["crate::value()".to_owned()],
            Some("String".to_owned()),
            Vec::new(),
            "src/lib.rs",
            CancellationToken::new(),
        )
        .await;
    assert_eq!(probe_status(&failed), "COMPILE_FAILED", "{failed:#?}");
    let probe = failed.probe.expect("probe payload");
    assert!(
        probe
            .diagnostics
            .iter()
            .any(|diagnostic| diagnostic.code.as_deref() == Some("E0308")),
        "the expected type must be unified by the compiler: {probe:#?}"
    );
}

#[tokio::test]
async fn diverging_snippet_is_not_reported_as_complete() {
    let fixture = Fixture::new("diverging");
    let data = fixture
        .probe(
            vec!["todo!()".to_owned()],
            Some("u8".to_owned()),
            Vec::new(),
            "src/lib.rs",
            CancellationToken::new(),
        )
        .await;
    assert_eq!(
        probe_status(&data),
        "INCOMPLETE_IMPLEMENTATION",
        "{data:#?}"
    );
    let probe = data.probe.expect("probe payload");
    assert!(!probe.implementation_complete);
    assert!(
        probe.snippets[0]
            .diverging
            .iter()
            .any(|item| item == "todo!"),
        "{probe:#?}"
    );
}

#[tokio::test]
async fn undeclared_module_is_unsupported_context() {
    let fixture = Fixture::new("undeclared");
    fixture.write("src/orphan.rs", "pub fn orphan() {}\n");
    let data = fixture
        .probe(
            vec!["let _ = 1;".to_owned()],
            None,
            Vec::new(),
            "src/orphan.rs",
            CancellationToken::new(),
        )
        .await;
    assert_eq!(data.status, "UNSUPPORTED_CONTEXT", "{data:#?}");
    assert!(data.probe.is_none());
}

#[tokio::test]
async fn budgets_and_cancellation_are_enforced() {
    let mut fixture = Fixture::new("budgets");
    fixture.config.api.max_snippets = 1;
    let data = fixture
        .probe(
            vec!["let _ = 1;".to_owned(), "let _ = 2;".to_owned()],
            None,
            Vec::new(),
            "src/lib.rs",
            CancellationToken::new(),
        )
        .await;
    assert_eq!(data.status, "INVALID", "{data:#?}");
    assert!(data.reason.contains("at most 1"));

    let cancelled = CancellationToken::new();
    cancelled.cancel();
    let data = fixture
        .probe(
            vec!["let _ = 1;".to_owned()],
            None,
            Vec::new(),
            "src/lib.rs",
            cancelled,
        )
        .await;
    assert_eq!(data.status, "CANCELLED", "{data:#?}");
}
