//! End-to-end tests for the revision-bound `change` engine.
//!
//! Each fixture builds a temporary Cargo project, mutates it (dirty tracked
//! files and untracked files), then drives create/stage/validate/export/discard
//! while asserting that the original workspace bytes never change.

use std::{
    fs,
    path::{Path, PathBuf},
    process::Command,
    sync::Arc,
    time::{SystemTime, UNIX_EPOCH},
};

use agz_rust_coder::{
    Config,
    change::{ChangeAction, ChangeOutcome, ChangeRequest, ChangeService, NewFileInput, PatchInput},
    gate::{GateDetail, GateTargetId, ValidationOptions},
    process::ProcessSupervisor,
    server::{ChangeInput, CheckDetail, CheckTarget},
    workspace::{ClientRoots, RootGuard, WorkspaceRoot},
};
use sha2::{Digest, Sha256};
use tokio_util::sync::CancellationToken;

struct Fixture {
    root: PathBuf,
    state: PathBuf,
    guard: Arc<RootGuard>,
    config: Config,
    service: Arc<ChangeService>,
}

impl Fixture {
    fn new(label: &str, source: &[u8], git: bool, mutate: impl FnOnce(&Path, &mut Config)) -> Self {
        Self::with_setup(label, source, git, |_| {}, mutate)
    }

    fn with_setup(
        label: &str,
        source: &[u8],
        git: bool,
        setup: impl FnOnce(&Path),
        mutate: impl FnOnce(&Path, &mut Config),
    ) -> Self {
        let stamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map_or(0, |duration| duration.as_nanos());
        let base = fs::canonicalize(std::env::temp_dir())
            .expect("canonical temp directory")
            .join(format!(
                "agz-rust-coder-change-{label}-{}-{stamp}",
                std::process::id()
            ));
        let root = base.join("workspace");
        let state = base.join("state");
        fs::create_dir_all(root.join("src")).expect("create project source directory");
        fs::create_dir_all(&state).expect("create state directory");
        fs::write(
            root.join("Cargo.toml"),
            "[package]\nname = \"change-fixture\"\nversion = \"0.1.0\"\nedition = \"2024\"\n\n[workspace]\n",
        )
        .expect("write manifest");
        fs::write(
            root.join("Cargo.lock"),
            "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"change-fixture\"\nversion = \"0.1.0\"\n",
        )
        .expect("write lockfile");
        fs::write(root.join("src/lib.rs"), source).expect("write source");
        setup(&base);
        if git {
            git_command(&root, &["init", "--quiet"]);
            git_command(&root, &["config", "user.email", "change@example.invalid"]);
            git_command(&root, &["config", "user.name", "Change Fixture"]);
            git_command(&root, &["add", "."]);
            git_command(&root, &["commit", "--quiet", "-m", "fixture"]);
        }
        let mut config = Config::defaults_at(&root);
        config.gate.debounce_ms = 10;
        config.gate.hard_timeout_ms = 120_000;
        config.gate.cache_dir = state.join("gate-cache");
        config.gate.lease_dir = state.join("leases");
        config.change.scratch_dir = state.join("change");
        config.telemetry.enabled = false;
        config.telemetry.path = state.join("activity.jsonl");
        mutate(&root, &mut config);
        let dependencies = config.server.allow_dependency_roots.clone();
        let guard =
            Arc::new(RootGuard::new([root.clone()], dependencies).expect("create root guard"));
        let service = Arc::new(
            ChangeService::new(
                config.clone(),
                Arc::clone(&guard),
                ProcessSupervisor::without_journal(),
            )
            .expect("create change service"),
        );
        Self {
            root,
            state,
            guard,
            config,
            service,
        }
    }

    /// Rebuilds the service over the same scratch, exercising startup recovery.
    fn rebuild_service(&self) -> Arc<ChangeService> {
        Arc::new(
            ChangeService::new(
                self.config.clone(),
                Arc::clone(&self.guard),
                ProcessSupervisor::without_journal(),
            )
            .expect("rebuild change service"),
        )
    }

    fn write(&self, relative: &str, contents: impl AsRef<[u8]>) -> PathBuf {
        let path = self.root.join(relative);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).expect("create parent directory");
        }
        fs::write(&path, contents).expect("write fixture file");
        path
    }

    fn workspace(&self) -> WorkspaceRoot {
        self.guard
            .snapshot(ClientRoots::unsupported())
            .expect("root snapshot")
            .select(Some(&self.root))
            .expect("select workspace")
    }

    async fn execute(&self, request: ChangeRequest) -> ChangeOutcome {
        self.execute_cancellable(request, CancellationToken::new())
            .await
    }

    async fn execute_cancellable(
        &self,
        request: ChangeRequest,
        cancellation: CancellationToken,
    ) -> ChangeOutcome {
        self.service
            .execute(request, &self.workspace(), cancellation, None)
            .await
    }

    fn candidate(&self, id: &str) -> PathBuf {
        self.state.join("change").join(id).join("candidate")
    }

    fn change_dir(&self, id: &str) -> PathBuf {
        self.state.join("change").join(id)
    }
}

impl Drop for Fixture {
    fn drop(&mut self) {
        if let Some(base) = self.root.parent() {
            let _ = fs::remove_dir_all(base);
        }
    }
}

fn git_command(root: &Path, arguments: &[&str]) {
    let status = Command::new("git")
        .args(arguments)
        .current_dir(root)
        .status()
        .expect("run git fixture command");
    assert!(status.success(), "git command failed: {arguments:?}");
}

fn create_request() -> ChangeRequest {
    ChangeRequest {
        action: ChangeAction::Create,
        change_id: None,
        expected_revision: None,
        base_identity: None,
        patches: Vec::new(),
        new_files: Vec::new(),
        target: GateTargetId::Check,
        options: ValidationOptions::default(),
        detail: GateDetail::Compact,
        timings: false,
    }
}

fn stage_request(
    id: &str,
    revision: u64,
    base: &str,
    patches: Vec<PatchInput>,
    new_files: Vec<NewFileInput>,
) -> ChangeRequest {
    ChangeRequest {
        action: ChangeAction::Stage,
        change_id: Some(id.to_owned()),
        expected_revision: Some(revision),
        base_identity: Some(base.to_owned()),
        patches,
        new_files,
        target: GateTargetId::Check,
        options: ValidationOptions::default(),
        detail: GateDetail::Compact,
        timings: false,
    }
}

fn validate_request(id: &str, revision: u64, base: &str) -> ChangeRequest {
    ChangeRequest {
        action: ChangeAction::Validate,
        change_id: Some(id.to_owned()),
        expected_revision: Some(revision),
        base_identity: Some(base.to_owned()),
        patches: Vec::new(),
        new_files: Vec::new(),
        target: GateTargetId::Check,
        options: ValidationOptions::default(),
        detail: GateDetail::Compact,
        timings: false,
    }
}

fn inspect_request(id: &str) -> ChangeRequest {
    ChangeRequest {
        action: ChangeAction::Inspect,
        change_id: Some(id.to_owned()),
        ..create_request()
    }
}

fn export_request(id: &str) -> ChangeRequest {
    ChangeRequest {
        action: ChangeAction::Export,
        change_id: Some(id.to_owned()),
        ..create_request()
    }
}

fn discard_request(id: &str) -> ChangeRequest {
    ChangeRequest {
        action: ChangeAction::Discard,
        change_id: Some(id.to_owned()),
        ..create_request()
    }
}

fn patch(file: &str, old: &str, new: &str) -> PatchInput {
    PatchInput {
        file: file.to_owned(),
        old_string: old.to_owned(),
        new_string: new.to_owned(),
    }
}

fn new_file(file: &str, content: &str) -> NewFileInput {
    NewFileInput {
        file: file.to_owned(),
        content: content.to_owned(),
    }
}

fn digest(path: &Path) -> String {
    let bytes = fs::read(path).expect("read digest target");
    let mut hasher = Sha256::new();
    hasher.update(&bytes);
    format!("{:x}", hasher.finalize())
}

fn assert_unchanged(fixture: &Fixture, expected: &[(&str, String)]) {
    for (relative, hash) in expected {
        assert_eq!(
            &digest(&fixture.root.join(relative)),
            hash,
            "original file changed: {relative}"
        );
    }
}

#[tokio::test]
async fn revision_bound_flow_is_isolated_and_verified() {
    let fixture = Fixture::new(
        "flow",
        b"pub fn value() -> u8 { 1 }\n",
        true,
        |_root, _config| {},
    );
    fixture.write("src/lib.rs", b"pub fn value() -> u8 { 11 }\n");
    fixture.write("notes.txt", b"untracked\r\n");
    fixture.write("src/extra.rs", b"pub fn extra() -> u8 { 3 }\n");
    let originals = [
        ("Cargo.toml", digest(&fixture.root.join("Cargo.toml"))),
        ("Cargo.lock", digest(&fixture.root.join("Cargo.lock"))),
        ("src/lib.rs", digest(&fixture.root.join("src/lib.rs"))),
        ("notes.txt", digest(&fixture.root.join("notes.txt"))),
        ("src/extra.rs", digest(&fixture.root.join("src/extra.rs"))),
    ];

    let created = fixture.execute(create_request()).await;
    assert_eq!(created.status, "CREATED", "{created:#?}");
    assert!(!created.is_error);
    let id = created.data.change_id.clone().expect("change id");
    let base = created.data.base_identity.clone().expect("base identity");
    assert_eq!(created.data.revision, 0);
    let capture = created.data.capture.clone().expect("capture summary");
    assert!(capture.complete);
    assert!(capture.files >= 5, "{capture:#?}");
    assert!(
        capture.excluded.iter().any(|path| path == ".git"),
        "the capture summary must expose the excluded Git directory: {capture:#?}"
    );

    // The capture is byte-exact, including CRLF and untracked files.
    let candidate = fixture.candidate(&id);
    assert_eq!(
        fs::read(candidate.join("src/lib.rs")).expect("candidate source"),
        b"pub fn value() -> u8 { 11 }\n"
    );
    assert_eq!(
        fs::read(candidate.join("notes.txt")).expect("candidate notes"),
        b"untracked\r\n"
    );
    assert!(candidate.join("src/extra.rs").is_file());
    assert!(!candidate.join(".git").exists());
    assert!(!candidate.join("target").exists());

    // First stage introduces a compile error in the candidate only.
    let staged = fixture
        .execute(stage_request(
            &id,
            0,
            &base,
            vec![patch(
                "src/lib.rs",
                "pub fn value() -> u8 { 11 }",
                "pub fn value() -> u8 { \"bad\" }",
            )],
            vec![new_file("src/created.rs", "pub fn created() -> u8 { 4 }\n")],
        ))
        .await;
    assert_eq!(staged.status, "STAGED", "{staged:#?}");
    assert_eq!(staged.data.revision, 1);
    assert!(
        String::from_utf8_lossy(&fs::read(candidate.join("src/lib.rs")).expect("candidate"))
            .contains("\"bad\"")
    );
    assert_eq!(
        fs::read(candidate.join("src/created.rs")).expect("new candidate file"),
        b"pub fn created() -> u8 { 4 }\n"
    );

    let failed = fixture.execute(validate_request(&id, 1, &base)).await;
    assert_eq!(failed.status, "FAIL", "{failed:#?}");
    assert!(
        !failed.is_error,
        "a recorded compile failure is not a tool error"
    );
    assert!(!failed.data.verified);
    let row = failed.data.evidence.last().expect("evidence row");
    assert_eq!(row.revision, 1);
    assert!(row.fresh && row.authoritative);
    assert_eq!(row.target, "check");
    assert!(
        row.command.contains(&id),
        "command must target the candidate"
    );
    assert!(row.exit_code.is_some_and(|code| code != 0));

    let exported = fixture.execute(export_request(&id)).await;
    assert_eq!(exported.status, "EXPORTED_UNVERIFIED");
    assert!(!exported.data.verified);
    assert!(
        exported
            .data
            .patches
            .iter()
            .any(|patch| patch.file == "src/lib.rs")
    );
    assert!(exported.data.new_files.iter().any(|file| {
        file.file == "src/created.rs" && file.sha256.len() == 64 && file.content.is_some()
    }));

    // Second stage repairs the candidate; earlier evidence becomes historical.
    let fixed = fixture
        .execute(stage_request(
            &id,
            1,
            &base,
            vec![patch(
                "src/lib.rs",
                "pub fn value() -> u8 { \"bad\" }",
                "pub fn value() -> u8 { 2 }",
            )],
            vec![],
        ))
        .await;
    assert_eq!(fixed.status, "STAGED", "{fixed:#?}");
    assert_eq!(fixed.data.revision, 2);
    assert!(
        fixed.data.evidence.iter().all(|evidence| !evidence.fresh),
        "superseded evidence must lose freshness"
    );

    let passed = fixture.execute(validate_request(&id, 2, &base)).await;
    assert_eq!(passed.status, "PASS", "{passed:#?}");
    assert!(passed.data.verified);
    assert!(
        passed
            .data
            .evidence
            .iter()
            .any(|evidence| { evidence.revision == 2 && evidence.fresh && evidence.authoritative })
    );
    assert!(
        passed
            .data
            .evidence
            .iter()
            .any(|evidence| { evidence.revision == 1 && !evidence.fresh })
    );

    let exported = fixture.execute(export_request(&id)).await;
    assert_eq!(exported.status, "EXPORTED");
    assert!(exported.data.verified);
    assert!(
        exported
            .data
            .evidence
            .iter()
            .any(|evidence| { evidence.revision == 2 && evidence.fresh && evidence.authoritative })
    );

    // Isolation: original source (dirty and untracked) and original target
    // remain exactly as captured, while the candidate build lived in scratch.
    assert_unchanged(&fixture, &originals);
    assert!(
        !fixture.root.join("target").exists(),
        "the original target directory must not be created"
    );
    assert!(fixture.change_dir(&id).join("cache").exists());

    let discarded = fixture.execute(discard_request(&id)).await;
    assert_eq!(discarded.status, "DISCARDED", "{discarded:#?}");
    assert!(!discarded.is_error);
    assert!(!candidate.exists(), "candidate copy must be removed");
    assert!(fixture.change_dir(&id).join("record.json").is_file());
    let again = fixture.execute(discard_request(&id)).await;
    assert_eq!(again.status, "DISCARDED");
    assert!(!again.is_error);
    assert_unchanged(&fixture, &originals);
}

#[tokio::test]
async fn fail_closed_inputs_never_touch_the_candidate() {
    let fixture = Fixture::new(
        "closed",
        b"pub fn value() -> u8 { 1 }\r\n",
        false,
        |_root, _config| {},
    );
    fixture.write("binary.dat", [0xff, 0xfe, 0xfd]);
    let created = fixture.execute(create_request()).await;
    assert_eq!(created.status, "CREATED", "{created:#?}");
    let id = created.data.change_id.clone().expect("change id");
    let base = created.data.base_identity.clone().expect("base identity");
    let candidate = fixture.candidate(&id);
    let original_candidate_hash = digest(&candidate.join("src/lib.rs"));

    for (patches, expected) in [
        (
            vec![patch("src/lib.rs", "missing text", "x")],
            "PATCH_REJECTED",
        ),
        (
            vec![
                patch("src/lib.rs", "value", "value2"),
                patch("src/lib.rs", "value2() -> u8", "value3() -> u8"),
            ],
            "PATCH_REJECTED",
        ),
        (vec![patch("binary.dat", "a", "b")], "PATCH_REJECTED"),
        (
            vec![patch("src/lib.rs", "1 }\n", "2 }\n")],
            "PATCH_REJECTED",
        ),
        (vec![patch("../escape.rs", "a", "b")], "PATCH_REJECTED"),
        (vec![patch("/etc/passwd", "a", "b")], "PATCH_REJECTED"),
    ] {
        let outcome = fixture
            .execute(stage_request(&id, 0, &base, patches, vec![]))
            .await;
        assert_eq!(outcome.status, expected, "{outcome:#?}");
        assert!(outcome.is_error);
        assert_eq!(outcome.data.revision, 0);
    }
    assert_eq!(
        digest(&candidate.join("src/lib.rs")),
        original_candidate_hash
    );

    let stale_revision = fixture
        .execute(stage_request(
            &id,
            9,
            &base,
            vec![patch("src/lib.rs", "1 }\r\n", "2 }\r\n")],
            vec![],
        ))
        .await;
    assert_eq!(stale_revision.status, "STALE");
    let stale_base = fixture
        .execute(stage_request(
            &id,
            0,
            &format!("{base}-wrong"),
            vec![patch("src/lib.rs", "1 }\r\n", "2 }\r\n")],
            vec![],
        ))
        .await;
    assert_eq!(stale_base.status, "STALE");

    // A `\n`-only patch cannot match CRLF bytes, but the CRLF patch succeeds.
    let crlf = fixture
        .execute(stage_request(
            &id,
            0,
            &base,
            vec![patch("src/lib.rs", "1 }\r\n", "2 }\r\n")],
            vec![],
        ))
        .await;
    assert_eq!(crlf.status, "STAGED", "{crlf:#?}");
    assert_eq!(crlf.data.revision, 1);
    assert_eq!(
        fs::read(candidate.join("src/lib.rs")).expect("candidate"),
        b"pub fn value() -> u8 { 2 }\r\n"
    );

    let inspected = fixture.execute(inspect_request(&id)).await;
    assert_eq!(inspected.status, "INSPECTED");
    assert_eq!(inspected.data.state, "ready");
    assert_eq!(inspected.data.revision, 1);
    assert!(
        inspected
            .data
            .patch_hash
            .as_deref()
            .is_some_and(|hash| hash.len() == 64)
    );
    assert!(
        inspected
            .data
            .changed_files
            .iter()
            .any(|file| file == "src/lib.rs")
    );

    // Cancellation before Cargo starts produces no usable evidence.
    let cancellation = CancellationToken::new();
    cancellation.cancel();
    let cancelled = fixture
        .execute_cancellable(validate_request(&id, 1, &base), cancellation)
        .await;
    assert_eq!(cancelled.status, "CANCELLED", "{cancelled:#?}");
    assert!(cancelled.is_error);
    assert!(
        cancelled
            .data
            .evidence
            .iter()
            .all(|evidence| !evidence.fresh)
    );

    // A changed authorization root epoch invalidates validation evidence.
    fixture
        .guard
        .invalidate_client_roots()
        .expect("invalidate root epoch");
    let stale_epoch_workspace = fixture
        .guard
        .snapshot(ClientRoots::unsupported())
        .expect("new root snapshot")
        .select(Some(&fixture.root))
        .expect("select workspace");
    let stale_epoch = fixture
        .service
        .execute(
            validate_request(&id, 1, &base),
            &stale_epoch_workspace,
            CancellationToken::new(),
            None,
        )
        .await;
    assert_eq!(stale_epoch.status, "STALE", "{stale_epoch:#?}");
    assert!(!stale_epoch.data.verified);
}

#[tokio::test]
async fn capture_limits_fail_closed_and_remove_partial_scratch() {
    let fixture = Fixture::new(
        "limits",
        b"pub fn value() -> u8 { 1 }\n",
        false,
        |_root, config| {
            config.change.max_bytes = 1_024;
        },
    );
    fixture.write("large.bin", vec![b'x'; 4_096]);
    let outcome = fixture.execute(create_request()).await;
    assert_eq!(outcome.status, "INCOMPLETE_INPUTS", "{outcome:#?}");
    assert!(outcome.is_error);
    let scratch = fixture.state.join("change");
    let remaining = fs::read_dir(&scratch).expect("read scratch").count();
    assert_eq!(remaining, 0, "partial scratch must be removed");
    assert!(!fixture.root.join("target").exists());
}

#[tokio::test]
async fn create_is_cancellable_and_bounded_by_the_metadata_deadline() {
    let cancelled_fixture = Fixture::new(
        "create-cancel",
        b"pub fn value() -> u8 { 1 }\n",
        false,
        |_root, _config| {},
    );
    let token = CancellationToken::new();
    token.cancel();
    let cancelled = cancelled_fixture
        .execute_cancellable(create_request(), token)
        .await;
    assert_eq!(cancelled.status, "CANCELLED", "{cancelled:#?}");
    assert!(cancelled.is_error);
    assert!(cancelled.data.change_id.is_none());
    assert_eq!(
        fs::read_dir(cancelled_fixture.state.join("change")).map_or(0, Iterator::count),
        0,
        "a cancelled capture must not leave scratch"
    );

    let timed_fixture = Fixture::new(
        "create-timeout",
        b"pub fn value() -> u8 { 1 }\n",
        false,
        |_root, config| {
            config.gate.hard_timeout_ms = 1;
        },
    );
    let timed = timed_fixture.execute(create_request()).await;
    assert_eq!(timed.status, "TIMEOUT", "{timed:#?}");
    assert!(timed.is_error);
    assert!(timed.data.change_id.is_none());
    assert_eq!(
        fs::read_dir(timed_fixture.state.join("change")).map_or(0, Iterator::count),
        0,
        "a timed out capture must not leave scratch"
    );
}

#[tokio::test]
async fn concurrent_changes_do_not_mix_candidates_or_evidence() {
    let fixture = Fixture::new(
        "concurrent",
        b"pub fn value() -> u8 { 1 }\n",
        false,
        |_root, _config| {},
    );
    let first = fixture.execute(create_request()).await;
    let second = fixture.execute(create_request()).await;
    assert_eq!(first.status, "CREATED");
    assert_eq!(second.status, "CREATED");
    let id_first = first.data.change_id.clone().expect("first id");
    let id_second = second.data.change_id.clone().expect("second id");
    assert_ne!(id_first, id_second);
    let base_first = first.data.base_identity.clone().expect("first base");
    let base_second = second.data.base_identity.clone().expect("second base");

    let staged_first = fixture
        .execute(stage_request(
            &id_first,
            0,
            &base_first,
            vec![patch("src/lib.rs", "u8 { 1 }", "u8 { 2 }")],
            vec![],
        ))
        .await;
    let staged_second = fixture
        .execute(stage_request(
            &id_second,
            0,
            &base_second,
            vec![patch("src/lib.rs", "u8 { 1 }", "u8 { 3 }")],
            vec![],
        ))
        .await;
    assert_eq!(staged_first.status, "STAGED");
    assert_eq!(staged_second.status, "STAGED");

    let (validated_first, validated_second) = tokio::join!(
        fixture.execute(validate_request(&id_first, 1, &base_first)),
        fixture.execute(validate_request(&id_second, 1, &base_second))
    );
    assert_eq!(validated_first.status, "PASS", "{validated_first:#?}");
    assert_eq!(validated_second.status, "PASS", "{validated_second:#?}");
    assert!(validated_first.data.verified && validated_second.data.verified);
    for (outcome, id) in [
        (&validated_first, &id_first),
        (&validated_second, &id_second),
    ] {
        assert!(
            outcome
                .data
                .evidence
                .iter()
                .filter(|evidence| evidence.revision == 1)
                .all(|evidence| evidence.command.contains(id)),
            "evidence must reference its own candidate: {outcome:#?}"
        );
    }
    assert!(
        String::from_utf8_lossy(
            &fs::read(fixture.candidate(&id_first).join("src/lib.rs")).unwrap()
        )
        .contains("u8 { 2 }")
    );
    assert!(
        String::from_utf8_lossy(
            &fs::read(fixture.candidate(&id_second).join("src/lib.rs")).unwrap()
        )
        .contains("u8 { 3 }")
    );

    // Per-change serialization: two stages at the same expected revision
    // cannot both apply; the loser sees the new revision and is stale.
    let (first_stage, second_stage) = tokio::join!(
        fixture.execute(stage_request(
            &id_first,
            1,
            &base_first,
            vec![patch("src/lib.rs", "u8 { 2 }", "u8 { 4 }")],
            vec![],
        )),
        fixture.execute(stage_request(
            &id_first,
            1,
            &base_first,
            vec![patch("src/lib.rs", "u8 { 2 }", "u8 { 5 }")],
            vec![],
        ))
    );
    let statuses = [first_stage.status, second_stage.status];
    assert!(statuses.contains(&"STAGED"), "{statuses:?}");
    assert!(statuses.contains(&"STALE"), "{statuses:?}");
}

#[tokio::test]
async fn mismatched_candidate_bytes_cannot_produce_fresh_verified_evidence() {
    let fixture = Fixture::new(
        "mismatch",
        b"pub fn value() -> u8 { 1 }\n",
        false,
        |_root, _config| {},
    );
    let created = fixture.execute(create_request()).await;
    assert_eq!(created.status, "CREATED", "{created:#?}");
    let id = created.data.change_id.clone().expect("change id");
    let base = created.data.base_identity.clone().expect("base");
    let staged = fixture
        .execute(stage_request(
            &id,
            0,
            &base,
            vec![patch("src/lib.rs", "u8 { 1 }", "u8 { 2 }")],
            vec![],
        ))
        .await;
    assert_eq!(staged.status, "STAGED", "{staged:#?}");

    // Simulate an applied-but-unrecorded revision: candidate bytes drift after
    // the record was published.
    fs::write(
        fixture.candidate(&id).join("src/lib.rs"),
        b"pub fn value() -> u8 { 99 }\n",
    )
    .expect("tamper candidate");

    let validated = fixture.execute(validate_request(&id, 1, &base)).await;
    assert_eq!(validated.status, "FAILED_INCONSISTENT", "{validated:#?}");
    assert!(validated.is_error);
    assert!(!validated.data.verified);
    assert!(
        validated
            .data
            .evidence
            .iter()
            .all(|evidence| !evidence.fresh),
        "mismatched bytes must publish no fresh evidence"
    );

    let exported = fixture.execute(export_request(&id)).await;
    assert_eq!(exported.status, "FAILED_INCONSISTENT", "{exported:#?}");
    assert!(exported.is_error);
    assert!(!exported.data.verified);

    let inspected = fixture.execute(inspect_request(&id)).await;
    assert_eq!(inspected.status, "INSPECTED");
    assert_eq!(inspected.data.state, "failed_inconsistent");
}

#[cfg(unix)]
#[tokio::test]
async fn failed_candidate_write_marks_failed_inconsistent_without_fresh_evidence() {
    use std::os::unix::fs::PermissionsExt;

    let fixture = Fixture::new(
        "apply-failure",
        b"pub fn value() -> u8 { 1 }\n",
        false,
        |_root, _config| {},
    );
    let created = fixture.execute(create_request()).await;
    assert_eq!(created.status, "CREATED", "{created:#?}");
    let id = created.data.change_id.clone().expect("change id");
    let base = created.data.base_identity.clone().expect("base");
    let source_dir = fixture.candidate(&id).join("src");
    let mut read_only = fs::metadata(&source_dir).expect("stat src").permissions();
    read_only.set_mode(0o555);
    fs::set_permissions(&source_dir, read_only).expect("make candidate src read-only");
    // Privileged runners can bypass the directory mode; probe once and skip
    // instead of asserting a write failure that cannot happen there.
    if fs::write(source_dir.join(".write-probe"), b"probe").is_ok() {
        let _ = fs::remove_file(source_dir.join(".write-probe"));
        let mut writable = fs::metadata(&source_dir).expect("stat src").permissions();
        writable.set_mode(0o755);
        fs::set_permissions(&source_dir, writable).expect("restore permissions");
        return;
    }

    // Planning succeeds (the file is readable) but the first candidate write
    // fails; the durable failed_inconsistent state must block all evidence.
    let staged = fixture
        .execute(stage_request(
            &id,
            0,
            &base,
            vec![patch("src/lib.rs", "u8 { 1 }", "u8 { 2 }")],
            vec![],
        ))
        .await;

    let mut writable = fs::metadata(&source_dir).expect("stat src").permissions();
    writable.set_mode(0o755);
    fs::set_permissions(&source_dir, writable).expect("restore permissions");

    assert_eq!(staged.status, "FAILED_INCONSISTENT", "{staged:#?}");
    assert!(staged.is_error);
    assert!(!staged.data.verified);
    assert_eq!(
        fs::read(fixture.candidate(&id).join("src/lib.rs")).expect("candidate"),
        b"pub fn value() -> u8 { 1 }\n",
        "a failed apply must not report the planned revision"
    );

    // A failed_inconsistent change accepts no further mutation either.
    let restage = fixture
        .execute(stage_request(
            &id,
            0,
            &base,
            vec![patch("src/lib.rs", "u8 { 1 }", "u8 { 2 }")],
            vec![],
        ))
        .await;
    assert_eq!(restage.status, "FAILED_INCONSISTENT", "{restage:#?}");
    assert!(restage.is_error);

    let inspected = fixture.execute(inspect_request(&id)).await;
    assert_eq!(inspected.status, "INSPECTED", "{inspected:#?}");
    assert_eq!(inspected.data.state, "failed_inconsistent");
    assert_eq!(inspected.data.revision, 0);
    assert!(!inspected.data.verified);

    let validated = fixture.execute(validate_request(&id, 0, &base)).await;
    assert_eq!(validated.status, "FAILED_INCONSISTENT", "{validated:#?}");
    assert!(validated.is_error);
    assert!(!validated.data.verified);
    assert!(validated.data.evidence.iter().all(|row| !row.fresh));

    let exported = fixture.execute(export_request(&id)).await;
    assert_eq!(exported.status, "FAILED_INCONSISTENT", "{exported:#?}");
    assert!(exported.is_error);
    assert!(!exported.data.verified);
}

#[tokio::test]
async fn orphan_applying_marker_refuses_validation_and_recovers_visibly() {
    let fixture = Fixture::new(
        "applying",
        b"pub fn value() -> u8 { 1 }\n",
        false,
        |_root, _config| {},
    );
    let created = fixture.execute(create_request()).await;
    let id = created.data.change_id.clone().expect("change id");
    let base = created.data.base_identity.clone().expect("base");
    let staged = fixture
        .execute(stage_request(
            &id,
            0,
            &base,
            vec![patch("src/lib.rs", "u8 { 1 }", "u8 { 2 }")],
            vec![],
        ))
        .await;
    assert_eq!(staged.status, "STAGED", "{staged:#?}");

    // Simulate a crash between the applying marker and the final publish.
    let record_path = fixture.change_dir(&id).join("record.json");
    let text = fs::read_to_string(&record_path).expect("read record");
    let text = text.replace("\"state\":\"ready\"", "\"state\":\"applying\"");
    assert!(text.contains("\"state\":\"applying\""), "{text}");
    fs::write(&record_path, text).expect("write applying record");

    let blocked_validate = fixture.execute(validate_request(&id, 1, &base)).await;
    assert_eq!(
        blocked_validate.status, "FAILED_INCONSISTENT",
        "{blocked_validate:#?}"
    );
    assert!(!blocked_validate.data.verified);
    let blocked_export = fixture.execute(export_request(&id)).await;
    assert_eq!(
        blocked_export.status, "FAILED_INCONSISTENT",
        "{blocked_export:#?}"
    );
    assert!(!blocked_export.data.verified);

    // Startup recovery marks the orphan visibly instead of silently Ready.
    let recovered = fixture.rebuild_service();
    let inspected = recovered
        .execute(
            inspect_request(&id),
            &fixture.workspace(),
            CancellationToken::new(),
            None,
        )
        .await;
    assert_eq!(inspected.status, "INSPECTED", "{inspected:#?}");
    assert_eq!(inspected.data.state, "failed_inconsistent");
    let after = recovered
        .execute(
            validate_request(&id, 1, &base),
            &fixture.workspace(),
            CancellationToken::new(),
            None,
        )
        .await;
    assert_eq!(after.status, "FAILED_INCONSISTENT", "{after:#?}");
    assert!(after.data.evidence.iter().all(|evidence| !evidence.fresh));
}

#[tokio::test]
async fn stage_and_export_after_epoch_change_are_rejected_without_mutation() {
    let fixture = Fixture::new(
        "epoch",
        b"pub fn value() -> u8 { 1 }\n",
        false,
        |_root, _config| {},
    );
    let created = fixture.execute(create_request()).await;
    let id = created.data.change_id.clone().expect("change id");
    let base = created.data.base_identity.clone().expect("base");
    let staged = fixture
        .execute(stage_request(
            &id,
            0,
            &base,
            vec![patch("src/lib.rs", "u8 { 1 }", "u8 { 2 }")],
            vec![],
        ))
        .await;
    assert_eq!(staged.status, "STAGED");
    let passed = fixture.execute(validate_request(&id, 1, &base)).await;
    assert_eq!(passed.status, "PASS", "{passed:#?}");
    assert!(passed.data.verified);

    fixture
        .guard
        .invalidate_client_roots()
        .expect("invalidate root epoch");
    let candidate_before = digest(&fixture.candidate(&id).join("src/lib.rs"));

    let stale_stage = fixture
        .execute(stage_request(
            &id,
            1,
            &base,
            vec![patch("src/lib.rs", "u8 { 2 }", "u8 { 3 }")],
            vec![],
        ))
        .await;
    assert_eq!(stale_stage.status, "STALE", "{stale_stage:#?}");
    assert!(stale_stage.is_error);
    assert_eq!(
        digest(&fixture.candidate(&id).join("src/lib.rs")),
        candidate_before,
        "a stale stage must not mutate the candidate"
    );
    let inspected = fixture.execute(inspect_request(&id)).await;
    assert_eq!(
        inspected.data.revision, 1,
        "a stale stage must not advance the revision"
    );

    let stale_export = fixture.execute(export_request(&id)).await;
    assert_eq!(stale_export.status, "STALE", "{stale_export:#?}");
    assert!(stale_export.is_error);
    assert!(
        !stale_export.data.verified,
        "a stale epoch must never export verified=true"
    );
}

#[tokio::test]
async fn expected_revision_zero_stages_through_the_json_input_shape() {
    let fixture = Fixture::new(
        "json-zero",
        b"pub fn value() -> u8 { 1 }\n",
        false,
        |_root, _config| {},
    );
    let created = fixture.execute(create_request()).await;
    let id = created.data.change_id.clone().expect("change id");
    let base = created.data.base_identity.clone().expect("base");

    let input: ChangeInput = serde_json::from_value(serde_json::json!({
        "action": "stage",
        "changeId": id,
        "expectedRevision": 0,
        "baseIdentity": base,
        "patches": [
            { "file": "src/lib.rs", "oldString": "u8 { 1 }", "newString": "u8 { 2 }" }
        ]
    }))
    .expect("stage input with expectedRevision 0 must deserialize");
    assert_eq!(input.expected_revision, Some(0));

    let request = ChangeRequest {
        action: input.action,
        change_id: input.change_id.clone(),
        expected_revision: input.expected_revision,
        base_identity: input.base_identity.clone(),
        patches: input.patches.clone(),
        new_files: input.new_files.clone(),
        target: match input.target {
            CheckTarget::Check => GateTargetId::Check,
            CheckTarget::Clippy => GateTargetId::Clippy,
            CheckTarget::Test => GateTargetId::Test,
            CheckTarget::Doc => GateTargetId::Doc,
            CheckTarget::Fmt => GateTargetId::Fmt,
            CheckTarget::All => GateTargetId::All,
        },
        options: input.options.clone(),
        detail: match input.detail {
            CheckDetail::Compact => GateDetail::Compact,
            CheckDetail::Standard => GateDetail::Standard,
            CheckDetail::Full => GateDetail::Full,
        },
        timings: input.timings,
    };
    let staged = fixture.execute(request).await;
    assert_eq!(staged.status, "STAGED", "{staged:#?}");
    assert_eq!(staged.data.revision, 1);
    assert!(
        String::from_utf8_lossy(&fs::read(fixture.candidate(&id).join("src/lib.rs")).unwrap())
            .contains("u8 { 2 }")
    );
}

#[tokio::test]
async fn external_path_dependency_fails_create_closed_without_a_false_pass() {
    let fixture = Fixture::with_setup(
        "external-dep",
        b"pub fn value() -> u8 { 1 }\n",
        false,
        |base| {
            // A build script in the workspace and a relative path dependency
            // outside it: criterion-5 inputs that a scratch copy cannot
            // reproduce byte-for-byte.
            fs::write(
                base.join("workspace/build.rs"),
                "fn main() { println!(\"cargo:rerun-if-changed=build.rs\"); }\n",
            )
            .expect("write workspace build script");
            let dep = base.join("dep");
            fs::create_dir_all(dep.join("src")).expect("create external dependency");
            fs::write(
                dep.join("Cargo.toml"),
                "[package]\nname = \"fixture-dep\"\nversion = \"0.1.0\"\nedition = \"2024\"\n\n[workspace]\n",
            )
            .expect("write dependency manifest");
            fs::write(dep.join("src/lib.rs"), "pub fn dep_value() -> u8 { 7 }\n")
                .expect("write dependency source");
        },
        |root, config| {
            let dep = root.parent().expect("fixture base").join("dep");
            config.server.allow_dependency_roots = vec![dep];
            fs::write(
                root.join("Cargo.toml"),
                "[package]\nname = \"change-fixture\"\nversion = \"0.1.0\"\nedition = \"2024\"\nbuild = \"build.rs\"\n\n[dependencies]\nfixture-dep = { path = \"../dep\" }\n\n[workspace]\n",
            )
            .expect("write manifest with relative path dependency");
            fs::write(
                root.join("Cargo.lock"),
                "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"change-fixture\"\nversion = \"0.1.0\"\ndependencies = [\n \"fixture-dep\",\n]\n\n[[package]]\nname = \"fixture-dep\"\nversion = \"0.1.0\"\n",
            )
            .expect("write lockfile with path dependency");
        },
    );

    let outcome = fixture.execute(create_request()).await;
    assert_eq!(outcome.status, "INCOMPLETE_INPUTS", "{outcome:#?}");
    assert!(outcome.is_error);
    assert!(
        outcome.data.change_id.is_none(),
        "an incomplete capture must not publish a change id"
    );
    assert!(
        outcome.data.reason.contains("cannot be reproduced") && outcome.data.reason.contains("dep"),
        "the unreproducible dependency must be listed with the fail-closed reason: {}",
        outcome.data.reason
    );
    let scratch = fixture.state.join("change");
    let remaining = fs::read_dir(&scratch).map_or(0, Iterator::count);
    assert_eq!(
        remaining, 0,
        "no candidate scratch may exist for an incomplete capture"
    );
}

#[tokio::test]
async fn validate_pins_revision_and_identity_and_rejects_mismatch() {
    let fixture = Fixture::new(
        "validate-pins",
        b"pub fn value() -> u8 { 1 }\n",
        false,
        |_root, _config| {},
    );
    let created = fixture.execute(create_request()).await;
    let id = created.data.change_id.clone().expect("change id");
    let base = created.data.base_identity.clone().expect("base");
    let staged = fixture
        .execute(stage_request(
            &id,
            0,
            &base,
            vec![patch("src/lib.rs", "u8 { 1 }", "u8 { 2 }")],
            vec![],
        ))
        .await;
    assert_eq!(staged.status, "STAGED");

    let wrong_revision = fixture.execute(validate_request(&id, 0, &base)).await;
    assert_eq!(wrong_revision.status, "STALE", "{wrong_revision:#?}");
    assert!(wrong_revision.data.evidence.iter().all(|row| !row.fresh));
    let wrong_base = fixture
        .execute(validate_request(&id, 1, "not-the-base"))
        .await;
    assert_eq!(wrong_base.status, "STALE", "{wrong_base:#?}");
    assert!(wrong_base.data.evidence.iter().all(|row| !row.fresh));

    let passed = fixture.execute(validate_request(&id, 1, &base)).await;
    assert_eq!(passed.status, "PASS", "{passed:#?}");
    assert!(passed.data.verified);
    assert!(
        passed.data.evidence.iter().all(|row| row.revision == 1),
        "evidence must identify its own revision: {passed:#?}"
    );
    assert!(
        passed
            .data
            .evidence
            .iter()
            .any(|row| row.revision == 1 && row.fresh && row.authoritative)
    );
}
