use std::{
    fs,
    path::{Path, PathBuf},
    process::Command,
    sync::{Arc, Mutex},
    time::{Duration, SystemTime, UNIX_EPOCH},
};

use agz_rust_coder::{
    Config,
    config::GateScope as ConfigGateScope,
    gate::{GateAuthority, GateRequest, GateScopeStrategy, GateStatus, GateTargetId},
    tools::CheckService,
    workspace::RootGuard,
};

struct TestProject {
    root: PathBuf,
    state: PathBuf,
}

impl TestProject {
    fn new(label: &str, source: &str, build_script: Option<&str>) -> Self {
        let stamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map_or(0, |duration| duration.as_nanos());
        let base = fs::canonicalize(std::env::temp_dir())
            .expect("canonical temp directory")
            .join(format!(
                "agz-rust-coder-check-{label}-{}-{stamp}",
                std::process::id()
            ));
        let root = base.join("workspace");
        let state = base.join("state");
        fs::create_dir_all(root.join("src")).expect("create project source directory");
        fs::create_dir_all(&state).expect("create project state directory");
        fs::write(
            root.join("Cargo.toml"),
            "[package]\nname = \"check-fixture\"\nversion = \"0.1.0\"\nedition = \"2024\"\n\n[workspace]\n",
        )
        .expect("write manifest");
        fs::write(
            root.join("Cargo.lock"),
            "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"check-fixture\"\nversion = \"0.1.0\"\n",
        )
        .expect("write lockfile");
        fs::write(root.join("src/lib.rs"), source).expect("write source");
        if let Some(build_script) = build_script {
            fs::write(root.join("build.rs"), build_script).expect("write build script");
        }
        git(&root, &["init", "--quiet"]);
        git(&root, &["config", "user.email", "check@example.invalid"]);
        git(&root, &["config", "user.name", "Check Fixture"]);
        git(&root, &["add", "."]);
        git(&root, &["commit", "--quiet", "-m", "fixture"]);
        Self { root, state }
    }

    fn service(&self) -> Arc<CheckService> {
        self.service_with_scope(ConfigGateScope::Shadow)
    }

    fn service_with_scope(&self, scope: ConfigGateScope) -> Arc<CheckService> {
        let mut config = Config::defaults_at(&self.root);
        config.gate.debounce_ms = 10;
        config.gate.hard_timeout_ms = 60_000;
        config.gate.cache_dir = self.state.join("cache");
        config.gate.lease_dir = self.state.join("leases");
        config.gate.scope = scope;
        let guard = Arc::new(
            RootGuard::new([self.root.clone()], std::iter::empty()).expect("create root guard"),
        );
        Arc::new(CheckService::new(config, guard))
    }

    fn service_with_cargo(&self, cargo: PathBuf) -> Arc<CheckService> {
        let mut config = Config::defaults_at(&self.root);
        config.gate.debounce_ms = 10;
        config.gate.hard_timeout_ms = 60_000;
        config.gate.cache_dir = self.state.join("cache");
        config.gate.lease_dir = self.state.join("leases");
        config.cargo.path = Some(cargo);
        let guard = Arc::new(
            RootGuard::new([self.root.clone()], std::iter::empty()).expect("create root guard"),
        );
        Arc::new(CheckService::new(config, guard))
    }
}

#[tokio::test]
async fn check_scope_applies_workspace_shadow_and_affected_contracts() {
    let project = TestProject::new("scope", "pub fn value() -> usize { 1 }\n", None);
    let affected = project.service_with_scope(ConfigGateScope::Affected);

    let clean = affected
        .run(
            GateRequest::new(&project.root, GateTargetId::Check),
            None,
            None,
        )
        .await;
    assert_eq!(clean.scope.strategy, GateScopeStrategy::Workspace);
    assert!(
        clean
            .scope
            .widened_because
            .iter()
            .any(|reason| reason.contains("empty"))
    );
    assert!(clean.steps[0].command.contains(&"--workspace".to_owned()));

    fs::write(
        project.root.join("src/lib.rs"),
        "pub fn value() -> usize { 2 }\n",
    )
    .expect("modify owned package source");
    let narrowed = affected
        .run(
            GateRequest::new(&project.root, GateTargetId::Check),
            None,
            None,
        )
        .await;
    assert_eq!(narrowed.scope.strategy, GateScopeStrategy::Affected);
    assert_eq!(narrowed.scope.packages, ["check-fixture"]);
    assert!(narrowed.steps[0].command.contains(&"-p".to_owned()));
    assert!(
        narrowed.steps[0]
            .command
            .contains(&"check-fixture".to_owned())
    );
    affected.close().await;

    let shadow = project.service_with_scope(ConfigGateScope::Shadow);
    let measured = shadow
        .run(
            GateRequest::new(&project.root, GateTargetId::Check),
            None,
            None,
        )
        .await;
    assert_eq!(measured.scope.strategy, GateScopeStrategy::Shadow);
    assert_eq!(measured.scope.packages, ["check-fixture"]);
    assert!(
        measured.steps[0]
            .command
            .contains(&"--workspace".to_owned())
    );
    shadow.close().await;
}

impl Drop for TestProject {
    fn drop(&mut self) {
        if let Some(base) = self.root.parent() {
            let _ = fs::remove_dir_all(base);
        }
    }
}

fn git(root: &Path, arguments: &[&str]) {
    let status = Command::new("git")
        .args(arguments)
        .current_dir(root)
        .status()
        .expect("run git fixture command");
    assert!(status.success(), "git command failed: {arguments:?}");
}

#[tokio::test]
async fn clean_fast_and_full_targets_grant_only_their_declared_authority() {
    let project = TestProject::new("authority", "pub fn answer() -> u32 {\n    42\n}\n", None);
    let service = project.service();

    let fast = service
        .run(
            GateRequest::new(&project.root, GateTargetId::Check),
            None,
            None,
        )
        .await;
    assert_eq!(fast.status, GateStatus::FastPass);
    assert_eq!(fast.authority, GateAuthority::Fast);

    let full = service
        .run(GateRequest::for_all(&project.root), None, None)
        .await;
    assert_eq!(full.status, GateStatus::FullPass, "{full:#?}");
    assert_eq!(full.authority, GateAuthority::Full);
    assert_ne!(fast.job_id, full.job_id);
    service.close().await;
}

#[tokio::test]
async fn broken_source_fails_without_authority_and_keeps_compiler_evidence() {
    let project = TestProject::new(
        "broken",
        "pub fn broken() -> u32 { let value: u32 = \"wrong\"; value }\n",
        None,
    );
    let service = project.service();
    let evidence = service
        .run(
            GateRequest::new(&project.root, GateTargetId::Check),
            None,
            None,
        )
        .await;
    assert_eq!(evidence.status, GateStatus::Fail);
    assert_eq!(evidence.authority, GateAuthority::None);
    assert!(
        evidence
            .steps
            .iter()
            .flat_map(|step| &step.diagnostics)
            .any(|diagnostic| diagnostic.code.as_deref() == Some("E0308"))
    );
    service.close().await;
}

#[tokio::test]
async fn active_identical_requests_singleflight_but_completed_pass_is_not_reused() {
    let project = TestProject::new("singleflight", "pub fn value() -> usize { 1 }\n", None);
    let service = project.service();
    let request = GateRequest::new(&project.root, GateTargetId::Check);
    let (first, second) = tokio::join!(
        service.run(request.clone(), None, None),
        service.run(request.clone(), None, None)
    );
    assert_eq!(first.status, GateStatus::FastPass);
    assert_eq!(first.job_id, second.job_id);

    let later = service.run(request, None, None).await;
    assert_eq!(later.status, GateStatus::FastPass);
    assert_ne!(later.job_id, first.job_id);
    service.close().await;
}

#[tokio::test]
async fn source_change_after_admission_makes_a_successful_run_stale() {
    let project = TestProject::new(
        "stale",
        "pub fn value() -> usize { 1 }\n",
        Some("fn main() { std::thread::sleep(std::time::Duration::from_millis(400)); }\n"),
    );
    let service = project.service();
    let request = GateRequest::new(&project.root, GateTargetId::Check);
    let running = {
        let service = Arc::clone(&service);
        tokio::spawn(async move { service.run(request, None, None).await })
    };
    for _ in 0..100 {
        if service.active_count() > 0 {
            break;
        }
        tokio::time::sleep(Duration::from_millis(5)).await;
    }
    assert!(service.active_count() > 0, "check job never became active");
    fs::write(
        project.root.join("src/lib.rs"),
        "pub fn value() -> usize { 2 }\n",
    )
    .expect("mutate source during check");

    let evidence = running.await.expect("join check job");
    assert_eq!(evidence.status, GateStatus::Stale);
    assert_eq!(evidence.authority, GateAuthority::None);
    service.close().await;
}

#[tokio::test]
async fn progress_reports_preflight_and_running_stages() {
    let project = TestProject::new("progress", "pub fn value() -> usize { 1 }\n", None);
    let service = project.service();
    let events = Arc::new(Mutex::new(Vec::new()));
    let callback = {
        let events = Arc::clone(&events);
        Arc::new(move |event: agz_rust_coder::gate::ProgressEvent| {
            events.lock().expect("progress lock").push(event.stage);
        }) as agz_rust_coder::gate::ProgressCallback
    };

    let evidence = service
        .run(
            GateRequest::new(&project.root, GateTargetId::Check),
            Some(callback),
            None,
        )
        .await;
    assert_eq!(evidence.status, GateStatus::FastPass);
    {
        let events = events.lock().expect("progress lock");
        assert!(events.contains(&agz_rust_coder::gate::ProgressStage::Accepted));
        assert!(events.contains(&agz_rust_coder::gate::ProgressStage::Preflight));
        assert!(events.contains(&agz_rust_coder::gate::ProgressStage::Running));
        assert!(events.contains(&agz_rust_coder::gate::ProgressStage::Completed));
    }
    service.close().await;
}

#[tokio::test]
async fn cancellation_detaches_the_last_subscriber_and_cleans_the_job() {
    let project = TestProject::new(
        "cancel",
        "pub fn value() -> usize { 1 }\n",
        Some("fn main() { std::thread::sleep(std::time::Duration::from_secs(5)); }\n"),
    );
    let service = project.service();
    let cancellation = tokio_util::sync::CancellationToken::new();
    let running = {
        let service = Arc::clone(&service);
        let root = project.root.clone();
        let cancellation = cancellation.clone();
        tokio::spawn(async move {
            service
                .run(
                    GateRequest::new(root, GateTargetId::Check),
                    None,
                    Some(cancellation),
                )
                .await
        })
    };
    for _ in 0..200 {
        if service.active_count() > 0 {
            break;
        }
        tokio::time::sleep(Duration::from_millis(5)).await;
    }
    assert!(service.active_count() > 0, "check job never became active");
    cancellation.cancel();
    let evidence = running.await.expect("join cancelled check");
    assert_eq!(evidence.status, GateStatus::Cancelled);
    for _ in 0..200 {
        if service.active_count() == 0 {
            break;
        }
        tokio::time::sleep(Duration::from_millis(5)).await;
    }
    assert_eq!(service.active_count(), 0);
    service.close().await;
}

#[cfg(unix)]
#[tokio::test]
async fn preflight_cancellation_does_not_start_cargo() {
    use std::os::unix::fs::PermissionsExt;

    let project = TestProject::new("preflight-cancel", "pub fn value() -> usize { 1 }\n", None);
    let marker = project.state.join("cargo-started");
    let cargo = project.state.join("fake-cargo");
    fs::write(
        &cargo,
        format!("#!/bin/sh\ntouch '{}'\nexit 1\n", marker.display()),
    )
    .expect("write fake cargo");
    let mut permissions = fs::metadata(&cargo)
        .expect("fake cargo metadata")
        .permissions();
    permissions.set_mode(0o755);
    fs::set_permissions(&cargo, permissions).expect("make fake cargo executable");

    let service = project.service_with_cargo(cargo);
    let cancellation = tokio_util::sync::CancellationToken::new();
    cancellation.cancel();
    let evidence = service
        .run(
            GateRequest::new(&project.root, GateTargetId::Check),
            None,
            Some(cancellation),
        )
        .await;

    assert_eq!(evidence.status, GateStatus::Cancelled);
    assert!(
        !marker.exists(),
        "pre-cancelled preflight must not run Cargo"
    );
    service.close().await;
}

#[cfg(unix)]
#[tokio::test]
async fn selected_child_replacement_cannot_run_the_check_target() {
    use std::sync::atomic::{AtomicBool, Ordering};

    let project = TestProject::new(
        "selected-child-replacement",
        "pub fn value() -> usize { 1 }\n",
        None,
    );
    let configured_parent = project
        .root
        .parent()
        .expect("workspace has a configured parent")
        .to_owned();
    let original = configured_parent.join("workspace-original");
    let marker = project.state.join("replacement-check-ran");

    let mut config = Config::defaults_at(&project.root);
    config.gate.debounce_ms = 10;
    config.gate.hard_timeout_ms = 60_000;
    config.gate.cache_dir = project.state.join("cache");
    config.gate.lease_dir = project.state.join("leases");
    config.gate.scope = ConfigGateScope::Workspace;
    let guard = Arc::new(
        RootGuard::new([configured_parent], std::iter::empty())
            .expect("authorize configured parent"),
    );
    let service = Arc::new(CheckService::new(config, guard));

    let swapped = Arc::new(AtomicBool::new(false));
    let callback = {
        let root = project.root.clone();
        let original = original.clone();
        let marker = marker.clone();
        let swapped = Arc::clone(&swapped);
        Arc::new(move |event: agz_rust_coder::gate::ProgressEvent| {
            if event.stage != agz_rust_coder::gate::ProgressStage::Running
                || swapped.swap(true, Ordering::SeqCst)
            {
                return;
            }
            fs::rename(&root, &original).expect("rename selected child workspace");
            fs::create_dir_all(root.join("src")).expect("create replacement source directory");
            fs::write(
                root.join("Cargo.toml"),
                "[package]\nname = \"check-fixture\"\nversion = \"0.1.0\"\nedition = \"2024\"\nbuild = \"build.rs\"\n\n[workspace]\n",
            )
            .expect("write replacement manifest");
            fs::write(
                root.join("Cargo.lock"),
                "version = 4\n\n[[package]]\nname = \"check-fixture\"\nversion = \"0.1.0\"\n",
            )
            .expect("write replacement lockfile");
            fs::write(root.join("src/lib.rs"), "pub fn replacement() {}\n")
                .expect("write replacement source");
            fs::write(
                root.join("build.rs"),
                format!(
                    "fn main() {{ std::fs::write({:?}, b\"replacement check ran\").unwrap(); }}\n",
                    marker.to_string_lossy()
                ),
            )
            .expect("write replacement build script");
        }) as agz_rust_coder::gate::ProgressCallback
    };

    let evidence = service
        .run(
            GateRequest::new(&project.root, GateTargetId::Check),
            Some(callback),
            None,
        )
        .await;

    assert!(
        swapped.load(Ordering::SeqCst),
        "replacement hook did not run"
    );
    assert_eq!(evidence.authority, GateAuthority::None, "{evidence:#?}");
    assert!(!marker.exists(), "replacement Cargo target must not run");
    assert!(original.join("Cargo.toml").is_file());
    service.close().await;
}

#[tokio::test]
async fn different_root_epochs_do_not_join_an_active_job() {
    let project = TestProject::new(
        "root-epoch",
        "pub fn value() -> usize { 1 }\n",
        Some("fn main() { std::thread::sleep(std::time::Duration::from_millis(500)); }\n"),
    );
    let service = project.service();
    let first = {
        let service = Arc::clone(&service);
        let root = project.root.clone();
        tokio::spawn(async move {
            service
                .run(
                    GateRequest::new(root, GateTargetId::Check).with_root_epoch(1),
                    None,
                    None,
                )
                .await
        })
    };
    for _ in 0..200 {
        if service.active_count() > 0 {
            break;
        }
        tokio::time::sleep(Duration::from_millis(5)).await;
    }
    assert!(service.active_count() > 0, "check job never became active");
    let second = {
        let service = Arc::clone(&service);
        let root = project.root.clone();
        tokio::spawn(async move {
            service
                .run(
                    GateRequest::new(root, GateTargetId::Check).with_root_epoch(2),
                    None,
                    None,
                )
                .await
        })
    };
    let first = first.await.expect("join first epoch check");
    let second = second.await.expect("join second epoch check");
    assert_eq!(first.status, GateStatus::FastPass, "{first:#?}");
    assert_eq!(second.status, GateStatus::FastPass, "{second:#?}");
    assert_ne!(first.job_id, second.job_id);
    service.close().await;
}

#[tokio::test]
async fn a_new_input_supersedes_the_older_active_job() {
    let project = TestProject::new(
        "supersede",
        "pub fn value() -> usize { 1 }\n",
        Some("fn main() { std::thread::sleep(std::time::Duration::from_millis(500)); }\n"),
    );
    let service = project.service();
    let first = {
        let service = Arc::clone(&service);
        let root = project.root.clone();
        tokio::spawn(async move {
            service
                .run(GateRequest::new(root, GateTargetId::Check), None, None)
                .await
        })
    };
    for _ in 0..200 {
        if service.active_count() > 0 {
            break;
        }
        tokio::time::sleep(Duration::from_millis(5)).await;
    }
    fs::write(
        project.root.join("src/lib.rs"),
        "pub fn value() -> usize { 2 }\n",
    )
    .expect("write new source generation");
    let second = service
        .run(
            GateRequest::new(&project.root, GateTargetId::Check),
            None,
            None,
        )
        .await;
    let first = first.await.expect("join superseded check");
    assert_eq!(first.status, GateStatus::Superseded, "{first:#?}");
    assert_eq!(second.status, GateStatus::FastPass, "{second:#?}");
    service.close().await;
}

#[tokio::test]
async fn streamed_error_has_request_timing_and_bounded_source_context() {
    use agz_rust_coder::gate::ValidationOptions;
    let project = TestProject::new(
        "context",
        "pub fn broken() -> u32 { let value: u32 = \"wrong\"; value }\n",
        None,
    );
    let service = project.service();
    let evidence = service
        .run(
            GateRequest::new(&project.root, GateTargetId::Check).with_options(ValidationOptions {
                context: true,
                ..Default::default()
            }),
            None,
            None,
        )
        .await;
    assert_eq!(evidence.status, GateStatus::Fail, "{evidence:#?}");
    assert!(evidence.first_diagnostic_ms.is_some());
    assert!(evidence.first_diagnostic_ms.unwrap() <= evidence.response_ms);
    let step = &evidence.steps[0];
    assert!(step.evidence.diagnostic_records > 0);
    assert!(step.first_diagnostic_ms.is_some());
    assert!(
        step.contexts.iter().any(|c| c.excerpt.contains("wrong")
            && c.source_hash.is_some()
            && c.freshness == "input-identity-matched"),
        "{:?}",
        step.contexts
    );
    assert!(step.contexts.iter().all(|c| c.untrusted_data));
    service.close().await;
}

#[tokio::test]
async fn explicit_features_are_executed_and_distinguish_validation_profiles() {
    use agz_rust_coder::gate::ValidationOptions;
    let project = TestProject::new(
        "features",
        "#[cfg(feature = \"broken\")]\ncompile_error!(\"selected feature fails\");\npub fn value() {}\n",
        None,
    );
    let manifest = project.root.join("Cargo.toml");
    fs::write(
        &manifest,
        format!(
            "{}\n[features]\ndefault = []\nbroken = []\n",
            fs::read_to_string(&manifest).unwrap()
        ),
    )
    .unwrap();
    let service = project.service_with_scope(ConfigGateScope::Affected);
    let good = service
        .run(
            GateRequest::new(&project.root, GateTargetId::Check),
            None,
            None,
        )
        .await;
    let options = ValidationOptions {
        features: vec!["broken".into()],
        ..Default::default()
    };
    let bad = service
        .run(
            GateRequest::new(&project.root, GateTargetId::Check).with_options(options.clone()),
            None,
            None,
        )
        .await;
    assert_eq!(good.status, GateStatus::FastPass, "{good:#?}");
    assert_eq!(bad.status, GateStatus::Fail, "{bad:#?}");
    assert_eq!(bad.scope.strategy, GateScopeStrategy::Workspace);
    assert_eq!(bad.profile.as_ref().unwrap().options, options);
    assert_ne!(good.command_hash, bad.command_hash);
    service.close().await;
}

#[tokio::test]
async fn clippy_and_test_scope_widens_for_build_scripts() {
    let project = TestProject::new("scope2", "pub fn value() {}\n", None);
    let service = project.service_with_scope(ConfigGateScope::Affected);
    fs::write(
        project.root.join("src/lib.rs"),
        "pub fn value() {}\n#[test] fn works() { value(); }\n",
    )
    .unwrap();
    for target in [GateTargetId::Clippy, GateTargetId::Test] {
        let narrow = service
            .run(GateRequest::new(&project.root, target), None, None)
            .await;
        assert_eq!(narrow.status, GateStatus::FastPass, "{narrow:#?}");
        assert_eq!(narrow.scope.strategy, GateScopeStrategy::Affected);
    }
    fs::write(project.root.join("build.rs"), "fn main() {}\n").unwrap();
    let broad = service
        .run(
            GateRequest::new(&project.root, GateTargetId::Clippy),
            None,
            None,
        )
        .await;
    assert_eq!(
        broad.scope.strategy,
        GateScopeStrategy::Workspace,
        "{broad:#?}"
    );
    service.close().await;
}

#[tokio::test]
#[ignore = "requires checksum-verified cargo-nextest 0.9.143 on PATH"]
async fn real_nextest_executes_test_filters_and_keeps_doctest_stage() {
    use agz_rust_coder::gate::{TestRunner, ValidationOptions};
    let project = TestProject::new(
        "nx",
        "pub fn value() {}\n#[test]\nfn works() {}\n#[test]\nfn fails() { panic!(\"expected failure\"); }\n",
        None,
    );
    let service = project.service();
    let options = ValidationOptions {
        runner: TestRunner::Nextest,
        test_filter: Some("works".into()),
        ..Default::default()
    };
    let good = service
        .run(
            GateRequest::new(&project.root, GateTargetId::Test).with_options(options.clone()),
            None,
            None,
        )
        .await;
    assert_eq!(good.status, GateStatus::FastPass, "{good:#?}");
    let bad = service
        .run(
            GateRequest::new(&project.root, GateTargetId::Test).with_options(ValidationOptions {
                test_filter: Some("fails".into()),
                ..options.clone()
            }),
            None,
            None,
        )
        .await;
    assert_eq!(bad.status, GateStatus::Fail, "{bad:#?}");
    let none = service
        .run(
            GateRequest::new(&project.root, GateTargetId::Test).with_options(ValidationOptions {
                test_filter: Some("no_such_test".into()),
                ..options
            }),
            None,
            None,
        )
        .await;
    assert_eq!(none.status, GateStatus::Fail, "{none:#?}");
    // A compile-failing doctest cannot be skipped by an otherwise passing nextest run.
    fs::write(project.root.join("src/lib.rs"),"/// ```\n/// let value: u32 = \"wrong\";\n/// ```\npub fn value() {}\n#[test]\nfn works() {}\n").unwrap();
    let all = service
        .run(
            GateRequest::for_all(&project.root).with_options(ValidationOptions {
                runner: TestRunner::Nextest,
                ..Default::default()
            }),
            None,
            None,
        )
        .await;
    assert_eq!(all.status, GateStatus::Fail, "{all:#?}");
    assert!(
        all.steps
            .iter()
            .any(|s| s.target == GateTargetId::Doc && s.exit_code != 0),
        "{all:#?}"
    );
    service.close().await;
}

#[cfg(unix)]
#[tokio::test]
#[ignore = "requires explicit RUSTC_WRAPPER pointing to checksum-verified sccache 0.17.0"]
async fn real_sccache_compiles_and_cleans_the_owned_server() {
    use agz_rust_coder::gate::ValidationOptions;
    let project = TestProject::new("sc", "pub fn value() {}\n", None);
    let service = project.service();
    let evidence = service
        .run(
            GateRequest::new(&project.root, GateTargetId::Check).with_options(ValidationOptions {
                sccache: true,
                ..Default::default()
            }),
            None,
            None,
        )
        .await;
    assert_eq!(evidence.status, GateStatus::FastPass, "{evidence:#?}");
    assert!(evidence.warnings.iter().any(|s| s.contains("client-side")));
    let entries = fs::read_dir(project.state.join("leases")).unwrap();
    assert!(
        !entries
            .filter_map(Result::ok)
            .any(|e| e.file_name().to_string_lossy().starts_with("sc-"))
    );
    service.close().await;
}

#[tokio::test]
async fn filtered_cargo_with_no_executed_tests_cannot_grant_a_pass() {
    use agz_rust_coder::gate::ValidationOptions;
    let project = TestProject::new("empty-filter", "#[test] fn works() {}\n", None);
    let service = project.service();
    for (filter, expected) in [
        ("works", GateStatus::FastPass),
        ("does_not_exist", GateStatus::Inconclusive),
    ] {
        let result = service
            .run(
                GateRequest::new(&project.root, GateTargetId::Test).with_options(
                    ValidationOptions {
                        test_filter: Some(filter.into()),
                        ..Default::default()
                    },
                ),
                None,
                None,
            )
            .await;
        assert_eq!(result.status, expected, "{result:#?}");
    }
    service.close().await;
}
