use std::{
    fs,
    path::{Path, PathBuf},
    process::Command,
    sync::{Arc, Mutex},
    time::{Duration, SystemTime, UNIX_EPOCH},
};

use agz_rust_coder::{
    Config,
    config::GateScope as ConfigGateScope,
    gate::{GateAuthority, GateRequest, GateScopeStrategy, GateStatus, GateTargetId},
    tools::CheckService,
    workspace::RootGuard,
};

struct TestProject {
    root: PathBuf,
    state: PathBuf,
}

impl TestProject {
    fn new(label: &str, source: &str, build_script: Option<&str>) -> Self {
        let stamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map_or(0, |duration| duration.as_nanos());
        let base = fs::canonicalize(std::env::temp_dir())
            .expect("canonical temp directory")
            .join(format!(
                "agz-rust-coder-check-{label}-{}-{stamp}",
                std::process::id()
            ));
        let root = base.join("workspace");
        let state = base.join("state");
        fs::create_dir_all(root.join("src")).expect("create project source directory");
        fs::create_dir_all(&state).expect("create project state directory");
        fs::write(
            root.join("Cargo.toml"),
            "[package]\nname = \"check-fixture\"\nversion = \"0.1.0\"\nedition = \"2024\"\n\n[workspace]\n",
        )
        .expect("write manifest");
        fs::write(
            root.join("Cargo.lock"),
            "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"check-fixture\"\nversion = \"0.1.0\"\n",
        )
        .expect("write lockfile");
        fs::write(root.join("src/lib.rs"), source).expect("write source");
        if let Some(build_script) = build_script {
            fs::write(root.join("build.rs"), build_script).expect("write build script");
        }
        git(&root, &["init", "--quiet"]);
        git(&root, &["config", "user.email", "check@example.invalid"]);
        git(&root, &["config", "user.name", "Check Fixture"]);
        git(&root, &["add", "."]);
        git(&root, &["commit", "--quiet", "-m", "fixture"]);
        Self { root, state }
    }

    fn service(&self) -> Arc<CheckService> {
        self.service_with_scope(ConfigGateScope::Shadow)
    }

    fn service_with_scope(&self, scope: ConfigGateScope) -> Arc<CheckService> {
        let mut config = Config::defaults_at(&self.root);
        config.gate.debounce_ms = 10;
        config.gate.hard_timeout_ms = 60_000;
        config.gate.cache_dir = self.state.join("cache");
        config.gate.lease_dir = self.state.join("leases");
        config.gate.scope = scope;
        let guard = Arc::new(
            RootGuard::new([self.root.clone()], std::iter::empty()).expect("create root guard"),
        );
        Arc::new(CheckService::new(config, guard))
    }
}

#[tokio::test]
async fn check_scope_applies_workspace_shadow_and_affected_contracts() {
    let project = TestProject::new("scope", "pub fn value() -> usize { 1 }\n", None);
    let affected = project.service_with_scope(ConfigGateScope::Affected);

    let clean = affected
        .run(
            GateRequest::new(&project.root, GateTargetId::Check),
            None,
            None,
        )
        .await;
    assert_eq!(clean.scope.strategy, GateScopeStrategy::Workspace);
    assert!(
        clean
            .scope
            .widened_because
            .iter()
            .any(|reason| reason.contains("empty"))
    );
    assert!(clean.steps[0].command.contains(&"--workspace".to_owned()));

    fs::write(
        project.root.join("src/lib.rs"),
        "pub fn value() -> usize { 2 }\n",
    )
    .expect("modify owned package source");
    let narrowed = affected
        .run(
            GateRequest::new(&project.root, GateTargetId::Check),
            None,
            None,
        )
        .await;
    assert_eq!(narrowed.scope.strategy, GateScopeStrategy::Affected);
    assert_eq!(narrowed.scope.packages, ["check-fixture"]);
    assert!(narrowed.steps[0].command.contains(&"-p".to_owned()));
    assert!(
        narrowed.steps[0]
            .command
            .contains(&"check-fixture".to_owned())
    );
    affected.close().await;

    let shadow = project.service_with_scope(ConfigGateScope::Shadow);
    let measured = shadow
        .run(
            GateRequest::new(&project.root, GateTargetId::Check),
            None,
            None,
        )
        .await;
    assert_eq!(measured.scope.strategy, GateScopeStrategy::Shadow);
    assert_eq!(measured.scope.packages, ["check-fixture"]);
    assert!(
        measured.steps[0]
            .command
            .contains(&"--workspace".to_owned())
    );
    shadow.close().await;
}

impl Drop for TestProject {
    fn drop(&mut self) {
        if let Some(base) = self.root.parent() {
            let _ = fs::remove_dir_all(base);
        }
    }
}

fn git(root: &Path, arguments: &[&str]) {
    let status = Command::new("git")
        .args(arguments)
        .current_dir(root)
        .status()
        .expect("run git fixture command");
    assert!(status.success(), "git command failed: {arguments:?}");
}

#[tokio::test]
async fn clean_fast_and_full_targets_grant_only_their_declared_authority() {
    let project = TestProject::new("authority", "pub fn answer() -> u32 {\n    42\n}\n", None);
    let service = project.service();

    let fast = service
        .run(
            GateRequest::new(&project.root, GateTargetId::Check),
            None,
            None,
        )
        .await;
    assert_eq!(fast.status, GateStatus::FastPass);
    assert_eq!(fast.authority, GateAuthority::Fast);

    let full = service
        .run(GateRequest::for_all(&project.root), None, None)
        .await;
    assert_eq!(full.status, GateStatus::FullPass, "{full:#?}");
    assert_eq!(full.authority, GateAuthority::Full);
    assert_ne!(fast.job_id, full.job_id);
    service.close().await;
}

#[tokio::test]
async fn broken_source_fails_without_authority_and_keeps_compiler_evidence() {
    let project = TestProject::new(
        "broken",
        "pub fn broken() -> u32 { let value: u32 = \"wrong\"; value }\n",
        None,
    );
    let service = project.service();
    let evidence = service
        .run(
            GateRequest::new(&project.root, GateTargetId::Check),
            None,
            None,
        )
        .await;
    assert_eq!(evidence.status, GateStatus::Fail);
    assert_eq!(evidence.authority, GateAuthority::None);
    assert!(
        evidence
            .steps
            .iter()
            .flat_map(|step| &step.diagnostics)
            .any(|diagnostic| diagnostic.code.as_deref() == Some("E0308"))
    );
    service.close().await;
}

#[tokio::test]
async fn active_identical_requests_singleflight_but_completed_pass_is_not_reused() {
    let project = TestProject::new("singleflight", "pub fn value() -> usize { 1 }\n", None);
    let service = project.service();
    let request = GateRequest::new(&project.root, GateTargetId::Check);
    let (first, second) = tokio::join!(
        service.run(request.clone(), None, None),
        service.run(request.clone(), None, None)
    );
    assert_eq!(first.status, GateStatus::FastPass);
    assert_eq!(first.job_id, second.job_id);

    let later = service.run(request, None, None).await;
    assert_eq!(later.status, GateStatus::FastPass);
    assert_ne!(later.job_id, first.job_id);
    service.close().await;
}

#[tokio::test]
async fn source_change_after_admission_makes_a_successful_run_stale() {
    let project = TestProject::new(
        "stale",
        "pub fn value() -> usize { 1 }\n",
        Some("fn main() { std::thread::sleep(std::time::Duration::from_millis(400)); }\n"),
    );
    let service = project.service();
    let request = GateRequest::new(&project.root, GateTargetId::Check);
    let running = {
        let service = Arc::clone(&service);
        tokio::spawn(async move { service.run(request, None, None).await })
    };
    for _ in 0..100 {
        if service.active_count() > 0 {
            break;
        }
        tokio::time::sleep(Duration::from_millis(5)).await;
    }
    assert!(service.active_count() > 0, "check job never became active");
    fs::write(
        project.root.join("src/lib.rs"),
        "pub fn value() -> usize { 2 }\n",
    )
    .expect("mutate source during check");

    let evidence = running.await.expect("join check job");
    assert_eq!(evidence.status, GateStatus::Stale);
    assert_eq!(evidence.authority, GateAuthority::None);
    service.close().await;
}

#[tokio::test]
async fn progress_reports_preflight_and_running_stages() {
    let project = TestProject::new("progress", "pub fn value() -> usize { 1 }\n", None);
    let service = project.service();
    let events = Arc::new(Mutex::new(Vec::new()));
    let callback = {
        let events = Arc::clone(&events);
        Arc::new(move |event: agz_rust_coder::gate::ProgressEvent| {
            events.lock().expect("progress lock").push(event.stage);
        }) as agz_rust_coder::gate::ProgressCallback
    };

    let evidence = service
        .run(
            GateRequest::new(&project.root, GateTargetId::Check),
            Some(callback),
            None,
        )
        .await;
    assert_eq!(evidence.status, GateStatus::FastPass);
    {
        let events = events.lock().expect("progress lock");
        assert!(events.contains(&agz_rust_coder::gate::ProgressStage::Accepted));
        assert!(events.contains(&agz_rust_coder::gate::ProgressStage::Preflight));
        assert!(events.contains(&agz_rust_coder::gate::ProgressStage::Running));
        assert!(events.contains(&agz_rust_coder::gate::ProgressStage::Completed));
    }
    service.close().await;
}

#[tokio::test]
async fn cancellation_detaches_the_last_subscriber_and_cleans_the_job() {
    let project = TestProject::new(
        "cancel",
        "pub fn value() -> usize { 1 }\n",
        Some("fn main() { std::thread::sleep(std::time::Duration::from_secs(5)); }\n"),
    );
    let service = project.service();
    let cancellation = tokio_util::sync::CancellationToken::new();
    let running = {
        let service = Arc::clone(&service);
        let root = project.root.clone();
        let cancellation = cancellation.clone();
        tokio::spawn(async move {
            service
                .run(
                    GateRequest::new(root, GateTargetId::Check),
                    None,
                    Some(cancellation),
                )
                .await
        })
    };
    for _ in 0..200 {
        if service.active_count() > 0 {
            break;
        }
        tokio::time::sleep(Duration::from_millis(5)).await;
    }
    assert!(service.active_count() > 0, "check job never became active");
    cancellation.cancel();
    let evidence = running.await.expect("join cancelled check");
    assert_eq!(evidence.status, GateStatus::Cancelled);
    for _ in 0..200 {
        if service.active_count() == 0 {
            break;
        }
        tokio::time::sleep(Duration::from_millis(5)).await;
    }
    assert_eq!(service.active_count(), 0);
    service.close().await;
}

#[tokio::test]
async fn different_root_epochs_do_not_join_an_active_job() {
    let project = TestProject::new(
        "root-epoch",
        "pub fn value() -> usize { 1 }\n",
        Some("fn main() { std::thread::sleep(std::time::Duration::from_millis(500)); }\n"),
    );
    let service = project.service();
    let first = {
        let service = Arc::clone(&service);
        let root = project.root.clone();
        tokio::spawn(async move {
            service
                .run(
                    GateRequest::new(root, GateTargetId::Check).with_root_epoch(1),
                    None,
                    None,
                )
                .await
        })
    };
    for _ in 0..200 {
        if service.active_count() > 0 {
            break;
        }
        tokio::time::sleep(Duration::from_millis(5)).await;
    }
    assert!(service.active_count() > 0, "check job never became active");
    let second = {
        let service = Arc::clone(&service);
        let root = project.root.clone();
        tokio::spawn(async move {
            service
                .run(
                    GateRequest::new(root, GateTargetId::Check).with_root_epoch(2),
                    None,
                    None,
                )
                .await
        })
    };
    let first = first.await.expect("join first epoch check");
    let second = second.await.expect("join second epoch check");
    assert_eq!(first.status, GateStatus::FastPass, "{first:#?}");
    assert_eq!(second.status, GateStatus::FastPass, "{second:#?}");
    assert_ne!(first.job_id, second.job_id);
    service.close().await;
}

#[tokio::test]
async fn a_new_input_supersedes_the_older_active_job() {
    let project = TestProject::new(
        "supersede",
        "pub fn value() -> usize { 1 }\n",
        Some("fn main() { std::thread::sleep(std::time::Duration::from_millis(500)); }\n"),
    );
    let service = project.service();
    let first = {
        let service = Arc::clone(&service);
        let root = project.root.clone();
        tokio::spawn(async move {
            service
                .run(GateRequest::new(root, GateTargetId::Check), None, None)
                .await
        })
    };
    for _ in 0..200 {
        if service.active_count() > 0 {
            break;
        }
        tokio::time::sleep(Duration::from_millis(5)).await;
    }
    fs::write(
        project.root.join("src/lib.rs"),
        "pub fn value() -> usize { 2 }\n",
    )
    .expect("write new source generation");
    let second = service
        .run(
            GateRequest::new(&project.root, GateTargetId::Check),
            None,
            None,
        )
        .await;
    let first = first.await.expect("join superseded check");
    assert_eq!(first.status, GateStatus::Superseded, "{first:#?}");
    assert_eq!(second.status, GateStatus::FastPass, "{second:#?}");
    service.close().await;
}
