//! Real Cargo fixtures for the `explain` tool: nested declarative macro
//! provenance, missing trait bounds, feature-gated cfg, bounds, and binding.

use std::{
    fs,
    path::{Path, PathBuf},
    process::Command,
    sync::Arc,
    time::{SystemTime, UNIX_EPOCH},
};

use agz_rust_coder::{
    Config,
    config::GateScope as ConfigGateScope,
    gate::{GateDiagnostic, GateRequest, GateStatus, GateTargetId},
    tools::{
        CheckService,
        explain::{self, ExplainProvenance, MAX_DIAGNOSTICS, feature_selection},
    },
    workspace::{ClientRoots, MetadataService, RootGuard, select_workspace},
};

const SOURCE: &str = r#"macro_rules! inner {
    () => {
        let _: i32 = "macro text";
    };
}
macro_rules! outer {
    () => {
        inner!()
    };
}

pub struct NoDebug;

pub fn outer_caller() {
    outer!();
}

pub fn wants_debug<T: std::fmt::Debug>(_: T) {}

pub fn missing_bound() {
    wants_debug(NoDebug);
}

pub fn mismatched() {
    let _: i32 = "text";
}

trait Unrelated {}
struct Holder;
impl Unrelated for Holder where Holder: Send {}

#[cfg(feature = "extra")]
pub fn feature_gated() {}
"#;

struct TestProject {
    root: PathBuf,
    state: PathBuf,
}

impl TestProject {
    fn new(label: &str) -> Self {
        Self::from_files(
            label,
            &[
                (
                    "Cargo.toml",
                    "[package]\nname = \"explain-fixture\"\nversion = \"0.1.0\"\nedition = \"2024\"\n\n[features]\nextra = []\n\n[workspace]\n",
                ),
                (
                    "Cargo.lock",
                    "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"explain-fixture\"\nversion = \"0.1.0\"\n",
                ),
                ("src/lib.rs", SOURCE),
            ],
        )
    }

    fn from_files(label: &str, files: &[(&str, &str)]) -> Self {
        let stamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map_or(0, |duration| duration.as_nanos());
        let base = fs::canonicalize(std::env::temp_dir())
            .expect("canonical temp directory")
            .join(format!(
                "agz-rust-coder-explain-{label}-{}-{stamp}",
                std::process::id()
            ));
        let root = base.join("workspace");
        let state = base.join("state");
        fs::create_dir_all(&root).expect("create workspace directory");
        fs::create_dir_all(&state).expect("create state directory");
        for (relative, contents) in files {
            let path = root.join(relative);
            if let Some(parent) = path.parent() {
                fs::create_dir_all(parent).expect("create fixture parent directory");
            }
            fs::write(&path, contents).expect("write fixture file");
        }
        git(&root, &["init", "--quiet"]);
        git(&root, &["config", "user.email", "explain@example.invalid"]);
        git(&root, &["config", "user.name", "Explain Fixture"]);
        git(&root, &["add", "."]);
        git(&root, &["commit", "--quiet", "-m", "fixture"]);
        Self { root, state }
    }

    fn root(&self) -> &Path {
        &self.root
    }

    fn service(&self) -> Arc<CheckService> {
        let mut config = Config::defaults_at(&self.root);
        config.gate.debounce_ms = 10;
        config.gate.hard_timeout_ms = 120_000;
        config.gate.cache_dir = self.state.join("cache");
        config.gate.lease_dir = self.state.join("leases");
        config.gate.scope = ConfigGateScope::Workspace;
        config.telemetry.enabled = false;
        config.telemetry.path = self.state.join("activity.jsonl");
        let guard = Arc::new(
            RootGuard::new([self.root.clone()], std::iter::empty()).expect("create root guard"),
        );
        Arc::new(CheckService::new(config, guard))
    }

    fn metadata_load(&self) -> agz_rust_coder::workspace::MetadataLoad {
        let guard =
            Arc::new(RootGuard::new([self.root.clone()], std::iter::empty()).expect("root guard"));
        let snapshot = guard
            .snapshot(ClientRoots::unsupported())
            .expect("root snapshot");
        let selection =
            select_workspace(&snapshot, Some(self.root())).expect("workspace selection");
        let metadata = MetadataService::new(guard);
        let cargo = std::env::var_os("CARGO")
            .map(PathBuf::from)
            .unwrap_or_else(|| PathBuf::from("cargo"));
        metadata
            .acquire(&selection, cargo)
            .expect("cargo metadata for fixture")
    }
}

impl Drop for TestProject {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(self.root.parent().unwrap_or(&self.root));
    }
}

fn git(root: &Path, args: &[&str]) {
    let status = Command::new("git")
        .args(args)
        .current_dir(root)
        .status()
        .expect("run git");
    assert!(status.success(), "git {args:?} failed");
}

fn multi_crate_project(label: &str) -> TestProject {
    TestProject::from_files(
        label,
        &[
            (
                "Cargo.toml",
                "[workspace]\nmembers = [\"app\", \"dep\"]\nresolver = \"3\"\n",
            ),
            (
                "Cargo.lock",
                "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"explain-app\"\nversion = \"0.1.0\"\ndependencies = [\n \"explain-dep\",\n]\n\n[[package]]\nname = \"explain-dep\"\nversion = \"0.1.0\"\n",
            ),
            (
                "dep/Cargo.toml",
                "[package]\nname = \"explain-dep\"\nversion = \"0.1.0\"\nedition = \"2024\"\n\n[features]\ndep-only = []\n",
            ),
            ("dep/src/lib.rs", "pub fn dep() {}\n"),
            (
                "app/Cargo.toml",
                "[package]\nname = \"explain-app\"\nversion = \"0.1.0\"\nedition = \"2024\"\n\n[features]\napp-extra = []\n\n[dependencies]\nexplain-dep = { path = \"../dep\", features = [\"dep-only\"] }\n",
            ),
            (
                "app/src/lib.rs",
                "#[cfg(feature = \"dep-only\")]\npub fn gated_by_dependency() {}\n",
            ),
        ],
    )
}

fn proc_macro_project(label: &str) -> TestProject {
    TestProject::from_files(
        label,
        &[
            (
                "Cargo.toml",
                "[workspace]\nmembers = [\"mac\", \"app\"]\nresolver = \"3\"\n",
            ),
            (
                "Cargo.lock",
                "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"explain-pm-app\"\nversion = \"0.1.0\"\ndependencies = [\n \"explain-pm-mac\",\n]\n\n[[package]]\nname = \"explain-pm-mac\"\nversion = \"0.1.0\"\n",
            ),
            (
                "mac/Cargo.toml",
                "[package]\nname = \"explain-pm-mac\"\nversion = \"0.1.0\"\nedition = \"2024\"\n\n[lib]\nproc-macro = true\n",
            ),
            (
                "mac/src/lib.rs",
                r#"use proc_macro::TokenStream;

#[proc_macro_derive(ExplainGuard)]
pub fn explain_guard(_input: TokenStream) -> TokenStream {
    "compile_error!(\"proc-macro expansion rejected\");"
        .parse()
        .expect("token stream")
}
"#,
            ),
            (
                "app/Cargo.toml",
                "[package]\nname = \"explain-pm-app\"\nversion = \"0.1.0\"\nedition = \"2024\"\n\n[dependencies]\nexplain-pm-mac = { path = \"../mac\" }\n",
            ),
            (
                "app/src/lib.rs",
                "use explain_pm_mac::ExplainGuard;\n\npub struct NotClone;\n\n#[derive(Clone)]\npub struct Wrapper {\n    pub field: NotClone,\n}\n\n#[derive(ExplainGuard)]\npub struct Widget;\n",
            ),
        ],
    )
}

#[tokio::test]
async fn cargo_fixture_keeps_macro_expansion_and_trait_evidence() {
    let project = TestProject::new("cargo");
    let evidence = project
        .service()
        .run(
            GateRequest::new(project.root(), GateTargetId::Check),
            None,
            None,
        )
        .await;
    assert_eq!(evidence.status, GateStatus::Fail, "{evidence:#?}");
    let diagnostics = evidence
        .steps
        .iter()
        .flat_map(|step| step.diagnostics.iter().cloned())
        .collect::<Vec<GateDiagnostic>>();
    assert!(!diagnostics.is_empty());

    // Nested declarative macro: rustc expansion provenance survives the gate
    // conversion and is presented as observed compiler evidence.
    let macro_diagnostics =
        explain::select_diagnostics(&diagnostics, "src/lib.rs", None, Some("E0308"));
    let view = explain::macro_compiler_view(&macro_diagnostics);
    let expansion = view
        .fragments
        .iter()
        .find(|fragment| {
            fragment.kind == "macroExpansion"
                && fragment.provenance == ExplainProvenance::ObservedCompiler
        })
        .expect("rustc expansion provenance");
    assert!(expansion.detail.contains("inner"), "{}", expansion.detail);
    assert!(view.macro_depth >= 1);

    // Missing trait bound with a related impl/where clause from bounded source.
    let source = fs::read_to_string(project.root().join("src/lib.rs")).expect("read source");
    let hint = explain::trait_hint(&macro_diagnostics).or_else(|| {
        let all = explain::select_diagnostics(&diagnostics, "lib.rs", None, None);
        explain::trait_hint(&all)
    });
    assert_eq!(hint.as_deref(), Some("Debug"), "{hint:?}");
    let trait_source = explain::select_diagnostics(&diagnostics, "lib.rs", None, None);
    let view = explain::trait_compiler_view(
        &trait_source,
        "src/lib.rs",
        1,
        Some(&source),
        hint.as_deref(),
    );
    assert!(view.fragments.iter().any(|fragment| {
        fragment.kind == "failedBound" && fragment.provenance == ExplainProvenance::ObservedCompiler
    }));
    assert!(
        view.fragments.iter().any(|fragment| {
            fragment.kind == "expectedFound" && fragment.detail.contains("i32")
        })
    );
    assert!(view.fragments.iter().any(|fragment| {
        matches!(fragment.kind.as_str(), "candidateImpl" | "whereClause")
            && fragment.provenance == ExplainProvenance::Inferred
            && fragment.source.is_some()
    }));
}

#[tokio::test]
async fn cfg_enablement_uses_recorded_cargo_features() {
    let project = TestProject::new("cfg");
    let load = project.metadata_load();
    let anchor = explain::anchor_feature_maps(
        &load.snapshot.metadata,
        project.root(),
        Path::new("src/lib.rs"),
    );
    assert_eq!(anchor.package.as_deref(), Some("explain-fixture"));
    assert!(anchor.declared.contains_key("extra"));
    assert!(!anchor.recorded.contains("extra"));
    let declared = anchor.declared.clone();
    let recorded = anchor.recorded.clone();

    let source = "#[cfg(feature = \"extra\")]\npub fn feature_gated() {}\n";
    let features = feature_selection(recorded.clone(), &declared, &[], false, false);
    let view = explain::cfg_view("src/lib.rs", 2, source, &features, None);
    assert!(view.fragments.iter().any(|fragment| {
        fragment.kind == "cfgCondition"
            && fragment.provenance == ExplainProvenance::Inferred
            && fragment.detail.contains("disables")
    }));

    // Requested features are an inference over the declared map, never a
    // verified compile result.
    let requested = feature_selection(recorded, &declared, &["extra".to_owned()], false, false);
    let view = explain::cfg_view("src/lib.rs", 2, source, &requested, None);
    assert!(view.fragments.iter().any(|fragment| {
        fragment.kind == "cfgCondition"
            && fragment.provenance == ExplainProvenance::Inferred
            && fragment.detail.contains("enables")
    }));
    assert!(
        features.note.contains("not compiler-verified")
            || features
                .note
                .contains("target/compiler predicates stay unknown")
    );
}

#[tokio::test]
async fn feature_evidence_is_scoped_to_the_anchor_package() {
    let project = multi_crate_project("multi-crate");
    let load = project.metadata_load();
    let app = explain::anchor_feature_maps(
        &load.snapshot.metadata,
        project.root(),
        Path::new("app/src/lib.rs"),
    );
    assert_eq!(app.package.as_deref(), Some("explain-app"));
    assert!(app.declared.contains_key("app-extra"));
    assert!(!app.declared.contains_key("dep-only"));
    assert!(!app.recorded.contains("dep-only"), "{:?}", app.recorded);

    // A feature activated only for the dependency must not enable the cfg in
    // the workspace member that owns the anchor.
    let source = "#[cfg(feature = \"dep-only\")]\npub fn gated_by_dependency() {}\n";
    let features = feature_selection(app.recorded.clone(), &app.declared, &[], false, false);
    let view = explain::cfg_view("app/src/lib.rs", 2, source, &features, None);
    assert!(view.fragments.iter().any(|fragment| {
        fragment.kind == "cfgCondition"
            && fragment.provenance == ExplainProvenance::Inferred
            && fragment.detail.contains("disables")
    }));

    // Requesting a dependency-only feature for the app package is not a
    // declared feature there, so enablement stays unknown instead of enabled.
    let features = feature_selection(
        app.recorded.clone(),
        &app.declared,
        &["dep-only".to_owned()],
        false,
        false,
    );
    let view = explain::cfg_view("app/src/lib.rs", 2, source, &features, None);
    assert!(view.fragments.iter().any(|fragment| {
        fragment.kind == "cfgCondition"
            && fragment.provenance == ExplainProvenance::Unknown
            && fragment.detail.contains("dep-only")
    }));

    // The dependency crate itself is compiled with its activated feature.
    let dep = explain::anchor_feature_maps(
        &load.snapshot.metadata,
        project.root(),
        Path::new("dep/src/lib.rs"),
    );
    assert_eq!(dep.package.as_deref(), Some("explain-dep"));
    assert!(dep.declared.contains_key("dep-only"));
    assert!(dep.recorded.contains("dep-only"), "{:?}", dep.recorded);
    let features = feature_selection(dep.recorded.clone(), &dep.declared, &[], false, false);
    let view = explain::cfg_view("dep/src/lib.rs", 2, source, &features, None);
    assert!(view.fragments.iter().any(|fragment| {
        fragment.kind == "cfgCondition"
            && fragment.provenance == ExplainProvenance::Inferred
            && fragment.detail.contains("enables")
    }));
}

#[tokio::test]
async fn derive_and_proc_macro_fixture_keeps_expansion_provenance() {
    let project = proc_macro_project("proc-macro");
    let evidence = project
        .service()
        .run(
            GateRequest::new(project.root(), GateTargetId::Check),
            None,
            None,
        )
        .await;
    assert_eq!(evidence.status, GateStatus::Fail, "{evidence:#?}");
    let diagnostics = evidence
        .steps
        .iter()
        .flat_map(|step| step.diagnostics.iter().cloned())
        .collect::<Vec<GateDiagnostic>>();
    let selected = explain::select_diagnostics(&diagnostics, "app/src/lib.rs", None, None);
    let view = explain::macro_compiler_view(&selected);
    let details = view
        .fragments
        .iter()
        .filter(|fragment| {
            fragment.kind == "macroExpansion"
                && fragment.provenance == ExplainProvenance::ObservedCompiler
        })
        .map(|fragment| fragment.detail.as_str())
        .collect::<Vec<_>>();

    // Built-in derives and custom proc-macro derives both surface through the
    // compiler's retained expansion provenance.
    assert!(
        details
            .iter()
            .any(|detail| detail.contains("derive(Clone)")),
        "{details:?}"
    );
    assert!(
        details.iter().any(|detail| detail.contains("ExplainGuard")),
        "{details:?}"
    );
    assert!(view.macro_depth >= 1);

    // Trait explanations keep the same compiler-retained expansion depth.
    let trait_diagnostics =
        explain::select_diagnostics(&diagnostics, "app/src/lib.rs", None, Some("E0277"));
    let trait_view =
        explain::trait_compiler_view(&trait_diagnostics, "app/src/lib.rs", 5, None, Some("Clone"));
    assert!(trait_view.macro_depth >= 1, "{trait_view:#?}");
}

#[test]
fn source_hash_binds_explanations_and_bounds_are_enforced() {
    let first = explain::source_sha256(b"pub fn a() {}\n");
    let second = explain::source_sha256(b"pub fn b() {}\n");
    assert_eq!(first.len(), 64);
    assert_eq!(first, explain::source_sha256(b"pub fn a() {}\n"));
    assert_ne!(first, second);

    let diagnostics = (0..MAX_DIAGNOSTICS + 4)
        .map(|index| diagnostic(index as u64))
        .collect::<Vec<_>>();
    let references = diagnostics.iter().collect::<Vec<_>>();
    let view = explain::macro_compiler_view(&references);
    assert_eq!(view.shown, MAX_DIAGNOSTICS);
    assert!(view.truncated);
}

#[test]
fn compiler_authority_stays_visible_in_advisory_conflicts() {
    let conflicts = explain::obligation_conflicts(true, &Default::default(), None);
    assert_eq!(conflicts.len(), 1);
    assert!(conflicts[0].compiler.contains("authoritative"));
    assert!(conflicts[0].analyzer.contains("no failed obligations"));
}

fn diagnostic(index: u64) -> GateDiagnostic {
    GateDiagnostic {
        code: Some("E0308".to_owned()),
        level: "error".to_owned(),
        file: Some("src/lib.rs".to_owned()),
        line: Some(index),
        message: "mismatched types".to_owned(),
        rendered: None,
        spans: vec![agz_rust_coder::gate::DiagnosticSpan {
            file: "src/lib.rs".to_owned(),
            byte_start: None,
            byte_end: None,
            line_start: index,
            line_end: index,
            column_start: 1,
            column_end: 2,
            is_primary: true,
            label: None,
            suggested_replacement: None,
            suggestion_applicability: None,
            expansion: None,
        }],
        children: Vec::new(),
        suggestions: Vec::new(),
    }
}
