//! End-to-end tests for `profile(action=runtime_compare)`.
//!
//! Each fixture builds a temporary Cargo project in server-owned scratch and
//! drives create/stage plus runtime comparison. The original workspace bytes
//! are never measured or written.

use std::{
    fs,
    path::{Path, PathBuf},
    sync::Arc,
    time::{Duration, Instant, SystemTime, UNIX_EPOCH},
};

use agz_rust_coder::{
    Config,
    change::{ChangeAction, ChangeOutcome, ChangeRequest, ChangeService, PatchInput},
    config::{RuntimeAdapterConfig, RuntimeMetric, RuntimeWorkloadConfig},
    gate::{GateDetail, GateTargetId, ValidationOptions},
    process::ProcessSupervisor,
    tools::{ProfileBudget, RuntimeCompareRequest, RuntimeCompareService},
    workspace::{ClientRoots, RootGuard, WorkspaceRoot},
};
use sha2::{Digest, Sha256};
use tokio_util::sync::CancellationToken;

struct Fixture {
    root: PathBuf,
    config: Config,
    guard: Arc<RootGuard>,
    change: Arc<ChangeService>,
    runtime: RuntimeCompareService,
}

impl Fixture {
    fn new(label: &str, source: &[u8], adapters: Vec<RuntimeAdapterConfig>) -> Self {
        Self::with_setup(label, source, adapters, |_| {})
    }

    fn with_setup(
        label: &str,
        source: &[u8],
        adapters: Vec<RuntimeAdapterConfig>,
        setup: impl FnOnce(&Path),
    ) -> Self {
        let stamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map_or(0, |duration| duration.as_nanos());
        let base = fs::canonicalize(std::env::temp_dir())
            .expect("canonical temp directory")
            .join(format!(
                "agz-runtime-{label}-{}-{stamp}",
                std::process::id()
            ));
        let root = base.join("workspace");
        let state = base.join("state");
        fs::create_dir_all(root.join("src")).expect("create source directory");
        fs::create_dir_all(&state).expect("create state directory");
        fs::write(
            root.join("Cargo.toml"),
            "[package]\nname = \"runtime-fixture\"\nversion = \"0.1.0\"\nedition = \"2024\"\n\n[workspace]\n",
        )
        .expect("write manifest");
        fs::write(
            root.join("Cargo.lock"),
            "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"runtime-fixture\"\nversion = \"0.1.0\"\n",
        )
        .expect("write lockfile");
        fs::write(root.join("src/lib.rs"), source).expect("write source");
        setup(&base);
        let mut config = Config::defaults_at(&root);
        config.gate.debounce_ms = 10;
        config.gate.hard_timeout_ms = 120_000;
        config.gate.cache_dir = state.join("gate-cache");
        config.gate.lease_dir = state.join("leases");
        config.change.scratch_dir = state.join("change");
        config.profile.runtime_adapters = adapters;
        config.telemetry.enabled = false;
        config.telemetry.path = state.join("activity.jsonl");
        let guard = Arc::new(
            RootGuard::new([root.clone()], config.server.allow_dependency_roots.clone())
                .expect("create root guard"),
        );
        let change = Arc::new(
            ChangeService::new(
                config.clone(),
                Arc::clone(&guard),
                ProcessSupervisor::without_journal(),
            )
            .expect("create change service"),
        );
        let runtime =
            RuntimeCompareService::new(config.clone(), ProcessSupervisor::without_journal());
        Self {
            root,
            config,
            guard,
            change,
            runtime,
        }
    }

    fn workspace(&self) -> WorkspaceRoot {
        self.guard
            .snapshot(ClientRoots::unsupported())
            .expect("root snapshot")
            .select(Some(&self.root))
            .expect("select workspace")
    }

    async fn execute(&self, request: ChangeRequest) -> ChangeOutcome {
        self.change
            .execute(request, &self.workspace(), CancellationToken::new(), None)
            .await
    }

    fn candidate(&self, id: &str) -> PathBuf {
        self.config.change.scratch_dir.join(id).join("candidate")
    }

    async fn create_and_stage(
        &self,
        old: &str,
        new: &str,
    ) -> (String, String, PathBuf, WorkspaceRoot) {
        let created = self.execute(create_request()).await;
        assert_eq!(created.status, "CREATED", "{}", created.data.reason);
        let id = created.data.change_id.clone().expect("change id");
        let base = created.data.base_identity.clone().expect("base identity");
        let staged = self
            .execute(stage_request(
                &id,
                0,
                &base,
                vec![patch("src/lib.rs", old, new)],
            ))
            .await;
        assert_eq!(staged.status, "STAGED", "{}", staged.data.reason);
        let workspace = self.workspace();
        let candidate = self.candidate(&id);
        (id, base, candidate, workspace)
    }
}

impl Drop for Fixture {
    fn drop(&mut self) {
        if let Some(base) = self.root.parent() {
            let _ = fs::remove_dir_all(base);
        }
    }
}

fn runtime_request(id: &str, revision: u64, workspace: &WorkspaceRoot) -> RuntimeCompareRequest {
    RuntimeCompareRequest {
        change_id: id.to_owned(),
        baseline_revision: 0,
        candidate_revision: revision,
        adapter: "sleepy".to_owned(),
        workload: "tiny".to_owned(),
        hypothesis: "the staged change removes redundant work".to_owned(),
        threshold_percent: 10.0,
        samples: Some(3),
        warmup: Some(1),
        gate_target: GateTargetId::Check,
        gate_options: ValidationOptions::default(),
        budget: ProfileBudget {
            max_runs: 4,
            max_report_bytes: 4 * 1024 * 1024,
            wall_time_ms: 120_000,
        },
        root_epoch: workspace.epoch(),
        workspace_root: workspace.authority_path().to_owned(),
    }
}

fn sleep_adapter() -> RuntimeAdapterConfig {
    RuntimeAdapterConfig {
        name: "sleepy".to_owned(),
        command: PathBuf::from("/bin/sleep"),
        args: Vec::new(),
        prepare_args: Vec::new(),
        workloads: vec![RuntimeWorkloadConfig {
            name: "tiny".to_owned(),
            args: vec!["0.05".to_owned()],
        }],
        metric: RuntimeMetric::Duration,
    }
}

fn missing_adapter() -> RuntimeAdapterConfig {
    RuntimeAdapterConfig {
        name: "broken".to_owned(),
        command: PathBuf::from("/nonexistent/agz-runtime-adapter"),
        args: Vec::new(),
        prepare_args: Vec::new(),
        workloads: vec![RuntimeWorkloadConfig {
            name: "tiny".to_owned(),
            args: Vec::new(),
        }],
        metric: RuntimeMetric::Duration,
    }
}

fn create_request() -> ChangeRequest {
    ChangeRequest {
        action: ChangeAction::Create,
        change_id: None,
        expected_revision: None,
        base_identity: None,
        patches: Vec::new(),
        new_files: Vec::new(),
        migration: None,
        target: GateTargetId::Check,
        options: ValidationOptions::default(),
        detail: GateDetail::Compact,
        timings: false,
    }
}

fn stage_request(id: &str, revision: u64, base: &str, patches: Vec<PatchInput>) -> ChangeRequest {
    ChangeRequest {
        action: ChangeAction::Stage,
        change_id: Some(id.to_owned()),
        expected_revision: Some(revision),
        base_identity: Some(base.to_owned()),
        patches,
        new_files: Vec::new(),
        migration: None,
        target: GateTargetId::Check,
        options: ValidationOptions::default(),
        detail: GateDetail::Compact,
        timings: false,
    }
}

fn patch(file: &str, old: &str, new: &str) -> PatchInput {
    PatchInput {
        file: file.to_owned(),
        old_string: old.to_owned(),
        new_string: new.to_owned(),
    }
}

fn digest(path: &Path) -> String {
    let bytes = fs::read(path).expect("read digest target");
    let mut hasher = Sha256::new();
    hasher.update(&bytes);
    format!("{:x}", hasher.finalize())
}

const PASSING_SOURCE: &[u8] = b"pub const N: u8 = 1;\n\npub fn value() -> u8 {\n    N\n}\n\n#[cfg(test)]\nmod tests {\n    #[test]\n    fn value_is_positive() {\n        assert!(super::value() >= 1);\n    }\n}\n";

const FAILING_SOURCE: &[u8] = b"pub const N: u8 = 1;\n\npub fn value() -> u8 {\n    N\n}\n\n#[cfg(test)]\nmod tests {\n    #[test]\n    fn value_is_positive() {\n        assert_eq!(super::value(), 1);\n    }\n}\n";

#[cfg(unix)]
#[tokio::test]
async fn runtime_compare_measures_balanced_samples_and_binds_evidence() {
    let fixture = Fixture::new("happy", PASSING_SOURCE, vec![sleep_adapter()]);
    let (id, _base, candidate, workspace) = fixture
        .create_and_stage("pub const N: u8 = 1;", "pub const N: u8 = 2;")
        .await;
    let candidate_before = digest(&candidate.join("src/lib.rs"));

    let comparison = fixture
        .runtime
        .compare(
            &runtime_request(&id, 1, &workspace),
            &fixture.change,
            std::time::Instant::now(),
            &CancellationToken::new(),
        )
        .await;

    assert_eq!(comparison.status, "COMPARABLE", "{}", comparison.reason);
    assert_eq!(
        comparison.verdict.as_deref(),
        Some("NO_MATERIAL_DIFFERENCE")
    );
    let binding = comparison.binding.as_ref().expect("binding");
    assert_ne!(
        binding.baseline_source_digest,
        binding.candidate_source_digest
    );
    assert!(!binding.adapter_digest.is_empty());
    assert_eq!(binding.candidate_revision, 1);
    let gates = comparison.correctness_gate.as_ref().expect("gates");
    assert!(gates.baseline.passed && gates.candidate.passed);
    let experiment = &comparison.experiment;
    assert!(!experiment.command.is_empty());
    assert_eq!(experiment.samples_per_side, 3);
    assert_eq!(experiment.warmup_per_side, 1);
    assert!(experiment.threshold_declared_before_measurement);
    let measurements = comparison.measurements.as_ref().expect("measurements");
    assert!(measurements.raw_samples.len() >= 4);
    assert!(
        measurements
            .raw_samples
            .iter()
            .any(|sample| sample.phase == "warmup")
    );
    assert!(
        measurements
            .raw_samples
            .iter()
            .all(|sample| sample.stdout_sha256.len() == 64)
    );
    // Balanced order: the first pair runs baseline first, the second candidate
    // first, and every sample carries its global sequence.
    assert_eq!(measurements.raw_samples[0].side, "baseline");
    assert_eq!(measurements.raw_samples[0].order, "baseline-candidate");
    assert_eq!(measurements.raw_samples[2].side, "candidate");
    assert_eq!(measurements.raw_samples[2].order, "candidate-baseline");
    assert_eq!(measurements.baseline.samples, 3);
    assert_eq!(measurements.candidate.samples, 3);
    assert!(!comparison.measured_findings.is_empty());
    assert_eq!(
        comparison.interpretation.hypothesis,
        "the staged change removes redundant work"
    );
    assert!(comparison.candidate_exportable);
    assert!(
        comparison
            .measured_findings
            .iter()
            .any(|finding| finding.contains("threshold")),
        "threshold predeclaration must be visible in the findings"
    );
    assert_eq!(
        digest(&candidate.join("src/lib.rs")),
        candidate_before,
        "the candidate snapshot must not be mutated by the experiment"
    );
    // The original workspace itself was never staged or measured.
    assert_eq!(
        fs::read(fixture.root.join("src/lib.rs")).expect("original source"),
        PASSING_SOURCE
    );
}

#[tokio::test]
async fn fast_but_wrong_candidate_is_rejected_before_measurement() {
    let fixture = Fixture::new("rejected", FAILING_SOURCE, vec![sleep_adapter()]);
    let (id, _base, _candidate, workspace) = fixture
        .create_and_stage("pub const N: u8 = 1;", "pub const N: u8 = 2;")
        .await;
    let mut request = runtime_request(&id, 1, &workspace);
    request.gate_target = GateTargetId::Test;

    let comparison = fixture
        .runtime
        .compare(
            &request,
            &fixture.change,
            std::time::Instant::now(),
            &CancellationToken::new(),
        )
        .await;

    assert_eq!(comparison.status, "REJECTED", "{}", comparison.reason);
    let gates = comparison.correctness_gate.as_ref().expect("gates");
    assert!(gates.baseline.passed);
    assert!(!gates.candidate.passed);
    assert!(
        comparison.measurements.is_none(),
        "a rejected candidate must not be measured"
    );
    assert!(!comparison.candidate_exportable);
}

#[tokio::test]
async fn tampered_candidate_bytes_are_incomparable() {
    let fixture = Fixture::new("tamper", PASSING_SOURCE, vec![sleep_adapter()]);
    let (id, _base, candidate, workspace) = fixture
        .create_and_stage("pub const N: u8 = 1;", "pub const N: u8 = 2;")
        .await;
    fs::write(
        candidate.join("src/lib.rs"),
        b"pub const N: u8 = 3;\n\npub fn value() -> u8 {\n    N\n}\n",
    )
    .expect("tamper candidate");

    let comparison = fixture
        .runtime
        .compare(
            &runtime_request(&id, 1, &workspace),
            &fixture.change,
            std::time::Instant::now(),
            &CancellationToken::new(),
        )
        .await;

    assert_eq!(comparison.status, "INCOMPARABLE", "{}", comparison.reason);
    assert!(
        comparison
            .reason
            .contains("does not match the recorded revision"),
        "unexpected reason: {}",
        comparison.reason
    );
    assert!(comparison.measurements.is_none());
    assert!(comparison.correctness_gate.is_none());
}

#[tokio::test]
async fn failed_and_insufficient_samples_stay_inconclusive() {
    let fixture = Fixture::with_setup(
        "broken-adapter",
        PASSING_SOURCE,
        vec![missing_adapter()],
        |_| {},
    );
    let (id, _base, _candidate, workspace) = fixture
        .create_and_stage("pub const N: u8 = 1;", "pub const N: u8 = 2;")
        .await;
    let mut request = runtime_request(&id, 1, &workspace);
    request.adapter = "broken".to_owned();
    request.samples = Some(2);
    request.warmup = Some(0);

    let comparison = fixture
        .runtime
        .compare(
            &request,
            &fixture.change,
            std::time::Instant::now(),
            &CancellationToken::new(),
        )
        .await;

    assert_eq!(comparison.status, "INCONCLUSIVE", "{}", comparison.reason);
    assert!(comparison.reason.contains("insufficient clean samples"));
    let measurements = comparison.measurements.as_ref().expect("raw evidence");
    assert!(
        measurements
            .raw_samples
            .iter()
            .all(|sample| sample.spawn_error.is_some())
    );
    assert!(!comparison.candidate_exportable);
}

#[tokio::test]
async fn unknown_adapter_missing_change_and_cancellation_fail_closed() {
    let fixture = Fixture::new("fail-closed", PASSING_SOURCE, vec![sleep_adapter()]);
    let workspace = fixture.workspace();

    let mut unknown = runtime_request("ch-unknown", 1, &workspace);
    unknown.adapter = "not-configured".to_owned();
    let comparison = fixture
        .runtime
        .compare(
            &unknown,
            &fixture.change,
            std::time::Instant::now(),
            &CancellationToken::new(),
        )
        .await;
    assert_eq!(comparison.status, "INCONCLUSIVE");
    assert!(
        comparison
            .reason
            .contains("no operator-authorized runtime adapter")
    );

    let missing = runtime_request("ch-00000000", 1, &workspace);
    let comparison = fixture
        .runtime
        .compare(
            &missing,
            &fixture.change,
            std::time::Instant::now(),
            &CancellationToken::new(),
        )
        .await;
    assert_eq!(comparison.status, "INCOMPARABLE");

    let cancelled = CancellationToken::new();
    cancelled.cancel();
    let comparison = fixture
        .runtime
        .compare(
            &runtime_request("ch-00000000", 1, &workspace),
            &fixture.change,
            std::time::Instant::now(),
            &cancelled,
        )
        .await;
    assert_eq!(comparison.status, "CANCELLED");
}

#[tokio::test]
async fn an_exhausted_wall_budget_is_terminal_before_scratch_is_created() {
    let fixture = Fixture::new("budget", PASSING_SOURCE, vec![sleep_adapter()]);
    let workspace = fixture.workspace();
    let mut request = runtime_request("ch-00000000", 1, &workspace);
    request.budget.wall_time_ms = 1;

    let comparison = fixture
        .runtime
        .compare(
            &request,
            &fixture.change,
            Instant::now()
                .checked_sub(Duration::from_secs(1))
                .expect("past instant"),
            &CancellationToken::new(),
        )
        .await;
    assert_eq!(comparison.status, "BUDGET_EXHAUSTED");
    assert!(comparison.measurements.is_none());
}

#[test]
fn effective_budget_clamps_caller_values_to_server_config() {
    let config = Config::defaults_at("/workspace");
    let service = RuntimeCompareService::new(config.clone(), ProcessSupervisor::without_journal());
    let effective = service.effective_budget(&ProfileBudget {
        max_runs: 999,
        max_report_bytes: u64::MAX,
        wall_time_ms: u64::MAX,
    });
    assert_eq!(effective.max_runs, config.profile.max_runs);
    assert_eq!(effective.max_report_bytes, config.profile.max_report_bytes);
    assert_eq!(effective.wall_time_ms, config.gate.hard_timeout_ms);
}
