//! End-to-end tests for `verify(action=test_plan|test_run|test_candidate)`.
//!
//! Each fixture builds a temporary Cargo project. Candidate comparisons run
//! only on server-owned `ChangeService` scratch copies; the assertions also
//! confirm the original workspace bytes never change.

use std::{
    fs,
    path::{Path, PathBuf},
    process::Command,
    sync::Arc,
    time::{SystemTime, UNIX_EPOCH},
};

use agz_rust_coder::{
    Config,
    change::{ChangeAction, ChangeRequest, ChangeService, NewFileInput, PatchInput},
    config::VerifyConfig,
    gate::{GateDetail, GateTargetId, TestRunner, ValidationOptions},
    process::ProcessSupervisor,
    tools::{
        BehaviorContract, CheckService, SemanticReference, TestMapping, TestPatchInput,
        VerifyAction, VerifyBudget, VerifyOutcome, VerifyRequest, VerifyService,
    },
    workspace::{ClientRoots, RootGuard, WorkspaceRoot},
};
use tokio_util::sync::CancellationToken;

const PACKAGE: &str = "verify-tests-fixture";

struct Fixture {
    root: PathBuf,
    state: PathBuf,
    guard: Arc<RootGuard>,
    check: Arc<CheckService>,
    change: Arc<ChangeService>,
}

impl Fixture {
    fn new(label: &str, source: &str, extra_files: &[(&str, &str)]) -> Self {
        let stamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map_or(0, |duration| duration.as_nanos());
        let base = fs::canonicalize(std::env::temp_dir())
            .expect("canonical temp directory")
            .join(format!(
                "agz-rust-coder-verify-tests-{label}-{}-{stamp}",
                std::process::id()
            ));
        let root = base.join("workspace");
        let state = base.join("state");
        fs::create_dir_all(root.join("src")).expect("create project source directory");
        fs::create_dir_all(&state).expect("create state directory");
        fs::write(
            root.join("Cargo.toml"),
            format!(
                "[package]\nname = \"{PACKAGE}\"\nversion = \"0.1.0\"\nedition = \"2024\"\n\n[workspace]\n"
            ),
        )
        .expect("write manifest");
        fs::write(
            root.join("Cargo.lock"),
            format!(
                "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"{PACKAGE}\"\nversion = \"0.1.0\"\n"
            ),
        )
        .expect("write lockfile");
        fs::write(root.join("src/lib.rs"), source).expect("write source");
        for (relative, contents) in extra_files {
            let path = root.join(relative);
            if let Some(parent) = path.parent() {
                fs::create_dir_all(parent).expect("create fixture subdirectory");
            }
            fs::write(path, contents).expect("write fixture file");
        }
        git(&root, &["init", "--quiet"]);
        git(
            &root,
            &["config", "user.email", "verify-tests@example.invalid"],
        );
        git(&root, &["config", "user.name", "Verify Tests Fixture"]);
        git(&root, &["add", "."]);
        git(&root, &["commit", "--quiet", "-m", "fixture"]);

        let mut config = Config::defaults_at(&root);
        config.gate.debounce_ms = 10;
        config.gate.hard_timeout_ms = 120_000;
        config.gate.cache_dir = state.join("gate-cache");
        config.gate.lease_dir = state.join("leases");
        config.change.scratch_dir = state.join("change");
        config.telemetry.enabled = false;
        config.telemetry.path = state.join("activity.jsonl");
        let dependencies = config.server.allow_dependency_roots.clone();
        let guard =
            Arc::new(RootGuard::new([root.clone()], dependencies).expect("create root guard"));
        let check = Arc::new(CheckService::new(config.clone(), Arc::clone(&guard)));
        let change = Arc::new(
            ChangeService::new(
                config,
                Arc::clone(&guard),
                ProcessSupervisor::without_journal(),
            )
            .expect("create change service"),
        );
        Self {
            root,
            state,
            guard,
            check,
            change,
        }
    }

    fn verify(&self) -> Arc<VerifyService> {
        Arc::new(
            VerifyService::new(
                Arc::clone(&self.check),
                VerifyConfig {
                    max_cells: 8,
                    max_wall_ms: 300_000,
                    max_tests: 16,
                    repeats: 2,
                },
            )
            .with_change(Some(Arc::clone(&self.change))),
        )
    }

    fn workspace(&self) -> WorkspaceRoot {
        self.guard
            .snapshot(ClientRoots::unsupported())
            .expect("root snapshot")
            .select(Some(&self.root))
            .expect("select workspace")
    }

    fn scratch_change_dir(&self, id: &str) -> PathBuf {
        self.state.join("change").join(id)
    }
}

impl Drop for Fixture {
    fn drop(&mut self) {
        if let Some(base) = self.root.parent() {
            let _ = fs::remove_dir_all(base);
        }
    }
}

fn git(root: &Path, arguments: &[&str]) {
    let status = Command::new("git")
        .args(arguments)
        .current_dir(root)
        .status()
        .expect("run git fixture command");
    assert!(status.success(), "git command failed: {arguments:?}");
}

fn request(
    fixture: &Fixture,
    action: VerifyAction,
    configuration: ValidationOptions,
) -> VerifyRequest {
    VerifyRequest {
        action,
        directory: Some(fixture.root.clone()),
        client_roots: ClientRoots::unsupported(),
        root_epoch: 0,
        change_id: None,
        required: Default::default(),
        budget: VerifyBudget {
            repeats: Some(1),
            ..VerifyBudget::default()
        },
        test_configuration: configuration,
        test_mappings: Vec::new(),
        changed_paths: Vec::new(),
        semantic_references: Vec::new(),
        test_patch: None,
        behavior_contract: None,
        workspace: Some(fixture.workspace()),
    }
}

async fn execute(service: &VerifyService, request: VerifyRequest) -> VerifyOutcome {
    service
        .execute(request, None, Some(CancellationToken::new()))
        .await
}

fn mapping(test_name: &str) -> TestMapping {
    TestMapping {
        path: None,
        package: None,
        target: None,
        test_name: Some(test_name.to_owned()),
    }
}

async fn create_change(fixture: &Fixture) -> (String, String) {
    let outcome = fixture
        .change
        .execute(
            ChangeRequest {
                action: ChangeAction::Create,
                change_id: None,
                expected_revision: None,
                base_identity: None,
                patches: Vec::new(),
                new_files: Vec::new(),
                migration: None,
                target: GateTargetId::Check,
                options: ValidationOptions::default(),
                detail: GateDetail::Compact,
                timings: false,
            },
            &fixture.workspace(),
            CancellationToken::new(),
            None,
        )
        .await;
    assert_eq!(outcome.status, "CREATED", "{:#?}", outcome.data.reason);
    (
        outcome.data.change_id.expect("change id"),
        outcome.data.base_identity.expect("base identity published"),
    )
}

async fn stage(
    fixture: &Fixture,
    id: &str,
    revision: u64,
    base: &str,
    patches: Vec<PatchInput>,
    new_files: Vec<NewFileInput>,
) -> u64 {
    let outcome = fixture
        .change
        .execute(
            ChangeRequest {
                action: ChangeAction::Stage,
                change_id: Some(id.to_owned()),
                expected_revision: Some(revision),
                base_identity: Some(base.to_owned()),
                patches,
                new_files,
                migration: None,
                target: GateTargetId::Check,
                options: ValidationOptions::default(),
                detail: GateDetail::Compact,
                timings: false,
            },
            &fixture.workspace(),
            CancellationToken::new(),
            None,
        )
        .await;
    assert_eq!(outcome.status, "STAGED", "{:#?}", outcome.data.reason);
    outcome.data.revision
}

fn patch(file: &str, old: &str, new: &str) -> PatchInput {
    PatchInput {
        file: file.to_owned(),
        old_string: old.to_owned(),
        new_string: new.to_owned(),
    }
}

#[tokio::test]
async fn plan_orders_scopes_and_widens_on_global_inputs() {
    let fixture = Fixture::new(
        "plan",
        "/// Adds one.\n///\n/// ```\n/// assert_eq!(verify_tests_fixture::add(1), 2);\n/// ```\npub fn add(value: i64) -> i64 { value + 1 }\n",
        &[("examples/demo.rs", "fn main() {}\n")],
    );
    let service = fixture.verify();

    let mut widened = request(
        &fixture,
        VerifyAction::TestPlan,
        ValidationOptions::default(),
    );
    widened.changed_paths = vec!["Cargo.toml".to_owned()];
    widened.test_mappings = vec![mapping("add_doctest")];
    widened.semantic_references = vec![SemanticReference {
        file: "src/lib.rs".to_owned(),
        symbol: Some("add".to_owned()),
    }];
    let outcome = execute(&service, widened).await;
    assert_eq!(outcome.status, "PLANNED", "{outcome:#?}");
    let plan = outcome.test_plan.expect("test plan");
    assert!(plan.full, "{plan:#?}");
    assert!(
        plan.widened_because
            .iter()
            .any(|reason| reason.contains("manifest")),
        "{plan:#?}"
    );
    assert!(
        plan.items.first().expect("mapping first").scope == "mapping",
        "{plan:#?}"
    );
    assert!(
        plan.items
            .iter()
            .any(|item| item.target_kind == "doctest" && item.runner == "cargo"),
        "{plan:#?}"
    );
    assert!(
        plan.items.iter().all(|item| !item.reason.is_empty()),
        "{plan:#?}"
    );
    assert!(
        plan.sources
            .iter()
            .any(|source| source.contains("inventory")),
        "{plan:#?}"
    );
    assert!(
        plan.skipped
            .iter()
            .any(|skipped| skipped.reason.contains("example")),
        "{plan:#?}"
    );

    let mut narrow = request(
        &fixture,
        VerifyAction::TestPlan,
        ValidationOptions::default(),
    );
    narrow.changed_paths = vec!["src/lib.rs".to_owned()];
    let outcome = execute(&service, narrow).await;
    let plan = outcome.test_plan.expect("test plan");
    assert!(
        plan.widened_because
            .iter()
            .any(|reason| reason.contains("library root")),
        "{plan:#?}"
    );

    // A nextest selection still plans the doctest scope under the cargo runner.
    let configuration = ValidationOptions {
        runner: TestRunner::Nextest,
        ..ValidationOptions::default()
    };
    let mut nextest = request(&fixture, VerifyAction::TestPlan, configuration);
    nextest.changed_paths = vec!["Cargo.toml".to_owned()];
    let outcome = execute(&service, nextest).await;
    let plan = outcome.test_plan.expect("test plan");
    assert!(
        plan.items
            .iter()
            .any(|item| item.target_kind == "doctest" && item.runner == "cargo"),
        "{plan:#?}"
    );
}

#[tokio::test]
async fn run_records_exact_identity_and_never_passes_empty_evidence() {
    let fixture = Fixture::new(
        "run",
        "pub fn add(left: i64, right: i64) -> i64 { left + right }\n\n\
         #[cfg(test)]\nmod tests {\n    #[test]\n    fn tests_pass() { assert_eq!(super::add(1, 2), 3); }\n    \
         #[test]\n    #[ignore]\n    fn tests_ignored() { assert_eq!(super::add(1, 1), 2); }\n    \
         #[test]\n    fn target() {}\n    #[test]\n    fn target_extra() {}\n}\n",
        &[],
    );
    let service = fixture.verify();
    let mut request = request(
        &fixture,
        VerifyAction::TestRun,
        ValidationOptions::default(),
    );
    request.test_mappings = vec![
        mapping("tests_pass"),
        mapping("tests_ignored"),
        mapping("tests_missing"),
        mapping("target"),
        mapping("targ"),
    ];
    request.test_mappings[0].package = Some(PACKAGE.to_owned());
    let outcome = execute(&service, request).await;
    assert_eq!(outcome.status, "TESTED_SUBSET", "{outcome:#?}");
    assert!(!outcome.complete);
    let run = outcome.test_run.expect("test run");
    assert_eq!(run.suite, "TESTED_SUBSET");
    assert!(!run.full);
    let find = |name: &str| {
        run.items
            .iter()
            .find(|item| item.item.exact_test.as_deref() == Some(name))
            .unwrap_or_else(|| panic!("missing item {name}: {run:#?}"))
    };
    let pass = find("tests_pass");
    assert_eq!(pass.status, "PASS", "{pass:#?}");
    assert!(pass.exact_test_seen);
    assert!(pass.tests_executed > 0);
    assert!(!pass.executed_names.is_empty());
    assert!(
        pass.command_hash
            .as_deref()
            .is_some_and(|hash| !hash.is_empty())
    );
    assert_eq!(pass.item.package, PACKAGE);
    assert_eq!(find("target").item.package, "workspace");
    assert_eq!(
        find("tests_missing").status,
        "ZERO_MATCH",
        "{:#?}",
        find("tests_missing")
    );
    assert_eq!(find("tests_ignored").status, "IGNORED_ONLY");
    // The substring filter runs a superset but the exact name is present.
    assert_eq!(find("target").status, "PASS");
    // A substring collision must not count as evidence for `targ`.
    assert_eq!(find("targ").status, "INCONCLUSIVE");
    assert_ne!(find("tests_missing").status, "PASS");
}

#[tokio::test]
async fn run_reports_full_suite_only_for_the_whole_inventory() {
    let fixture = Fixture::new(
        "full",
        "/// Adds one.\n///\n/// ```\n/// assert_eq!(verify_tests_fixture::add(1), 2);\n/// ```\npub fn add(value: i64) -> i64 { value + 1 }\n\n\
         #[cfg(test)]\nmod tests {\n    #[test]\n    fn add_works() { assert_eq!(super::add(1), 2); }\n}\n",
        &[],
    );
    let service = fixture.verify();
    let mut request = request(
        &fixture,
        VerifyAction::TestRun,
        ValidationOptions::default(),
    );
    // A library-root change conservatively covers the full workspace inventory.
    request.changed_paths = vec!["src/lib.rs".to_owned()];
    let outcome = execute(&service, request).await;
    assert_eq!(outcome.status, "FULL_REQUESTED_SUITE", "{outcome:#?}");
    assert!(outcome.complete);
    assert!(outcome.all_pass);
    let run = outcome.test_run.expect("test run");
    assert!(run.full);
    assert_eq!(run.suite, "FULL_REQUESTED_SUITE");
    assert!(run.doctest_gate.starts_with("REQUIRED"), "{run:#?}");
    assert!(
        run.items
            .iter()
            .all(|item| item.status == "PASS" && item.tests_executed > 0),
        "{run:#?}"
    );
}

#[tokio::test]
async fn candidate_regression_fails_baseline_and_passes_candidate() {
    let fixture = Fixture::new("candidate", "pub fn answer() -> i64 { 0 }\n", &[]);
    let service = fixture.verify();
    let (id, base) = create_change(&fixture).await;
    let revision = stage(
        &fixture,
        &id,
        0,
        &base,
        vec![patch(
            "src/lib.rs",
            "pub fn answer() -> i64 { 0 }",
            "pub fn answer() -> i64 { 42 }",
        )],
        Vec::new(),
    )
    .await;
    assert_eq!(revision, 1);

    let mut request = request(
        &fixture,
        VerifyAction::TestCandidate,
        ValidationOptions::default(),
    );
    request.change_id = Some(id.clone());
    request.test_patch = Some(TestPatchInput {
        patches: Vec::new(),
        new_files: vec![NewFileInput {
            file: "tests/regression.rs".to_owned(),
            content: "#[test]\nfn regression_answer() {\n    assert_eq!(\
                      verify_tests_fixture::answer(), 42, \"answer must be 42\");\n}\n"
                .to_owned(),
        }],
    });
    request.behavior_contract = Some(BehaviorContract {
        test_name: "regression_answer".to_owned(),
        package: Some(PACKAGE.to_owned()),
        target: Some("regression".to_owned()),
        expected_failure: "answer must be 42".to_owned(),
    });
    let outcome = execute(&service, request).await;
    assert_eq!(outcome.status, "SATISFIED", "{outcome:#?}");
    assert!(outcome.complete);
    let data = outcome.test_candidate.expect("candidate data");
    assert_eq!(data.contract_status, "SATISFIED");
    assert!(data.compatible);
    assert!(!data.flaky);
    assert!(data.reconstructed_candidate);
    assert_eq!(data.baseline.fail_observed, 1);
    assert_eq!(data.candidate.pass_observed, 1);
    assert!(
        data.baseline
            .repeats
            .iter()
            .all(|repeat| repeat.expected_failure_seen && repeat.exact_test_seen),
        "{data:#?}"
    );
    assert!(data.detections.is_empty(), "{data:#?}");

    // The original workspace source is never modified.
    let source = fs::read_to_string(fixture.root.join("src/lib.rs")).expect("read source");
    assert!(source.contains("{ 0 }"), "{source}");
    // The server-owned probe scratch is released after the comparison.
    if let Some(probe) = data.probe_change_id {
        assert!(
            !fixture
                .scratch_change_dir(&probe)
                .join("candidate")
                .exists(),
            "probe candidate should be discarded"
        );
    } else {
        panic!("probe change id must be reported");
    }
}

#[tokio::test]
async fn candidate_rejects_test_patch_tampering_before_running() {
    let fixture = Fixture::new("tamper", "pub fn answer() -> i64 { 0 }\n", &[]);
    let service = fixture.verify();
    let (id, base) = create_change(&fixture).await;
    stage(
        &fixture,
        &id,
        0,
        &base,
        vec![patch(
            "src/lib.rs",
            "pub fn answer() -> i64 { 0 }",
            "pub fn answer() -> i64 { 42 }",
        )],
        Vec::new(),
    )
    .await;

    let mut request = request(
        &fixture,
        VerifyAction::TestCandidate,
        ValidationOptions::default(),
    );
    request.change_id = Some(id);
    request.test_patch = Some(TestPatchInput {
        patches: vec![patch(
            "tests/old.rs",
            "#[test]\nfn old_regression() { assert!(true); }\n",
            "",
        )],
        new_files: vec![NewFileInput {
            file: "tests/regression.rs".to_owned(),
            content: "#[test]\nfn regression_answer() { assert_eq!(value(), 42); }\n".to_owned(),
        }],
    });
    request.behavior_contract = Some(BehaviorContract {
        test_name: "regression_answer".to_owned(),
        package: None,
        target: None,
        expected_failure: "assertion failed".to_owned(),
    });
    let outcome = execute(&service, request).await;
    assert_eq!(outcome.status, "REJECTED", "{outcome:#?}");
    let data = outcome.test_candidate.expect("candidate data");
    assert!(
        data.detections
            .iter()
            .any(|row| row.starts_with("test-deletion")),
        "{data:#?}"
    );
    assert!(
        data.baseline.repeats.is_empty() && data.candidate.repeats.is_empty(),
        "rejected patches must not run tests: {data:#?}"
    );
}

#[tokio::test]
async fn candidate_detects_fix_side_test_deletion() {
    let fixture = Fixture::new(
        "delete",
        "pub fn answer() -> i64 { 0 }\n",
        &[(
            "tests/existing.rs",
            "#[test]\nfn existing_one() { assert!(true); }\n\n#[test]\nfn existing_two() { assert!(true); }\n",
        )],
    );
    let service = fixture.verify();
    let (id, base) = create_change(&fixture).await;
    // The fix both corrects the behavior and deletes an existing test.
    stage(
        &fixture,
        &id,
        0,
        &base,
        vec![
            patch(
                "src/lib.rs",
                "pub fn answer() -> i64 { 0 }",
                "pub fn answer() -> i64 { 42 }",
            ),
            patch(
                "tests/existing.rs",
                "#[test]\nfn existing_two() { assert!(true); }\n",
                "",
            ),
        ],
        Vec::new(),
    )
    .await;

    let mut request = request(
        &fixture,
        VerifyAction::TestCandidate,
        ValidationOptions::default(),
    );
    request.change_id = Some(id);
    request.test_patch = Some(TestPatchInput {
        patches: Vec::new(),
        new_files: vec![NewFileInput {
            file: "tests/regression.rs".to_owned(),
            content: "#[test]\nfn regression_answer() {\n    assert_eq!(\
                      verify_tests_fixture::answer(), 42, \"answer must be 42\");\n}\n"
                .to_owned(),
        }],
    });
    request.behavior_contract = Some(BehaviorContract {
        test_name: "regression_answer".to_owned(),
        package: None,
        target: None,
        expected_failure: "answer must be 42".to_owned(),
    });
    let budget = VerifyBudget {
        repeats: Some(1),
        ..VerifyBudget::default()
    };
    request.budget = budget;
    let outcome = execute(&service, request).await;
    assert_eq!(outcome.status, "REJECTED", "{outcome:#?}");
    let data = outcome.test_candidate.expect("candidate data");
    assert!(
        data.detections
            .iter()
            .any(|row| row.starts_with("candidate-deletes-tests")),
        "{data:#?}"
    );
    assert!(
        data.candidate.repeats.is_empty(),
        "candidate runs must stop after detection: {data:#?}"
    );
}

#[tokio::test]
async fn candidate_reports_flakiness_with_repeat_counts() {
    let fixture = Fixture::new("flaky", "pub fn answer() -> i64 { 0 }\n", &[]);
    let service = fixture.verify();
    let (id, base) = create_change(&fixture).await;
    stage(
        &fixture,
        &id,
        0,
        &base,
        vec![patch(
            "src/lib.rs",
            "pub fn answer() -> i64 { 0 }",
            "pub fn answer() -> i64 { 42 }",
        )],
        Vec::new(),
    )
    .await;

    let mut request = request(
        &fixture,
        VerifyAction::TestCandidate,
        ValidationOptions::default(),
    );
    request.change_id = Some(id);
    request.budget = VerifyBudget {
        repeats: Some(2),
        ..VerifyBudget::default()
    };
    request.test_patch = Some(TestPatchInput {
        patches: Vec::new(),
        new_files: vec![NewFileInput {
            file: "tests/flaky.rs".to_owned(),
            content: "#[test]\nfn flaky_regression() {\n    let cwd = std::env::current_dir()\
                      .expect(\"cwd\");\n    let probe = cwd\n        .parent()\n        .and_then(|parent| parent.file_name())\n        .map(|name| name.to_string_lossy().into_owned())\n        .expect(\"probe directory name\");\n    let state = std::path::Path::new(&std::env::temp_dir())\n        .join(format!(\"agz-verify-flaky-{probe}\"));\n    let seen = state.exists();\n    if !seen {\n        std::fs::write(&state, b\"seen\").expect(\"state file\");\n    }\n    \
                      assert!(seen, \"flaky probe first run fails\");\n}\n"
                .to_owned(),
        }],
    });
    request.behavior_contract = Some(BehaviorContract {
        test_name: "flaky_regression".to_owned(),
        package: None,
        target: None,
        expected_failure: "flaky probe first run fails".to_owned(),
    });
    let outcome = execute(&service, request).await;
    assert_eq!(outcome.status, "INCONCLUSIVE", "{outcome:#?}");
    let data = outcome.test_candidate.expect("candidate data");
    assert!(data.flaky, "{data:#?}");
    assert_eq!(data.repeats, 2);
    assert_eq!(data.baseline.fail_observed, 1);
    assert_eq!(data.baseline.pass_observed, 1);
    assert_eq!(data.baseline.repeats.len(), 2);
    assert!(
        outcome
            .warnings
            .iter()
            .any(|warning| warning.contains("flak")),
        "{:#?}",
        outcome.warnings
    );
    if let Some(probe) = data.probe_change_id {
        let state = std::env::temp_dir().join(format!("agz-verify-flaky-{probe}"));
        let _ = fs::remove_file(state);
    }
}
