use std::{
    fs,
    path::{Path, PathBuf},
    process::Command,
    sync::Arc,
    time::{SystemTime, UNIX_EPOCH},
};

use agz_rust_coder::{
    Config,
    config::VerifyConfig,
    tools::{
        CheckService, RequiredConfigurations, VerifyAction, VerifyBudget, VerifyOutcome,
        VerifyRequest, VerifyRunner, VerifyService, VerifyStage,
    },
    workspace::{ClientRoots, RootGuard},
};

struct TestProject {
    root: PathBuf,
    state: PathBuf,
}

impl TestProject {
    fn new(label: &str, extra_manifest: &str, source: &str) -> Self {
        Self::build(label, None, extra_manifest, source)
    }

    fn with_rust_version(label: &str, version: &str, extra_manifest: &str, source: &str) -> Self {
        Self::build(label, Some(version), extra_manifest, source)
    }

    fn build(label: &str, rust_version: Option<&str>, extra_manifest: &str, source: &str) -> Self {
        let stamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map_or(0, |duration| duration.as_nanos());
        let base = fs::canonicalize(std::env::temp_dir())
            .expect("canonical temp directory")
            .join(format!(
                "agz-rust-coder-verify-{label}-{}-{stamp}",
                std::process::id()
            ));
        let root = base.join("workspace");
        let state = base.join("state");
        fs::create_dir_all(root.join("src")).expect("create project source directory");
        fs::create_dir_all(&state).expect("create project state directory");
        let rust_version = rust_version.map_or_else(String::new, |version| {
            format!("rust-version = \"{version}\"\n")
        });
        fs::write(
            root.join("Cargo.toml"),
            format!(
                "[package]\nname = \"verify-fixture\"\nversion = \"0.1.0\"\nedition = \"2024\"\n\
                 {rust_version}\n[workspace]\n{extra_manifest}\n"
            ),
        )
        .expect("write manifest");
        fs::write(
            root.join("Cargo.lock"),
            "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"verify-fixture\"\nversion = \"0.1.0\"\n",
        )
        .expect("write lockfile");
        fs::write(root.join("src/lib.rs"), source).expect("write source");
        git(&root, &["init", "--quiet"]);
        git(&root, &["config", "user.email", "verify@example.invalid"]);
        git(&root, &["config", "user.name", "Verify Fixture"]);
        git(&root, &["add", "."]);
        git(&root, &["commit", "--quiet", "-m", "fixture"]);
        Self { root, state }
    }

    fn service(&self) -> Arc<VerifyService> {
        let mut config = Config::defaults_at(&self.root);
        config.gate.debounce_ms = 10;
        config.gate.hard_timeout_ms = 120_000;
        config.gate.cache_dir = self.state.join("cache");
        config.gate.lease_dir = self.state.join("leases");
        let guard = Arc::new(
            RootGuard::new([self.root.clone()], std::iter::empty()).expect("create root guard"),
        );
        let check = Arc::new(CheckService::new(config, guard));
        Arc::new(VerifyService::new(
            check,
            VerifyConfig {
                max_cells: 8,
                max_wall_ms: 300_000,
            },
        ))
    }
}

impl Drop for TestProject {
    fn drop(&mut self) {
        if let Some(base) = self.root.parent() {
            let _ = fs::remove_dir_all(base);
        }
    }
}

fn git(root: &Path, arguments: &[&str]) {
    let status = Command::new("git")
        .args(arguments)
        .current_dir(root)
        .status()
        .expect("run git fixture command");
    assert!(status.success(), "git command failed: {arguments:?}");
}

fn request(
    action: VerifyAction,
    root: &Path,
    required: RequiredConfigurations,
    budget: VerifyBudget,
) -> VerifyRequest {
    VerifyRequest {
        action,
        directory: Some(root.to_path_buf()),
        client_roots: ClientRoots::unsupported(),
        root_epoch: 0,
        change_id: Some("change-42".to_owned()),
        required,
        budget,
    }
}

fn check_only_budget(cells: u32) -> VerifyBudget {
    VerifyBudget {
        max_cells: Some(cells),
        max_wall_ms: Some(240_000),
    }
}

fn cell<'a>(outcome: &'a VerifyOutcome, id_part: &str) -> &'a agz_rust_coder::tools::CellOutcome {
    outcome
        .cells
        .iter()
        .find(|cell| cell.id.contains(id_part))
        .unwrap_or_else(|| panic!("missing cell {id_part}: {:#?}", outcome.cells))
}

#[tokio::test]
async fn default_pass_and_no_default_failure_are_distinct_and_bound() {
    let project = TestProject::new(
        "default",
        "[features]\ndefault = [\"ok\"]\nok = []",
        "#[cfg(feature = \"ok\")]\npub fn value() -> usize { 1 }\n\n\
         #[cfg(not(feature = \"ok\"))]\ncompile_error!(\"no-default configuration is broken\");\n",
    );
    let service = project.service();
    let required = RequiredConfigurations {
        include_default: true,
        include_no_default: true,
        include_policy: false,
        stages: vec![VerifyStage::Check],
        ..RequiredConfigurations::default()
    };
    let outcome = service
        .execute(
            request(
                VerifyAction::MatrixRun,
                &project.root,
                required.clone(),
                check_only_budget(4),
            ),
            None,
            None,
        )
        .await;

    assert_eq!(outcome.cells.len(), 2, "{outcome:#?}");
    let default = cell(&outcome, "default--host--default--check");
    let no_default = cell(&outcome, "no-default--host--default--check");
    assert_eq!(default.status, "PASS", "{default:#?}");
    assert_eq!(no_default.status, "FAIL", "{no_default:#?}");
    assert_eq!(outcome.status, "FULL_REQUESTED_MATRIX", "{outcome:#?}");
    assert!(outcome.complete);
    assert!(!outcome.all_pass);
    assert_eq!(outcome.completed_cell_ids.len(), 2);
    assert!(outcome.missing_cell_ids.is_empty());
    assert_eq!(outcome.change_id.as_deref(), Some("change-42"));
    assert!(!outcome.exhaustive);
    assert!(outcome.resolver.contains("edition-default") || !outcome.resolver.is_empty());
    assert!(outcome.feature_unification.contains("resolver"));

    // Evidence binds each result to source/lock/config/toolchain.
    assert!(
        default
            .input_hash
            .as_deref()
            .is_some_and(|hash| !hash.is_empty())
    );
    assert_ne!(default.input_hash, no_default.input_hash);
    assert_ne!(default.command_hash, no_default.command_hash);
    assert!(
        default
            .command_hash
            .as_deref()
            .is_some_and(|hash| !hash.is_empty())
            && default
                .environment_hash
                .as_deref()
                .is_some_and(|hash| !hash.is_empty())
    );
    assert!(default.job_id.as_deref().is_some_and(|id| !id.is_empty()));
    assert!(no_default.duration_ms > 0);
    assert!(outcome.package_scope == "workspace");
    assert_eq!(default.strategy.as_deref(), Some("shadow"));
    assert_eq!(no_default.strategy.as_deref(), Some("workspace"));

    // A plan reports the same cells without executing them.
    let plan = service
        .execute(
            request(
                VerifyAction::MatrixPlan,
                &project.root,
                required,
                check_only_budget(4),
            ),
            None,
            None,
        )
        .await;
    assert_eq!(plan.status, "PLANNED");
    assert!(plan.cells.iter().all(|cell| cell.status == "PLANNED"));
    assert!(plan.cells.iter().all(|cell| cell.job_id.is_none()));
}

#[tokio::test]
async fn unsupported_feature_combinations_are_typed_and_never_green() {
    let project = TestProject::new(
        "unsupported",
        "[features]\ndefault = []\ntls-native = []\ntls-rustls = []\n\n\
         [workspace.metadata.agz-verify]\nfeature-groups = [[\"tls-native\", \"tls-rustls\"], [\"missing-feature\"]]\n\
         mutually-exclusive-features = [[\"tls-native\", \"tls-rustls\"]]",
        "pub fn value() -> usize { 1 }\n",
    );
    let service = project.service();
    let required = RequiredConfigurations {
        include_default: false,
        include_policy: true,
        stages: vec![VerifyStage::Check],
        ..RequiredConfigurations::default()
    };
    let plan = service
        .execute(
            request(
                VerifyAction::MatrixPlan,
                &project.root,
                required.clone(),
                check_only_budget(8),
            ),
            None,
            None,
        )
        .await;
    assert_eq!(plan.status, "PLANNED", "{plan:#?}");
    assert!(plan.cells.is_empty(), "{:#?}", plan.cells);
    assert_eq!(plan.skipped.len(), 2);
    assert!(
        plan.skipped
            .iter()
            .all(|cell| cell.status == "UNSUPPORTED_CONFIGURATION")
    );
    assert!(
        plan.skipped
            .iter()
            .any(|cell| cell.reason.contains("mutually exclusive"))
    );
    assert!(
        plan.skipped
            .iter()
            .any(|cell| cell.reason.contains("not declared"))
    );
    assert!(plan.policy_source.contains("agz-verify"));

    let run = service
        .execute(
            request(
                VerifyAction::MatrixRun,
                &project.root,
                required,
                check_only_budget(8),
            ),
            None,
            None,
        )
        .await;
    assert_eq!(run.status, "PARTIAL", "{run:#?}");
    assert!(!run.complete);
    assert!(!run.all_pass);
    assert!(run.cells.is_empty());
    assert!(run.completed_cell_ids.is_empty());
    assert_eq!(run.missing_cell_ids.len(), 2);
}

#[tokio::test]
async fn budget_exhaustion_separates_completed_and_skipped_cells() {
    let project = TestProject::new(
        "budget",
        "[features]\ndefault = []\na = []\nb = []\n\n\
         [workspace.metadata.agz-verify]\nfeature-groups = [[\"a\"], [\"b\"]]",
        "pub fn value() -> usize { 1 }\n",
    );
    let service = project.service();
    let required = RequiredConfigurations {
        include_default: true,
        include_no_default: true,
        include_policy: true,
        stages: vec![VerifyStage::Check],
        ..RequiredConfigurations::default()
    };
    let outcome = service
        .execute(
            request(
                VerifyAction::MatrixRun,
                &project.root,
                required,
                check_only_budget(1),
            ),
            None,
            None,
        )
        .await;
    assert_eq!(outcome.status, "PARTIAL", "{outcome:#?}");
    assert!(!outcome.complete);
    assert_eq!(outcome.budget.executed, 1);
    assert_eq!(outcome.cells.len(), 1);
    assert_eq!(outcome.cells[0].status, "PASS");
    assert_eq!(outcome.completed_cell_ids.len(), 1);
    assert!(
        outcome
            .skipped
            .iter()
            .all(|cell| cell.status == "SKIPPED_BUDGET")
    );
    assert_eq!(outcome.skipped.len(), 3);
    assert_eq!(outcome.missing_cell_ids.len(), 3);
    // Skipped cells are never green and never appear as completed.
    assert!(
        outcome
            .completed_cell_ids
            .iter()
            .all(|id| !outcome.missing_cell_ids.contains(id))
    );
}

#[tokio::test]
async fn not_installed_target_is_reported_without_download() {
    let project = TestProject::new("target", "", "pub fn value() -> usize { 1 }\n");
    let service = project.service();
    let target = "thumbv7em-none-eabi";
    let required = RequiredConfigurations {
        include_default: false,
        include_policy: false,
        targets: vec![target.to_owned()],
        stages: vec![VerifyStage::Check],
        ..RequiredConfigurations::default()
    };
    let outcome = service
        .execute(
            request(
                VerifyAction::MatrixPlan,
                &project.root,
                required.clone(),
                check_only_budget(4),
            ),
            None,
            None,
        )
        .await;
    let installed_cell = outcome
        .cells
        .iter()
        .any(|cell| cell.target_triple.as_deref() == Some(target));
    let not_installed = outcome
        .skipped
        .iter()
        .any(|cell| cell.status == "NOT_INSTALLED" && cell.reason.contains(target));
    assert!(
        installed_cell || not_installed,
        "target must be either planned or typed as not installed: {outcome:#?}"
    );
    if not_installed {
        assert!(!outcome.installed_targets.iter().any(|item| item == target));
    }
    let run = service
        .execute(
            request(
                VerifyAction::MatrixRun,
                &project.root,
                required,
                check_only_budget(4),
            ),
            None,
            None,
        )
        .await;
    assert!(!run.complete || run.cells.iter().all(|cell| cell.status != "FAIL"));
    if not_installed {
        assert_eq!(run.status, "PARTIAL");
        assert!(
            run.skipped
                .iter()
                .any(|cell| cell.status == "NOT_INSTALLED")
        );
    }
}

#[tokio::test]
async fn installed_cross_target_is_compile_only_and_never_claims_tests() {
    let project = TestProject::new("cross", "", "pub fn value() -> usize { 1 }\n");
    let service = project.service();
    let target = "x86_64-pc-windows-gnu";
    let required = RequiredConfigurations {
        include_default: false,
        include_policy: false,
        targets: vec![target.to_owned()],
        stages: vec![VerifyStage::Check, VerifyStage::Test],
        ..RequiredConfigurations::default()
    };
    let plan = service
        .execute(
            request(
                VerifyAction::MatrixPlan,
                &project.root,
                required.clone(),
                check_only_budget(4),
            ),
            None,
            None,
        )
        .await;
    let target_installed = plan.installed_targets.iter().any(|item| item == target);
    if target_installed {
        let cross = cell(&plan, target);
        assert_eq!(cross.stage, "check");
        assert!(cross.compile_only);
        assert!(!cross.test_execution_claimed);
    } else {
        assert!(
            plan.skipped
                .iter()
                .any(|cell| cell.status == "NOT_INSTALLED" && cell.reason.contains(target))
        );
    }
    // A requested non-check stage on a foreign target is explicitly unsupported.
    assert!(plan.skipped.iter().any(|cell| {
        cell.status == "UNSUPPORTED_CONFIGURATION" && cell.reason.contains("compile-only")
    }));
    if target_installed {
        let run = service
            .execute(
                request(
                    VerifyAction::MatrixRun,
                    &project.root,
                    required,
                    check_only_budget(4),
                ),
                None,
                None,
            )
            .await;
        for cell in &run.cells {
            if cell.target_triple.is_some() {
                assert_eq!(cell.stage, "check");
                assert!(cell.compile_only);
            }
            assert!(!cell.test_execution_claimed);
        }
        assert_eq!(
            run.cells
                .iter()
                .filter(|cell| cell.target_triple.is_some())
                .count(),
            1
        );
    }
}

#[tokio::test]
async fn completed_pass_is_not_reused_for_a_new_explicit_run() {
    let project = TestProject::new("reuse", "", "pub fn value() -> usize { 1 }\n");
    let service = project.service();
    let required = RequiredConfigurations {
        include_default: true,
        include_policy: false,
        stages: vec![VerifyStage::Check],
        ..RequiredConfigurations::default()
    };
    let first = service
        .execute(
            request(
                VerifyAction::MatrixRun,
                &project.root,
                required.clone(),
                check_only_budget(2),
            ),
            None,
            None,
        )
        .await;
    let second = service
        .execute(
            request(
                VerifyAction::MatrixRun,
                &project.root,
                required,
                check_only_budget(2),
            ),
            None,
            None,
        )
        .await;
    let first_cell = cell(&first, "default--host--default--check");
    let second_cell = cell(&second, "default--host--default--check");
    assert_eq!(first_cell.status, "PASS", "{first:#?}");
    assert_eq!(second_cell.status, "PASS", "{second:#?}");
    assert_ne!(first_cell.job_id, second_cell.job_id);
}

#[tokio::test]
async fn msrv_cell_uses_the_installed_toolchain_when_present() {
    let project =
        TestProject::with_rust_version("msrv", "1.88", "", "pub fn value() -> usize { 1 }\n");
    let service = project.service();
    let required = RequiredConfigurations {
        include_default: false,
        include_policy: false,
        include_msrv: true,
        stages: vec![VerifyStage::Check],
        ..RequiredConfigurations::default()
    };
    let plan = service
        .execute(
            request(
                VerifyAction::MatrixPlan,
                &project.root,
                required.clone(),
                check_only_budget(2),
            ),
            None,
            None,
        )
        .await;
    let msrv_cell = plan.cells.iter().find(|cell| cell.toolchain.is_some());
    match msrv_cell {
        Some(cell) => {
            assert!(
                cell.msrv
                    .as_deref()
                    .is_some_and(|msrv| msrv.starts_with("1.88")),
                "{cell:#?}"
            );
            let toolchain = cell.toolchain.clone().expect("toolchain");
            let outcome = service
                .execute(
                    request(
                        VerifyAction::MatrixRun,
                        &project.root,
                        required,
                        check_only_budget(2),
                    ),
                    None,
                    None,
                )
                .await;
            let executed = outcome
                .cells
                .iter()
                .find(|cell| cell.toolchain.as_deref() == Some(toolchain.as_str()))
                .expect("msrv cell");
            assert_eq!(executed.status, "PASS", "{executed:#?}");
            assert_eq!(executed.gate_status.as_deref(), Some("FAST_PASS"));
            assert!(executed.command_hash.is_some());
        }
        None => {
            assert!(plan.skipped.iter().any(|cell| {
                cell.status == "NOT_INSTALLED" || cell.status == "UNSUPPORTED_CONFIGURATION"
            }));
        }
    }
}

#[tokio::test]
async fn nextest_missing_runner_is_typed_as_runner_unavailable() {
    let project = TestProject::new(
        "runner",
        "",
        "pub fn value() -> usize { 1 }\n#[test]\nfn works() { value(); }\n",
    );
    let service = project.service();
    let required = RequiredConfigurations {
        include_default: true,
        include_policy: false,
        stages: vec![VerifyStage::Test],
        runner: VerifyRunner::Nextest,
        ..RequiredConfigurations::default()
    };
    let outcome = service
        .execute(
            request(
                VerifyAction::MatrixRun,
                &project.root,
                required,
                check_only_budget(2),
            ),
            None,
            None,
        )
        .await;
    let cell = &outcome.cells[0];
    assert_eq!(cell.runner, "nextest");
    // Either nextest is available and may pass/fail, or the runner is typed
    // unavailable; the cell is never silently treated as a green check.
    assert!(
        matches!(
            cell.status.as_str(),
            "RUNNER_UNAVAILABLE" | "PASS" | "FAIL" | "INCONCLUSIVE"
        ),
        "{cell:#?}"
    );
    if cell.status == "RUNNER_UNAVAILABLE" {
        assert!(!cell.test_execution_claimed);
        assert!(!outcome.complete);
    }
}
