//! Provider-free end-to-end tests for the bounded `work` executor.
//!
//! Each fixture builds a temporary Cargo project and a real `ChangeService`
//! over server-owned scratch. The "fake host" is the test itself: it receives a
//! `NEEDS_MODEL` handoff, then supplies candidate patches through `resume`.
//! Nothing here needs a model, a network, or a shell command surface.

use std::{
    fs,
    path::{Path, PathBuf},
    sync::Arc,
    time::{Duration, SystemTime, UNIX_EPOCH},
};

use agz_rust_coder::{
    Config,
    change::{ChangeService, PatchInput},
    process::ProcessSupervisor,
    server::WorkInput,
    work::{
        WorkAction, WorkBudget, WorkChangeBudget, WorkConstraints, WorkGate, WorkIntent,
        WorkOutcome, WorkRequest, WorkService, WorkTemplate, WorkTool,
    },
    workspace::{ClientRoots, RootGuard, WorkspaceRoot},
};
use sha2::{Digest, Sha256};
use tokio_util::sync::CancellationToken;

struct Fixture {
    root: PathBuf,
    state: PathBuf,
    guard: Arc<RootGuard>,
    config: Config,
    change: Arc<ChangeService>,
    work: Arc<WorkService>,
}

impl Fixture {
    fn new(label: &str, source: &[u8], mutate: impl FnOnce(&mut Config)) -> Self {
        let stamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map_or(0, |duration| duration.as_nanos());
        let base = fs::canonicalize(std::env::temp_dir())
            .expect("canonical temp directory")
            .join(format!(
                "agz-rust-coder-work-{label}-{}-{stamp}",
                std::process::id()
            ));
        let root = base.join("workspace");
        let state = base.join("state");
        fs::create_dir_all(root.join("src")).expect("create project source directory");
        fs::create_dir_all(&state).expect("create state directory");
        fs::write(
            root.join("Cargo.toml"),
            "[package]\nname = \"work-fixture\"\nversion = \"0.1.0\"\nedition = \"2024\"\n\n[workspace]\n",
        )
        .expect("write manifest");
        fs::write(
            root.join("Cargo.lock"),
            "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"work-fixture\"\nversion = \"0.1.0\"\n",
        )
        .expect("write lockfile");
        fs::write(root.join("src/lib.rs"), source).expect("write source");
        let mut config = Config::defaults_at(&root);
        config.gate.debounce_ms = 10;
        config.gate.hard_timeout_ms = 120_000;
        config.gate.cache_dir = state.join("gate-cache");
        config.gate.lease_dir = state.join("leases");
        config.change.scratch_dir = state.join("change");
        config.work.continuation_ttl_ms = 300_000;
        config.telemetry.enabled = false;
        config.telemetry.path = state.join("activity.jsonl");
        mutate(&mut config);
        let dependencies = config.server.allow_dependency_roots.clone();
        let guard =
            Arc::new(RootGuard::new([root.clone()], dependencies).expect("create root guard"));
        let change = Arc::new(
            ChangeService::new(
                config.clone(),
                Arc::clone(&guard),
                ProcessSupervisor::without_journal(),
            )
            .expect("create change service"),
        );
        let work = Arc::new(WorkService::new(&config, Some(Arc::clone(&change))));
        Self {
            root,
            state,
            guard,
            config,
            change,
            work,
        }
    }

    fn workspace(&self) -> WorkspaceRoot {
        self.guard
            .snapshot(ClientRoots::unsupported())
            .expect("root snapshot")
            .select(Some(&self.root))
            .expect("select workspace")
    }

    async fn execute(&self, request: WorkRequest) -> WorkOutcome {
        self.work
            .execute(request, &self.workspace(), CancellationToken::new(), None)
            .await
    }
}

impl Drop for Fixture {
    fn drop(&mut self) {
        if let Some(base) = self.root.parent() {
            let _ = fs::remove_dir_all(base);
        }
    }
}

fn workspace_of(guard: &RootGuard, root: &Path) -> WorkspaceRoot {
    guard
        .snapshot(ClientRoots::unsupported())
        .expect("root snapshot")
        .select(Some(root))
        .expect("select workspace")
}

fn intent() -> WorkIntent {
    WorkIntent {
        template: WorkTemplate::RepairCompileFailure,
        scope_paths: vec!["src".to_owned()],
        contract: "value() returns a u8 without compiler errors".to_owned(),
        stop_condition: "the check gate passes or the declared budget is exhausted".to_owned(),
        acceptance_gates: vec![WorkGate::Check],
        change_budget: WorkChangeBudget {
            max_patches: 8,
            max_new_files: 4,
        },
    }
}

fn budget(max_candidates: u64, max_handoffs: u64) -> WorkBudget {
    WorkBudget {
        max_compiles: 12,
        max_candidates,
        max_handoffs,
        wall_time_ms: 120_000,
    }
}

fn start_request(intent: WorkIntent, patches: Vec<PatchInput>, budget: WorkBudget) -> WorkRequest {
    WorkRequest {
        action: WorkAction::Start,
        work_id: None,
        continuation_token: None,
        change_id: None,
        intent: Some(intent),
        patches,
        new_files: Vec::new(),
        constraints: WorkConstraints::default(),
        budget,
    }
}

fn resume_request(work_id: &str, token: &str, patches: Vec<PatchInput>) -> WorkRequest {
    WorkRequest {
        action: WorkAction::Resume,
        work_id: Some(work_id.to_owned()),
        continuation_token: Some(token.to_owned()),
        change_id: None,
        intent: None,
        patches,
        new_files: Vec::new(),
        constraints: WorkConstraints::default(),
        budget: budget(4, 4),
    }
}

fn inspect_request(work_id: &str) -> WorkRequest {
    WorkRequest {
        action: WorkAction::Inspect,
        work_id: Some(work_id.to_owned()),
        ..resume_request(work_id, "unused", Vec::new())
    }
}

fn cancel_request(work_id: &str) -> WorkRequest {
    WorkRequest {
        action: WorkAction::Cancel,
        work_id: Some(work_id.to_owned()),
        ..resume_request(work_id, "unused", Vec::new())
    }
}

fn patch(file: &str, old: &str, new: &str) -> PatchInput {
    PatchInput {
        file: file.to_owned(),
        old_string: old.to_owned(),
        new_string: new.to_owned(),
    }
}

fn digest(path: &Path) -> String {
    let bytes = fs::read(path).expect("read digest target");
    let mut hasher = Sha256::new();
    hasher.update(&bytes);
    format!("{:x}", hasher.finalize())
}

fn original_hashes(fixture: &Fixture) -> Vec<(String, String)> {
    ["Cargo.toml", "Cargo.lock", "src/lib.rs"]
        .into_iter()
        .map(|relative| (relative.to_owned(), digest(&fixture.root.join(relative))))
        .collect()
}

fn assert_unchanged(fixture: &Fixture, expected: &[(String, String)]) {
    for (relative, hash) in expected {
        assert_eq!(
            &digest(&fixture.root.join(relative)),
            hash,
            "original file changed: {relative}"
        );
    }
}

const BAD_CANDIDATE: &str = "pub fn value() -> u8 { let x: u8 = 1; x = 2; x }";
const DIFFERENT_FAILURE: &str = "let mut x: u8 = 1; x = 2; \"bad\"";
const FIXED_CANDIDATE: &str = "let mut x: u8 = 1; x = 2; x";

#[tokio::test]
async fn handoff_tokens_are_single_use_and_resume_reads_fresh_evidence() {
    let fixture = Fixture::new("tokens", b"pub fn value() -> u8 { 1 }\n", |_| {});
    let originals = original_hashes(&fixture);

    let start = fixture
        .execute(start_request(
            intent(),
            vec![patch(
                "src/lib.rs",
                "pub fn value() -> u8 { 1 }",
                BAD_CANDIDATE,
            )],
            budget(4, 3),
        ))
        .await;
    assert_eq!(start.status, "NEEDS_MODEL", "{start:#?}");
    assert!(!start.is_error);
    assert_eq!(start.data.state, "needs_model");
    assert_eq!(start.data.revision, 1);
    assert!(start.data.used.candidates == 1 && start.data.used.compiles == 1);
    let work_id = start.data.work_id.clone().expect("work id");
    let change_id = start.data.change_id.clone().expect("change id");
    assert!(change_id.starts_with("ch-"), "{change_id}");
    let handoff = start.data.handoff.clone().expect("handoff package");
    assert_eq!(handoff.failure_kind, "compile");
    assert_eq!(handoff.continuation_token.len(), 64);
    assert!(handoff.expires_at_ms > 0);
    assert!(
        handoff
            .diagnostics
            .iter()
            .any(|diagnostic| diagnostic.code.as_deref() == Some("E0384")),
        "{handoff:#?}"
    );
    assert!(
        handoff
            .suggestion_package
            .as_ref()
            .is_some_and(|package| !package.patches.is_empty()),
        "{handoff:#?}"
    );
    assert!(
        handoff
            .unresolved_obligations
            .iter()
            .any(|obligation| obligation.contains("contract")),
        "{handoff:#?}"
    );
    assert!(handoff.candidate_input_schema.is_object());

    // An unrelated token is rejected without consuming the live one.
    let garbage = fixture
        .execute(resume_request(
            &work_id,
            &"0".repeat(64),
            vec![patch("src/lib.rs", BAD_CANDIDATE, BAD_CANDIDATE)],
        ))
        .await;
    assert_eq!(garbage.status, "STALE", "{garbage:#?}");
    assert!(garbage.is_error);

    // The host tries a different repair; it fails with different diagnostics,
    // so a second bounded handoff is issued.
    let second = fixture
        .execute(resume_request(
            &work_id,
            &handoff.continuation_token,
            vec![patch(
                "src/lib.rs",
                "let x: u8 = 1; x = 2; x",
                DIFFERENT_FAILURE,
            )],
        ))
        .await;
    assert_eq!(second.status, "NEEDS_MODEL", "{second:#?}");
    assert_eq!(second.data.revision, 2);
    let second_handoff = second.data.handoff.clone().expect("second handoff");
    assert_ne!(
        second_handoff.continuation_token, handoff.continuation_token,
        "each handoff issues a fresh single-use token"
    );
    assert!(
        !second_handoff
            .diagnostics
            .iter()
            .any(|diagnostic| diagnostic.code.as_deref() == Some("E0384")),
        "diagnostics must describe the new candidate: {second_handoff:#?}"
    );

    // Reusing the first token is rejected; it was already consumed.
    let reuse = fixture
        .execute(resume_request(
            &work_id,
            &handoff.continuation_token,
            vec![patch("src/lib.rs", DIFFERENT_FAILURE, FIXED_CANDIDATE)],
        ))
        .await;
    assert_eq!(reuse.status, "STALE", "{reuse:#?}");

    // The fixed candidate passes the requested gate.
    let ready = fixture
        .execute(resume_request(
            &work_id,
            &second_handoff.continuation_token,
            vec![patch("src/lib.rs", DIFFERENT_FAILURE, FIXED_CANDIDATE)],
        ))
        .await;
    assert_eq!(ready.status, "READY", "{ready:#?}");
    assert!(!ready.is_error);
    assert_eq!(ready.data.state, "ready");
    assert_eq!(ready.data.revision, 3);
    assert!(
        ready
            .data
            .evidence
            .iter()
            .any(|row| row.gate == "check" && row.status == "PASS" && row.fresh),
        "{ready:#?}"
    );
    assert!(ready.data.handoff.is_none());
    assert_eq!(ready.data.used.candidates, 3);
    assert_eq!(ready.data.used.handoffs, 2);

    // After READY the old token has no active handoff to resume.
    let after_ready = fixture
        .execute(resume_request(
            &work_id,
            &second_handoff.continuation_token,
            vec![patch("src/lib.rs", FIXED_CANDIDATE, FIXED_CANDIDATE)],
        ))
        .await;
    assert_eq!(after_ready.status, "STALE", "{after_ready:#?}");

    let inspected = fixture.execute(inspect_request(&work_id)).await;
    assert_eq!(inspected.status, "INSPECTED");
    assert_eq!(inspected.data.state, "ready");
    assert!(inspected.data.evidence_total >= 2);

    let by_change = fixture
        .execute(WorkRequest {
            change_id: Some(change_id),
            ..inspect_request(&work_id)
        })
        .await;
    assert_eq!(by_change.status, "INSPECTED", "{by_change:#?}");

    assert_unchanged(&fixture, &originals);
    assert!(
        !fixture.root.join("target").exists(),
        "the original workspace target directory must not be created"
    );
}

#[tokio::test]
async fn implement_with_contract_hands_off_with_diagnostics_and_resumes_to_ready() {
    let fixture = Fixture::new("contract", b"pub fn value() -> u8 { 1 }\n", |_| {});
    let mut request = start_request(
        intent(),
        vec![patch(
            "src/lib.rs",
            "pub fn value() -> u8 { 1 }",
            BAD_CANDIDATE,
        )],
        budget(2, 2),
    );
    request.intent.as_mut().expect("intent").template = WorkTemplate::ImplementWithContract;
    let start = fixture.execute(request).await;
    assert_eq!(start.status, "NEEDS_MODEL", "{start:#?}");
    let handoff = start.data.handoff.clone().expect("handoff");
    assert_eq!(handoff.failure_kind, "compile");
    assert!(
        handoff
            .diagnostics
            .iter()
            .any(|diagnostic| diagnostic.code.as_deref() == Some("E0384")),
        "{handoff:#?}"
    );
    let work_id = start.data.work_id.clone().expect("work id");
    let ready = fixture
        .execute(resume_request(
            &work_id,
            &handoff.continuation_token,
            vec![patch(
                "src/lib.rs",
                "let x: u8 = 1; x = 2; x",
                FIXED_CANDIDATE,
            )],
        ))
        .await;
    assert_eq!(ready.status, "READY", "{ready:#?}");
    assert!(
        ready
            .data
            .evidence
            .iter()
            .any(|row| row.gate == "check" && row.status == "PASS" && row.fresh),
        "{ready:#?}"
    );
}

#[tokio::test]
async fn empty_candidate_hands_off_without_compiling() {
    let fixture = Fixture::new("empty", b"pub fn value() -> u8 { 1 }\n", |_| {});
    let originals = original_hashes(&fixture);

    let mut request = start_request(intent(), Vec::new(), budget(2, 2));
    request.intent.as_mut().expect("intent").template = WorkTemplate::ImplementWithContract;
    let start = fixture.execute(request).await;
    assert_eq!(start.status, "NEEDS_MODEL", "{start:#?}");
    assert_eq!(start.data.state, "needs_model");
    assert_eq!(start.data.revision, 0);
    assert_eq!(start.data.used.candidates, 0);
    assert_eq!(start.data.used.compiles, 0);
    let handoff = start.data.handoff.clone().expect("handoff");
    assert_eq!(handoff.failure_kind, "no_candidate");
    assert!(handoff.diagnostics.is_empty());
    let work_id = start.data.work_id.clone().expect("work id");

    let ready = fixture
        .execute(resume_request(
            &work_id,
            &handoff.continuation_token,
            vec![patch(
                "src/lib.rs",
                "pub fn value() -> u8 { 1 }",
                "pub fn value() -> u8 { 2 }",
            )],
        ))
        .await;
    assert_eq!(ready.status, "READY", "{ready:#?}");
    assert_eq!(ready.data.revision, 1);
    assert_eq!(ready.data.used.candidates, 1);
    assert_eq!(ready.data.used.compiles, 1);
    assert_unchanged(&fixture, &originals);
}

#[tokio::test]
async fn adopted_change_with_a_fresh_failure_hands_off_without_recompiling() {
    let fixture = Fixture::new("adopt", b"pub fn value() -> u8 { 1 }\n", |_| {});
    let first = fixture
        .execute(start_request(
            intent(),
            vec![patch(
                "src/lib.rs",
                "pub fn value() -> u8 { 1 }",
                BAD_CANDIDATE,
            )],
            budget(2, 1),
        ))
        .await;
    assert_eq!(first.status, "NEEDS_MODEL", "{first:#?}");
    let change_id = first.data.change_id.clone().expect("change id");

    // A second work adopts the same change; the existing fresh failure is
    // reused as the decision package instead of recompiling.
    let mut adopt = start_request(intent(), Vec::new(), budget(2, 1));
    adopt.change_id = Some(change_id);
    let adopted = fixture.execute(adopt).await;
    assert_eq!(adopted.status, "NEEDS_MODEL", "{adopted:#?}");
    assert_eq!(adopted.data.used.candidates, 0);
    assert_eq!(adopted.data.used.compiles, 0);
    let handoff = adopted.data.handoff.clone().expect("handoff");
    assert_eq!(handoff.failure_kind, "compile");
    assert!(
        handoff
            .diagnostics
            .iter()
            .any(|diagnostic| diagnostic.code.as_deref() == Some("E0384")),
        "{handoff:#?}"
    );
}

#[tokio::test]
async fn candidate_budget_exhaustion_blocks_with_an_explicit_reason() {
    let fixture = Fixture::new("budget", b"pub fn value() -> u8 { 1 }\n", |_| {});
    let start = fixture
        .execute(start_request(
            intent(),
            vec![patch(
                "src/lib.rs",
                "pub fn value() -> u8 { 1 }",
                BAD_CANDIDATE,
            )],
            budget(1, 3),
        ))
        .await;
    assert_eq!(start.status, "BLOCKED", "{start:#?}");
    assert!(start.is_error);
    assert_eq!(start.data.state, "blocked");
    assert!(
        start.data.reason.contains("candidate budget")
            && start.data.reason.contains("maxCandidates"),
        "{:#?}",
        start.data.reason
    );
    assert!(start.data.handoff.is_none());
    assert!(!fixture.state.join("change").join("none").exists());
}

#[tokio::test]
async fn policy_and_missing_tools_fail_closed() {
    let fixture = Fixture::new("policy", b"pub fn value() -> u8 { 1 }\n", |_| {});

    // A candidate outside the declared scope is refused before any change
    // scratch is created.
    let mut scoped = intent();
    scoped.scope_paths = vec!["src/lib.rs".to_owned()];
    let blocked = fixture
        .execute(start_request(
            scoped,
            vec![patch(
                "Cargo.toml",
                "edition = \"2024\"",
                "edition = \"2021\"",
            )],
            budget(2, 1),
        ))
        .await;
    assert_eq!(blocked.status, "BLOCKED", "{blocked:#?}");
    assert!(blocked.is_error);
    assert!(blocked.data.change_id.is_none());
    assert!(
        blocked.data.reason.contains("scopePaths"),
        "{}",
        blocked.data.reason
    );

    // A disabled required tool is a policy block, not a silent plan change.
    let mut config = fixture.config.clone();
    config.tools.docs = false;
    let work = WorkService::new(&config, Some(Arc::clone(&fixture.change)));
    let mut request = start_request(intent(), Vec::new(), budget(2, 1));
    request.constraints.required_tools = vec![WorkTool::Docs];
    let blocked = work
        .execute(
            request,
            &fixture.workspace(),
            CancellationToken::new(),
            None,
        )
        .await;
    assert_eq!(blocked.status, "BLOCKED", "{blocked:#?}");
    assert!(
        blocked.data.reason.contains("'docs'"),
        "{}",
        blocked.data.reason
    );

    // Offline work may not require a network-backed tool.
    let mut request = start_request(intent(), Vec::new(), budget(2, 1));
    request.constraints.offline = true;
    request.constraints.required_tools = vec![WorkTool::Docs];
    let blocked = fixture.execute(request).await;
    assert_eq!(blocked.status, "BLOCKED", "{blocked:#?}");
    assert!(
        blocked.data.reason.contains("offline"),
        "{}",
        blocked.data.reason
    );

    // Without the change tool the executor fails closed instead of inventing a
    // different candidate mechanism.
    let without_change = WorkService::new(&fixture.config, None);
    let blocked = without_change
        .execute(
            start_request(intent(), Vec::new(), budget(1, 0)),
            &fixture.workspace(),
            CancellationToken::new(),
            None,
        )
        .await;
    assert_eq!(blocked.status, "BLOCKED", "{blocked:#?}");
    assert!(
        blocked.data.reason.contains("'change'"),
        "{}",
        blocked.data.reason
    );
}

#[tokio::test]
async fn cancel_propagates_to_an_in_flight_validation() {
    let fixture = Fixture::new("cancel", b"pub fn value() -> u8 { 1 }\n", |_| {});
    let start = fixture
        .execute(start_request(
            intent(),
            vec![patch(
                "src/lib.rs",
                "pub fn value() -> u8 { 1 }",
                BAD_CANDIDATE,
            )],
            budget(3, 2),
        ))
        .await;
    assert_eq!(start.status, "NEEDS_MODEL", "{start:#?}");
    let work_id = start.data.work_id.clone().expect("work id");
    let token = start
        .data
        .handoff
        .clone()
        .expect("handoff")
        .continuation_token;

    let guard = Arc::clone(&fixture.guard);
    let work = Arc::clone(&fixture.work);
    let root = fixture.root.clone();
    let resume_work_id = work_id.clone();
    let resume = tokio::spawn(async move {
        let workspace = workspace_of(&guard, &root);
        work.execute(
            resume_request(
                &resume_work_id,
                &token,
                vec![patch("src/lib.rs", BAD_CANDIDATE, FIXED_CANDIDATE)],
            ),
            &workspace,
            CancellationToken::new(),
            None,
        )
        .await
    });

    // Wait until the record is published as validating, then cancel while the
    // bound Cargo check is still running.
    let workspace = fixture.workspace();
    let mut observed = false;
    for _ in 0..800 {
        let inspected = fixture
            .work
            .execute(
                inspect_request(&work_id),
                &workspace,
                CancellationToken::new(),
                None,
            )
            .await;
        if inspected.status == "INSPECTED" && inspected.data.state == "validating" {
            observed = true;
            break;
        }
        tokio::time::sleep(Duration::from_millis(5)).await;
    }
    assert!(observed, "the validating state was never observed");

    let cancelled = fixture.execute(cancel_request(&work_id)).await;
    assert_eq!(cancelled.status, "CANCELLED", "{cancelled:#?}");
    assert!(!cancelled.is_error);
    assert_eq!(cancelled.data.state, "cancelled");

    let resumed = resume.await.expect("resume task runs");
    assert_eq!(resumed.status, "CANCELLED", "{resumed:#?}");
    assert!(resumed.is_error);
    assert_eq!(resumed.data.state, "cancelled");

    let after = fixture
        .execute(resume_request(
            &work_id,
            "0".repeat(64).as_str(),
            vec![patch("src/lib.rs", FIXED_CANDIDATE, FIXED_CANDIDATE)],
        ))
        .await;
    assert_eq!(after.status, "STALE", "{after:#?}");
}

#[test]
fn work_input_rejects_unknown_fields_and_shell_commands() {
    let valid = serde_json::json!({
        "action": "resume",
        "workId": "wk-1-1-1",
        "continuationToken": "token",
        "patches": [{"file": "src/lib.rs", "oldString": "a", "newString": "b"}],
    });
    assert!(serde_json::from_value::<WorkInput>(valid.clone()).is_ok());

    let mut smuggled = valid.clone();
    smuggled["command"] = serde_json::json!("rm -rf /");
    assert!(
        serde_json::from_value::<WorkInput>(smuggled).is_err(),
        "work has no arbitrary command surface"
    );

    let mut nested = valid;
    nested["patches"][0]["command"] = serde_json::json!("sh -c true");
    assert!(
        serde_json::from_value::<WorkInput>(nested).is_err(),
        "candidate patches have no command surface"
    );
}
