use std::{
    fs,
    path::{Path, PathBuf},
    process::Command,
    sync::{Arc, Mutex},
    time::{Duration, SystemTime, UNIX_EPOCH},
};

use agz_rust_mcp::{
    Config,
    config::GateScope as ConfigGateScope,
    gate::{GateAuthority, GateRequest, GateScopeStrategy, GateStatus, GateTargetId},
    tools::CheckService,
    workspace::RootGuard,
};

struct TestProject {
    root: PathBuf,
    state: PathBuf,
}

impl TestProject {
    fn new(label: &str, source: &str, build_script: Option<&str>) -> Self {
        let stamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map_or(0, |duration| duration.as_nanos());
        let base = fs::canonicalize(std::env::temp_dir())
            .expect("canonical temp directory")
            .join(format!(
                "agz-rust-mcp-check-{label}-{}-{stamp}",
                std::process::id()
            ));
        let root = base.join("workspace");
        let state = base.join("state");
        fs::create_dir_all(root.join("src")).expect("create project source directory");
        fs::create_dir_all(&state).expect("create project state directory");
        fs::write(
            root.join("Cargo.toml"),
            "[package]\nname = \"check-fixture\"\nversion = \"0.1.0\"\nedition = \"2024\"\n\n[workspace]\n",
        )
        .expect("write manifest");
        fs::write(
            root.join("Cargo.lock"),
            "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"check-fixture\"\nversion = \"0.1.0\"\n",
        )
        .expect("write lockfile");
        fs::write(root.join("src/lib.rs"), source).expect("write source");
        if let Some(build_script) = build_script {
            fs::write(root.join("build.rs"), build_script).expect("write build script");
        }
        git(&root, &["init", "--quiet"]);
        git(&root, &["config", "user.email", "check@example.invalid"]);
        git(&root, &["config", "user.name", "Check Fixture"]);
        git(&root, &["add", "."]);
        git(&root, &["commit", "--quiet", "-m", "fixture"]);
        Self { root, state }
    }

    fn service(&self) -> Arc<CheckService> {
        self.service_with_scope(ConfigGateScope::Shadow)
    }

    fn service_with_scope(&self, scope: ConfigGateScope) -> Arc<CheckService> {
        let mut config = Config::defaults_at(&self.root);
        config.gate.debounce_ms = 10;
        config.gate.hard_timeout_ms = 60_000;
        config.gate.cache_dir = self.state.join("cache");
        config.gate.lease_dir = self.state.join("leases");
        config.gate.scope = scope;
        let guard = Arc::new(
            RootGuard::new([self.root.clone()], std::iter::empty()).expect("create root guard"),
        );
        Arc::new(CheckService::new(config, guard))
    }

    #[cfg(unix)]
    fn service_with_cargo(&self, cargo: PathBuf) -> Arc<CheckService> {
        let mut config = Config::defaults_at(&self.root);
        config.gate.debounce_ms = 10;
        config.gate.hard_timeout_ms = 60_000;
        config.gate.cache_dir = self.state.join("cache");
        config.gate.lease_dir = self.state.join("leases");
        config.cargo.path = Some(cargo);
        let guard = Arc::new(
            RootGuard::new([self.root.clone()], std::iter::empty()).expect("create root guard"),
        );
        Arc::new(CheckService::new(config, guard))
    }
}

#[tokio::test]
async fn build_target_checks_linking_for_the_selected_example() {
    use agz_rust_mcp::gate::{CargoTargetSelection, ValidationOptions};
    let project = TestProject::new("build-example", "pub fn value() {}\n", None);
    fs::create_dir(project.root.join("examples")).unwrap();
    fs::write(project.root.join("examples/demo.rs"), "fn main() {}\n").unwrap();
    fs::create_dir(project.root.join(".cargo")).unwrap();
    fs::write(
        project.root.join(".cargo/config.toml"),
        "[build]\nrustflags=[\"-C\",\"linker=agz-missing-linker-for-build-test\"]\n",
    )
    .unwrap();
    let service = project.service();
    let options = ValidationOptions {
        packages: vec!["check-fixture".to_owned()],
        cargo_target: Some(CargoTargetSelection::Example {
            name: "demo".to_owned(),
        }),
        ..Default::default()
    };
    let checked = service
        .run(
            GateRequest::new(&project.root, GateTargetId::Check).with_options(options.clone()),
            None,
            None,
        )
        .await;
    assert_eq!(checked.status, GateStatus::FastPass, "{checked:#?}");
    let built = service
        .run(
            GateRequest::new(&project.root, GateTargetId::Build).with_options(options),
            None,
            None,
        )
        .await;
    assert_eq!(built.status, GateStatus::Fail, "{built:#?}");
    assert_eq!(built.scope.strategy, GateScopeStrategy::Explicit);
    assert!(
        built.steps[0].command.contains(" build ")
            && built.steps[0].command.contains("--example demo")
    );
    service.close().await;
}

#[tokio::test]
async fn explicit_scope_runs_the_selected_test_despite_unrequested_target_failures() {
    use agz_rust_mcp::gate::{CargoTargetSelection, ValidationOptions};
    let project = TestProject::new("explicit-scope", "pub fn value() -> u8 { 7 }\n", None);
    let manifest = project.root.join("Cargo.toml");
    fs::write(
        &manifest,
        fs::read_to_string(&manifest).unwrap().replace(
            "[workspace]",
            "[workspace]\nmembers=[\"sibling\"]\n\n[features]\nchosen=[]",
        ),
    )
    .unwrap();
    fs::create_dir_all(project.root.join("sibling/src")).unwrap();
    fs::write(
        project.root.join("sibling/Cargo.toml"),
        "[package]\nname=\"unrequested\"\nversion=\"0.1.0\"\nedition=\"2024\"\n",
    )
    .unwrap();
    fs::write(
        project.root.join("sibling/src/lib.rs"),
        "compile_error!(\"unrequested package\");\n",
    )
    .unwrap();
    let lock = project.root.join("Cargo.lock");
    fs::write(
        &lock,
        format!(
            "{}\n[[package]]\nname=\"unrequested\"\nversion=\"0.1.0\"\n",
            fs::read_to_string(&lock).unwrap()
        ),
    )
    .unwrap();
    fs::create_dir_all(project.root.join("tests")).unwrap();
    fs::write(project.root.join("tests/focused.rs"),
        "#[cfg(feature=\"chosen\")]\n#[test]\nfn scope_focus() { assert_eq!(check_fixture::value(), 7); }\n").unwrap();
    fs::write(
        project.root.join("tests/unrelated.rs"),
        "compile_error!(\"unrequested target\");\n",
    )
    .unwrap();
    let service = project.service_with_scope(ConfigGateScope::Affected);
    let broad = service
        .run(
            GateRequest::new(&project.root, GateTargetId::Test),
            None,
            None,
        )
        .await;
    assert_eq!(broad.status, GateStatus::Fail, "{broad:#?}");
    for (stage, cargo_target) in [
        (GateTargetId::Check, None),
        (GateTargetId::Clippy, Some(CargoTargetSelection::Lib {})),
    ] {
        let scoped = service
            .run(
                GateRequest::new(&project.root, stage).with_options(ValidationOptions {
                    packages: vec!["check-fixture".into()],
                    cargo_target,
                    ..Default::default()
                }),
                None,
                None,
            )
            .await;
        assert_eq!(scoped.status, GateStatus::FastPass, "{scoped:#?}");
        assert_eq!(scoped.scope.packages, ["check-fixture"]);
        assert!(!scoped.steps[0].command.contains("--workspace"));
    }
    let options = ValidationOptions {
        packages: vec!["check-fixture".into()],
        cargo_target: Some(CargoTargetSelection::Test {
            name: "focused".into(),
        }),
        features: vec!["chosen".into()],
        test_filter: Some("scope_focus".into()),
        ..Default::default()
    };
    let selected = service
        .run(
            GateRequest::new(project.root.join("src"), GateTargetId::Test)
                .with_options(options.clone()),
            None,
            None,
        )
        .await;
    assert_eq!(selected.status, GateStatus::FastPass, "{selected:#?}");
    assert_eq!(selected.authority, GateAuthority::Fast);
    assert_eq!(selected.scope.strategy, GateScopeStrategy::Explicit);
    assert_eq!(selected.scope.packages, ["check-fixture"]);
    assert_eq!(selected.steps[0].evidence.tests_executed, Some(1));
    assert!(selected.steps[0].command.contains("--test focused"));
    assert!(!selected.steps[0].command.contains("--all-targets"));
    assert!(!selected.steps[0].command.contains("--workspace"));
    assert_eq!(selected.profile.as_ref().unwrap().options, options);
    assert_ne!(selected.command_hash, broad.command_hash);
    let broken = service
        .run(
            GateRequest::new(&project.root, GateTargetId::Test).with_options(ValidationOptions {
                cargo_target: Some(CargoTargetSelection::Test {
                    name: "unrelated".into(),
                }),
                ..options
            }),
            None,
            None,
        )
        .await;
    assert_eq!(broken.status, GateStatus::Fail, "{broken:#?}");
    assert_ne!(selected.command_hash, broken.command_hash);
    service.close().await;
}

#[tokio::test]
async fn invalid_explicit_scope_never_falls_back_to_a_workspace_build() {
    use agz_rust_mcp::gate::{CargoTargetSelection, ValidationOptions};
    let project = TestProject::new("invalid-selection", "pub fn value() {}\n", None);
    let service = project.service();
    for (target, package, cargo_target) in [
        (GateTargetId::All, "check-fixture", None),
        (GateTargetId::Fmt, "check-fixture", None),
        (GateTargetId::Check, "missing", None),
        (GateTargetId::Check, "check-*", None),
        (
            GateTargetId::Test,
            "check-fixture",
            Some(CargoTargetSelection::Test {
                name: "missing".into(),
            }),
        ),
        (
            GateTargetId::Doc,
            "check-fixture",
            Some(CargoTargetSelection::Lib {}),
        ),
    ] {
        let evidence = service
            .run(
                GateRequest::new(&project.root, target).with_options(ValidationOptions {
                    packages: vec![package.into()],
                    cargo_target,
                    ..Default::default()
                }),
                None,
                None,
            )
            .await;
        assert_eq!(evidence.status, GateStatus::Inconclusive, "{evidence:#?}");
        assert_eq!(evidence.authority, GateAuthority::None);
        assert!(
            evidence.steps.is_empty(),
            "invalid selection compiled: {evidence:#?}"
        );
    }
    let empty_test = service
        .run(
            GateRequest::new(&project.root, GateTargetId::Test).with_options(ValidationOptions {
                packages: vec!["check-fixture".into()],
                cargo_target: Some(CargoTargetSelection::Lib {}),
                ..Default::default()
            }),
            None,
            None,
        )
        .await;
    assert_eq!(
        empty_test.status,
        GateStatus::Inconclusive,
        "{empty_test:#?}"
    );
    assert_eq!(empty_test.steps[0].evidence.tests_executed, Some(0));
    service.close().await;
}

#[tokio::test]
async fn check_scope_applies_workspace_shadow_and_affected_contracts() {
    let project = TestProject::new("scope", "pub fn value() -> usize { 1 }\n", None);
    let affected = project.service_with_scope(ConfigGateScope::Affected);

    let clean = affected
        .run(
            GateRequest::new(&project.root, GateTargetId::Check),
            None,
            None,
        )
        .await;
    assert_eq!(clean.scope.strategy, GateScopeStrategy::Workspace);
    assert!(
        clean
            .scope
            .widened_because
            .iter()
            .any(|reason| reason.contains("empty"))
    );
    assert!(clean.steps[0].command.contains(&"--workspace".to_owned()));

    fs::write(
        project.root.join("src/lib.rs"),
        "pub fn value() -> usize { 2 }\n",
    )
    .expect("modify owned package source");
    let narrowed = affected
        .run(
            GateRequest::new(&project.root, GateTargetId::Check),
            None,
            None,
        )
        .await;
    assert_eq!(narrowed.scope.strategy, GateScopeStrategy::Affected);
    assert_eq!(narrowed.scope.packages, ["check-fixture"]);
    assert!(narrowed.steps[0].command.contains(&"-p".to_owned()));
    assert!(
        narrowed.steps[0]
            .command
            .contains(&"check-fixture".to_owned())
    );
    affected.close().await;

    let shadow = project.service_with_scope(ConfigGateScope::Shadow);
    let measured = shadow
        .run(
            GateRequest::new(&project.root, GateTargetId::Check),
            None,
            None,
        )
        .await;
    assert_eq!(measured.scope.strategy, GateScopeStrategy::Shadow);
    assert_eq!(measured.scope.packages, ["check-fixture"]);
    assert!(
        measured.steps[0]
            .command
            .contains(&"--workspace".to_owned())
    );
    shadow.close().await;
}

impl Drop for TestProject {
    fn drop(&mut self) {
        if let Some(base) = self.root.parent() {
            let _ = fs::remove_dir_all(base);
        }
    }
}

fn git(root: &Path, arguments: &[&str]) {
    let status = Command::new("git")
        .args(arguments)
        .current_dir(root)
        .status()
        .expect("run git fixture command");
    assert!(status.success(), "git command failed: {arguments:?}");
}

#[tokio::test]
async fn clean_fast_and_full_targets_grant_only_their_declared_authority() {
    let project = TestProject::new("authority", "pub fn answer() -> u32 {\n    42\n}\n", None);
    let service = project.service();

    let fast = service
        .run(
            GateRequest::new(&project.root, GateTargetId::Check),
            None,
            None,
        )
        .await;
    assert_eq!(fast.status, GateStatus::FastPass);
    assert_eq!(fast.authority, GateAuthority::Fast);

    let full = service
        .run(GateRequest::for_all(&project.root), None, None)
        .await;
    assert_eq!(full.status, GateStatus::FullPass, "{full:#?}");
    assert_eq!(full.authority, GateAuthority::Full);
    assert_ne!(fast.job_id, full.job_id);
    service.close().await;
}

#[tokio::test]
async fn broken_source_fails_without_authority_and_keeps_compiler_evidence() {
    let project = TestProject::new(
        "broken",
        "pub fn broken() -> u32 { let value: u32 = \"wrong\"; value }\n",
        None,
    );
    let service = project.service();
    let evidence = service
        .run(
            GateRequest::new(&project.root, GateTargetId::Check),
            None,
            None,
        )
        .await;
    assert_eq!(evidence.status, GateStatus::Fail);
    assert_eq!(evidence.authority, GateAuthority::None);
    assert!(
        evidence
            .steps
            .iter()
            .flat_map(|step| &step.diagnostics)
            .any(|diagnostic| diagnostic.code.as_deref() == Some("E0308"))
    );
    service.close().await;
}

#[tokio::test]
async fn active_identical_requests_singleflight_but_completed_pass_is_not_reused() {
    let project = TestProject::new("singleflight", "pub fn value() -> usize { 1 }\n", None);
    let service = project.service();
    let request = GateRequest::new(&project.root, GateTargetId::Check);
    let (first, second) = tokio::join!(
        service.run(request.clone(), None, None),
        service.run(request.clone(), None, None)
    );
    assert_eq!(first.status, GateStatus::FastPass);
    assert_eq!(first.job_id, second.job_id);

    let later = service.run(request, None, None).await;
    assert_eq!(later.status, GateStatus::FastPass);
    assert_ne!(later.job_id, first.job_id);
    service.close().await;
}

#[tokio::test]
async fn compact_failing_test_keeps_human_panic_evidence() {
    let project = TestProject::new(
        "compact-panic",
        "#[test]\nfn broken() { panic!(\"expected useful panic evidence\"); }\n",
        None,
    );
    let service = project.service();
    let evidence = service
        .run(
            GateRequest::new(&project.root, GateTargetId::Test),
            None,
            None,
        )
        .await;
    assert_eq!(evidence.status, GateStatus::Fail, "{evidence:#?}");
    let step = &evidence.steps[0];
    assert_eq!(step.evidence.tests_executed, Some(1));
    assert!(step.stdout.contains("expected useful panic evidence"));
    assert!(!step.stdout.contains("compiler-artifact"));
    assert!(step.tail.is_empty());
    service.close().await;
}

#[tokio::test]
async fn one_server_checks_real_nested_worktrees_and_member_source_directories() {
    let project = TestProject::new("worktree-paths", "pub fn value() -> u8 { 1 }\n", None);
    let nested = project.root.join(".worktrees/feature ü with spaces");
    git(
        &project.root,
        &[
            "worktree",
            "add",
            "--detach",
            nested
                .strip_prefix(&project.root)
                .unwrap()
                .to_str()
                .unwrap(),
        ],
    );
    // An unrelated parent Cargo workspace must not absorb the nested checkout.
    let service = project.service();
    let main = service
        .run(
            GateRequest::new(&project.root, GateTargetId::Check),
            None,
            None,
        )
        .await;
    assert_eq!(main.status, GateStatus::FastPass, "{main:#?}");
    let worktree = service
        .run(
            GateRequest::new(nested.join("src"), GateTargetId::Check),
            None,
            None,
        )
        .await;
    assert_eq!(worktree.status, GateStatus::FastPass, "{worktree:#?}");
    assert_eq!(worktree.workspace_root, Some(nested.clone()));
    assert_ne!(main.job_id, worktree.job_id);
    assert_ne!(
        main.build.as_ref().unwrap().target_directory,
        worktree.build.as_ref().unwrap().target_directory
    );
    fs::write(
        nested.join("src/lib.rs"),
        "pub fn value() -> u8 { \"broken\" }\n",
    )
    .unwrap();
    let broken = service
        .run(GateRequest::new(&nested, GateTargetId::Check), None, None)
        .await;
    assert_eq!(broken.status, GateStatus::Fail, "{broken:#?}");
    let main_again = service
        .run(
            GateRequest::new(&project.root, GateTargetId::Check),
            None,
            None,
        )
        .await;
    assert_eq!(main_again.status, GateStatus::FastPass, "{main_again:#?}");
    service.close().await;
}

#[tokio::test]
async fn worktree_checks_hash_authorized_shared_dependencies_under_the_parent_root() {
    let project = TestProject::new(
        "worktree-shared",
        "pub fn value() -> u8 { shared::value() }\n",
        None,
    );
    let shared = project.root.join("shared");
    fs::create_dir_all(shared.join("src")).unwrap();
    fs::write(
        shared.join("Cargo.toml"),
        "[package]\nname='shared'\nversion='0.1.0'\nedition='2024'\n[workspace]\n",
    )
    .unwrap();
    fs::write(shared.join("src/lib.rs"), "pub fn value() -> u8 { 1 }\n").unwrap();
    fs::write(project.root.join("Cargo.toml"), format!(
        "[package]\nname='check-fixture'\nversion='0.1.0'\nedition='2024'\n[workspace]\nexclude=['shared']\n[dependencies]\nshared={{path={}}}\n",
        toml::Value::String(shared.to_string_lossy().into_owned())
    )).unwrap();
    fs::write(project.root.join("Cargo.lock"), "version=4\n[[package]]\nname='check-fixture'\nversion='0.1.0'\ndependencies=['shared']\n[[package]]\nname='shared'\nversion='0.1.0'\n").unwrap();
    git(&project.root, &["add", "."]);
    git(
        &project.root,
        &["commit", "--quiet", "-m", "shared dependency fixture"],
    );
    let nested = project.root.join(".worktrees/shared-feature");
    git(
        &project.root,
        &[
            "worktree",
            "add",
            "--detach",
            nested
                .strip_prefix(&project.root)
                .unwrap()
                .to_str()
                .unwrap(),
        ],
    );

    let mut config = Config::defaults_at(&project.root);
    config.server.allow_dependency_roots = vec![shared.clone()];
    config.gate.cache_dir = project.state.join("cache");
    config.gate.lease_dir = project.state.join("leases");
    config.gate.hard_timeout_ms = 60_000;
    config.gate.debounce_ms = 10;
    let guard = Arc::new(RootGuard::new([project.root.clone()], [shared.clone()]).unwrap());
    let service = CheckService::new(config, guard);
    let request = GateRequest::new(nested.join("src"), GateTargetId::Check);
    let first = service.run(request.clone(), None, None).await;
    assert_eq!(first.status, GateStatus::FastPass, "{first:#?}");
    fs::write(shared.join("src/lib.rs"), "pub fn value() -> u8 { 2 }\n").unwrap();
    let changed = service.run(request.clone(), None, None).await;
    assert_eq!(changed.status, GateStatus::FastPass, "{changed:#?}");
    assert_ne!(
        first.input_hash, changed.input_hash,
        "shared dependency changes must enter the worktree input identity"
    );
    fs::write(
        shared.join("src/lib.rs"),
        "pub fn value() -> u8 { \"broken\" }\n",
    )
    .unwrap();
    let broken = service.run(request, None, None).await;
    assert_eq!(broken.status, GateStatus::Fail, "{broken:#?}");
    service.close().await;
}

#[tokio::test]
async fn source_directory_checks_without_git_hash_the_whole_workspace() {
    let project = TestProject::new("no-git-subdir", "pub fn value() -> u8 { 1 }\n", None);
    fs::remove_dir_all(project.root.join(".git")).unwrap();
    fs::write(
        project.root.join("build.rs"),
        "fn main() { println!(\"cargo:rustc-cfg=first\"); }\n",
    )
    .unwrap();
    let service = project.service();
    let request = GateRequest::new(project.root.join("src"), GateTargetId::Check);
    let before = service.run(request.clone(), None, None).await;
    assert_eq!(before.status, GateStatus::FastPass, "{before:#?}");
    fs::write(
        project.root.join("build.rs"),
        "fn main() { println!(\"cargo:rustc-cfg=other\"); }\n",
    )
    .unwrap();
    let after = service.run(request, None, None).await;
    assert_eq!(after.status, GateStatus::FastPass, "{after:#?}");
    assert_ne!(
        before.input_hash, after.input_hash,
        "build.rs outside the requested src directory is a workspace input"
    );
    service.close().await;
}

#[tokio::test]
async fn source_change_after_admission_makes_a_successful_run_stale() {
    let project = TestProject::new(
        "stale",
        "pub fn value() -> usize { 1 }\n",
        Some("fn main() { std::thread::sleep(std::time::Duration::from_millis(400)); }\n"),
    );
    let service = project.service();
    let request = GateRequest::new(&project.root, GateTargetId::Check);
    let running = {
        let service = Arc::clone(&service);
        tokio::spawn(async move { service.run(request, None, None).await })
    };
    for _ in 0..100 {
        if service.active_count() > 0 {
            break;
        }
        tokio::time::sleep(Duration::from_millis(5)).await;
    }
    assert!(service.active_count() > 0, "check job never became active");
    fs::write(
        project.root.join("src/lib.rs"),
        "pub fn value() -> usize { 2 }\n",
    )
    .expect("mutate source during check");

    let evidence = running.await.expect("join check job");
    assert_eq!(evidence.status, GateStatus::Stale);
    assert_eq!(evidence.authority, GateAuthority::None);
    service.close().await;
}

#[tokio::test]
async fn progress_reports_preflight_and_running_stages() {
    let project = TestProject::new("progress", "pub fn value() -> usize { 1 }\n", None);
    let service = project.service();
    let events = Arc::new(Mutex::new(Vec::new()));
    let callback = {
        let events = Arc::clone(&events);
        Arc::new(move |event: agz_rust_mcp::gate::ProgressEvent| {
            events.lock().expect("progress lock").push(event.stage);
        }) as agz_rust_mcp::gate::ProgressCallback
    };

    let evidence = service
        .run(
            GateRequest::new(&project.root, GateTargetId::Check),
            Some(callback),
            None,
        )
        .await;
    assert_eq!(evidence.status, GateStatus::FastPass);
    {
        let events = events.lock().expect("progress lock");
        assert!(events.contains(&agz_rust_mcp::gate::ProgressStage::Accepted));
        assert!(events.contains(&agz_rust_mcp::gate::ProgressStage::Preflight));
        assert!(events.contains(&agz_rust_mcp::gate::ProgressStage::Running));
        assert!(events.contains(&agz_rust_mcp::gate::ProgressStage::Completed));
    }
    service.close().await;
}

#[tokio::test]
async fn cancellation_detaches_the_last_subscriber_and_cleans_the_job() {
    let project = TestProject::new(
        "cancel",
        "pub fn value() -> usize { 1 }\n",
        Some("fn main() { std::thread::sleep(std::time::Duration::from_secs(5)); }\n"),
    );
    let service = project.service();
    let cancellation = tokio_util::sync::CancellationToken::new();
    let running = {
        let service = Arc::clone(&service);
        let root = project.root.clone();
        let cancellation = cancellation.clone();
        tokio::spawn(async move {
            service
                .run(
                    GateRequest::new(root, GateTargetId::Check),
                    None,
                    Some(cancellation),
                )
                .await
        })
    };
    for _ in 0..200 {
        if service.active_count() > 0 {
            break;
        }
        tokio::time::sleep(Duration::from_millis(5)).await;
    }
    assert!(service.active_count() > 0, "check job never became active");
    cancellation.cancel();
    let evidence = running.await.expect("join cancelled check");
    assert_eq!(evidence.status, GateStatus::Cancelled);
    for _ in 0..200 {
        if service.active_count() == 0 {
            break;
        }
        tokio::time::sleep(Duration::from_millis(5)).await;
    }
    assert_eq!(service.active_count(), 0);
    service.close().await;
}

#[cfg(unix)]
#[tokio::test]
async fn preflight_cancellation_does_not_start_cargo() {
    use std::os::unix::fs::PermissionsExt;

    let project = TestProject::new("preflight-cancel", "pub fn value() -> usize { 1 }\n", None);
    let marker = project.state.join("cargo-started");
    let cargo = project.state.join("fake-cargo");
    fs::write(
        &cargo,
        format!("#!/bin/sh\ntouch '{}'\nexit 1\n", marker.display()),
    )
    .expect("write fake cargo");
    let mut permissions = fs::metadata(&cargo)
        .expect("fake cargo metadata")
        .permissions();
    permissions.set_mode(0o755);
    fs::set_permissions(&cargo, permissions).expect("make fake cargo executable");

    let service = project.service_with_cargo(cargo);
    let cancellation = tokio_util::sync::CancellationToken::new();
    cancellation.cancel();
    let evidence = service
        .run(
            GateRequest::new(&project.root, GateTargetId::Check),
            None,
            Some(cancellation),
        )
        .await;

    assert_eq!(evidence.status, GateStatus::Cancelled);
    assert!(
        !marker.exists(),
        "pre-cancelled preflight must not run Cargo"
    );
    service.close().await;
}

#[cfg(unix)]
#[tokio::test]
async fn selected_child_replacement_cannot_run_the_check_target() {
    use std::sync::atomic::{AtomicBool, Ordering};

    let project = TestProject::new(
        "selected-child-replacement",
        "pub fn value() -> usize { 1 }\n",
        None,
    );
    let configured_parent = project
        .root
        .parent()
        .expect("workspace has a configured parent")
        .to_owned();
    let original = configured_parent.join("workspace-original");
    let marker = project.state.join("replacement-check-ran");

    let mut config = Config::defaults_at(&project.root);
    config.gate.debounce_ms = 10;
    config.gate.hard_timeout_ms = 60_000;
    config.gate.cache_dir = project.state.join("cache");
    config.gate.lease_dir = project.state.join("leases");
    config.gate.scope = ConfigGateScope::Workspace;
    let guard = Arc::new(
        RootGuard::new([configured_parent], std::iter::empty())
            .expect("authorize configured parent"),
    );
    let service = Arc::new(CheckService::new(config, guard));

    let swapped = Arc::new(AtomicBool::new(false));
    let callback = {
        let root = project.root.clone();
        let original = original.clone();
        let marker = marker.clone();
        let swapped = Arc::clone(&swapped);
        Arc::new(move |event: agz_rust_mcp::gate::ProgressEvent| {
            if event.stage != agz_rust_mcp::gate::ProgressStage::Running
                || swapped.swap(true, Ordering::SeqCst)
            {
                return;
            }
            fs::rename(&root, &original).expect("rename selected child workspace");
            fs::create_dir_all(root.join("src")).expect("create replacement source directory");
            fs::write(
                root.join("Cargo.toml"),
                "[package]\nname = \"check-fixture\"\nversion = \"0.1.0\"\nedition = \"2024\"\nbuild = \"build.rs\"\n\n[workspace]\n",
            )
            .expect("write replacement manifest");
            fs::write(
                root.join("Cargo.lock"),
                "version = 4\n\n[[package]]\nname = \"check-fixture\"\nversion = \"0.1.0\"\n",
            )
            .expect("write replacement lockfile");
            fs::write(root.join("src/lib.rs"), "pub fn replacement() {}\n")
                .expect("write replacement source");
            fs::write(
                root.join("build.rs"),
                format!(
                    "fn main() {{ std::fs::write({:?}, b\"replacement check ran\").unwrap(); }}\n",
                    marker.to_string_lossy()
                ),
            )
            .expect("write replacement build script");
        }) as agz_rust_mcp::gate::ProgressCallback
    };

    let evidence = service
        .run(
            GateRequest::new(&project.root, GateTargetId::Check),
            Some(callback),
            None,
        )
        .await;

    assert!(
        swapped.load(Ordering::SeqCst),
        "replacement hook did not run"
    );
    assert_eq!(evidence.authority, GateAuthority::None, "{evidence:#?}");
    assert!(!marker.exists(), "replacement Cargo target must not run");
    assert!(original.join("Cargo.toml").is_file());
    service.close().await;
}

#[tokio::test]
async fn different_root_epochs_do_not_join_an_active_job() {
    let project = TestProject::new(
        "root-epoch",
        "pub fn value() -> usize { 1 }\n",
        Some("fn main() { std::thread::sleep(std::time::Duration::from_millis(500)); }\n"),
    );
    let service = project.service();
    let first = {
        let service = Arc::clone(&service);
        let root = project.root.clone();
        tokio::spawn(async move {
            service
                .run(
                    GateRequest::new(root, GateTargetId::Check).with_root_epoch(1),
                    None,
                    None,
                )
                .await
        })
    };
    for _ in 0..200 {
        if service.active_count() > 0 {
            break;
        }
        tokio::time::sleep(Duration::from_millis(5)).await;
    }
    assert!(service.active_count() > 0, "check job never became active");
    let second = {
        let service = Arc::clone(&service);
        let root = project.root.clone();
        tokio::spawn(async move {
            service
                .run(
                    GateRequest::new(root, GateTargetId::Check).with_root_epoch(2),
                    None,
                    None,
                )
                .await
        })
    };
    let first = first.await.expect("join first epoch check");
    let second = second.await.expect("join second epoch check");
    assert_eq!(first.status, GateStatus::FastPass, "{first:#?}");
    assert_eq!(second.status, GateStatus::FastPass, "{second:#?}");
    assert_ne!(first.job_id, second.job_id);
    service.close().await;
}

#[tokio::test]
async fn different_validation_profiles_do_not_supersede_unchanged_source() {
    let project = TestProject::new(
        "concurrent-profiles",
        "#[test] fn exact_test() { assert_eq!(2 + 2, 4); }\n",
        None,
    );
    let ready = project.state.join("ready");
    let release = project.state.join("release");
    fs::write(project.root.join("build.rs"), format!(
        "fn main() {{ std::fs::write({ready:?}, b\"ready\").unwrap(); let start = std::time::Instant::now(); while !std::path::Path::new({release:?}).exists() {{ assert!(start.elapsed() < std::time::Duration::from_secs(45)); std::thread::sleep(std::time::Duration::from_millis(10)); }} }}\n"
    )).expect("write bounded build barrier");
    let service = project.service();
    let first = {
        let service = Arc::clone(&service);
        let root = project.root.clone();
        tokio::spawn(async move {
            service
                .run(GateRequest::new(root, GateTargetId::Check), None, None)
                .await
        })
    };
    let started = tokio::time::timeout(Duration::from_secs(30), async {
        while !ready.exists() {
            tokio::time::sleep(Duration::from_millis(10)).await;
        }
    })
    .await;
    if started.is_err() {
        fs::write(&release, b"release").unwrap();
        service.close().await;
        panic!("first Cargo build never reached the barrier");
    }
    let second = {
        let service = Arc::clone(&service);
        let root = project.root.clone();
        tokio::spawn(async move {
            service
                .run(GateRequest::new(root, GateTargetId::Test), None, None)
                .await
        })
    };
    let submitted = tokio::time::timeout(Duration::from_secs(20), async {
        while service.active_count() < 2 && !first.is_finished() {
            tokio::time::sleep(Duration::from_millis(10)).await;
        }
    })
    .await;
    fs::write(&release, b"release").expect("release queued profiles");
    let first = first.await.expect("first profile");
    let second = second.await.expect("second profile");
    service.close().await;
    submitted.expect("second profile reaches scheduler");
    assert_eq!(first.status, GateStatus::FastPass, "{first:#?}");
    assert_eq!(second.status, GateStatus::FastPass, "{second:#?}");
    assert_eq!(second.steps[0].evidence.tests_executed, Some(1));
    assert_ne!(first.command_hash, second.command_hash);
    assert_ne!(first.input_hash, second.input_hash);
    assert_ne!(first.job_id, second.job_id);
}

#[tokio::test]
async fn a_new_input_supersedes_the_older_active_job() {
    let project = TestProject::new("supersede", "pub fn value() -> usize { 1 }\n", None);
    let ready = project.state.join("build-ready");
    let release = project.state.join("build-release");
    // Synchronize with actual Cargo execution, not preflight wall-clock speed.
    fs::write(project.root.join("build.rs"), format!(
        "fn main() {{ std::fs::write({:?}, b\"ready\").unwrap(); let start = std::time::Instant::now(); while !std::path::Path::new({:?}).exists() {{ assert!(start.elapsed() < std::time::Duration::from_secs(45), \"test barrier expired\"); std::thread::sleep(std::time::Duration::from_millis(10)); }} }}\n",
        ready, release,
    )).expect("write bounded build barrier");
    let service = project.service();
    let first = {
        let service = Arc::clone(&service);
        let root = project.root.clone();
        tokio::spawn(async move {
            service
                .run(GateRequest::new(root, GateTargetId::Check), None, None)
                .await
        })
    };
    let started = tokio::time::timeout(Duration::from_secs(30), async {
        while !ready.exists() {
            tokio::time::sleep(Duration::from_millis(10)).await;
        }
    })
    .await;
    if started.is_err() {
        fs::write(&release, b"release").expect("release failed fixture");
        service.close().await;
        panic!("first Cargo build never reached the synchronization barrier");
    }
    fs::write(
        project.root.join("src/lib.rs"),
        "pub fn value() -> usize { 2 }\n",
    )
    .expect("write new source generation");
    let second = {
        let service = Arc::clone(&service);
        let root = project.root.clone();
        tokio::spawn(async move {
            service
                .run(GateRequest::new(root, GateTargetId::Check), None, None)
                .await
        })
    };
    let first = tokio::time::timeout(Duration::from_secs(20), first).await;
    fs::write(&release, b"release").expect("release replacement build");
    let second = tokio::time::timeout(Duration::from_secs(30), second).await;
    service.close().await;
    let first = first
        .expect("older check superseded within its bound")
        .expect("join older check");
    let second = second
        .expect("replacement check completed within its bound")
        .expect("join replacement");
    assert_eq!(first.status, GateStatus::Superseded, "{first:#?}");
    assert_eq!(second.status, GateStatus::FastPass, "{second:#?}");
    assert_ne!(first.input_hash, second.input_hash);
}

#[tokio::test]
async fn streamed_error_has_request_timing_and_bounded_source_context() {
    use agz_rust_mcp::gate::ValidationOptions;
    let project = TestProject::new(
        "context",
        "pub fn broken() -> u32 { let value: u32 = \"wrong\"; value }\n",
        None,
    );
    let service = project.service();
    let evidence = service
        .run(
            GateRequest::new(&project.root, GateTargetId::Check).with_options(ValidationOptions {
                context: true,
                ..Default::default()
            }),
            None,
            None,
        )
        .await;
    assert_eq!(evidence.status, GateStatus::Fail, "{evidence:#?}");
    assert!(evidence.first_diagnostic_ms.is_some());
    assert!(evidence.first_diagnostic_ms.unwrap() <= evidence.response_ms);
    let step = &evidence.steps[0];
    assert!(step.evidence.diagnostic_records > 0);
    assert!(step.first_diagnostic_ms.is_some());
    assert!(
        step.contexts.iter().any(|c| c.excerpt.contains("wrong")
            && c.source_hash.is_some()
            && c.freshness == "input-identity-matched"),
        "{:?}",
        step.contexts
    );
    assert!(step.contexts.iter().all(|c| c.untrusted_data));
    service.close().await;
}

#[tokio::test]
async fn explicit_features_are_executed_and_distinguish_validation_profiles() {
    use agz_rust_mcp::gate::ValidationOptions;
    let project = TestProject::new(
        "features",
        "#[cfg(feature = \"broken\")]\ncompile_error!(\"selected feature fails\");\npub fn value() {}\n",
        None,
    );
    let manifest = project.root.join("Cargo.toml");
    fs::write(
        &manifest,
        format!(
            "{}\n[features]\ndefault = []\nbroken = []\n",
            fs::read_to_string(&manifest).unwrap()
        ),
    )
    .unwrap();
    let service = project.service_with_scope(ConfigGateScope::Affected);
    let good = service
        .run(
            GateRequest::new(&project.root, GateTargetId::Check),
            None,
            None,
        )
        .await;
    let options = ValidationOptions {
        features: vec!["broken".into()],
        ..Default::default()
    };
    let bad = service
        .run(
            GateRequest::new(&project.root, GateTargetId::Check).with_options(options.clone()),
            None,
            None,
        )
        .await;
    assert_eq!(good.status, GateStatus::FastPass, "{good:#?}");
    assert_eq!(bad.status, GateStatus::Fail, "{bad:#?}");
    assert_eq!(bad.scope.strategy, GateScopeStrategy::Workspace);
    assert_eq!(bad.profile.as_ref().unwrap().options, options);
    assert_ne!(good.command_hash, bad.command_hash);
    service.close().await;
}

#[tokio::test]
async fn clippy_and_test_scope_widens_for_build_scripts() {
    let project = TestProject::new("scope2", "pub fn value() {}\n", None);
    let service = project.service_with_scope(ConfigGateScope::Affected);
    fs::write(
        project.root.join("src/lib.rs"),
        "pub fn value() {}\n#[test] fn works() { value(); }\n",
    )
    .unwrap();
    for target in [GateTargetId::Clippy, GateTargetId::Test] {
        let narrow = service
            .run(GateRequest::new(&project.root, target), None, None)
            .await;
        assert_eq!(narrow.status, GateStatus::FastPass, "{narrow:#?}");
        assert_eq!(narrow.scope.strategy, GateScopeStrategy::Affected);
    }
    fs::write(project.root.join("build.rs"), "fn main() {}\n").unwrap();
    let broad = service
        .run(
            GateRequest::new(&project.root, GateTargetId::Clippy),
            None,
            None,
        )
        .await;
    assert_eq!(
        broad.scope.strategy,
        GateScopeStrategy::Workspace,
        "{broad:#?}"
    );
    service.close().await;
}

#[tokio::test]
#[ignore = "requires checksum-verified cargo-nextest 0.9.143 on PATH"]
async fn real_nextest_executes_test_filters_and_keeps_doctest_stage() {
    use agz_rust_mcp::gate::{TestRunner, ValidationOptions};
    let project = TestProject::new(
        "nx",
        "pub fn value() {}\n#[test]\nfn works() {}\n#[test]\nfn fails() { panic!(\"expected failure\"); }\n",
        None,
    );
    let service = project.service();
    let options = ValidationOptions {
        runner: TestRunner::Nextest,
        test_filter: Some("works".into()),
        ..Default::default()
    };
    let good = service
        .run(
            GateRequest::new(&project.root, GateTargetId::Test).with_options(options.clone()),
            None,
            None,
        )
        .await;
    assert_eq!(good.status, GateStatus::FastPass, "{good:#?}");
    let bad = service
        .run(
            GateRequest::new(&project.root, GateTargetId::Test).with_options(ValidationOptions {
                test_filter: Some("fails".into()),
                ..options.clone()
            }),
            None,
            None,
        )
        .await;
    assert_eq!(bad.status, GateStatus::Fail, "{bad:#?}");
    let none = service
        .run(
            GateRequest::new(&project.root, GateTargetId::Test).with_options(ValidationOptions {
                test_filter: Some("no_such_test".into()),
                ..options
            }),
            None,
            None,
        )
        .await;
    assert_eq!(none.status, GateStatus::Fail, "{none:#?}");
    // A compile-failing doctest cannot be skipped by an otherwise passing nextest run.
    fs::write(project.root.join("src/lib.rs"),"/// ```\n/// let value: u32 = \"wrong\";\n/// ```\npub fn value() {}\n#[test]\nfn works() {}\n").unwrap();
    let all = service
        .run(
            GateRequest::for_all(&project.root).with_options(ValidationOptions {
                runner: TestRunner::Nextest,
                ..Default::default()
            }),
            None,
            None,
        )
        .await;
    assert_eq!(all.status, GateStatus::Fail, "{all:#?}");
    assert!(
        all.steps
            .iter()
            .any(|s| s.target == GateTargetId::Doc && s.exit_code != 0),
        "{all:#?}"
    );
    service.close().await;
}

#[cfg(unix)]
#[tokio::test]
#[ignore = "requires explicit RUSTC_WRAPPER pointing to checksum-verified sccache 0.17.0"]
async fn real_sccache_compiles_and_cleans_the_owned_server() {
    #[cfg(target_os = "linux")]
    let before = live_sccache_pids();
    use agz_rust_mcp::gate::ValidationOptions;
    let project = TestProject::new("sc", "pub fn value() {}\n", None);
    let service = project.service();
    let evidence = service
        .run(
            GateRequest::new(&project.root, GateTargetId::Check).with_options(ValidationOptions {
                sccache: true,
                ..Default::default()
            }),
            None,
            None,
        )
        .await;
    assert_eq!(evidence.status, GateStatus::FastPass, "{evidence:#?}");
    assert!(evidence.warnings.iter().any(|s| s.contains("client-side")));
    let entries = fs::read_dir(project.state.join("leases")).unwrap();
    assert!(
        !entries
            .filter_map(Result::ok)
            .any(|e| e.file_name().to_string_lossy().starts_with("sc-"))
    );
    service.close().await;
    #[cfg(target_os = "linux")]
    tokio::time::timeout(Duration::from_secs(5), async {
        while !live_sccache_pids().is_subset(&before) {
            tokio::time::sleep(Duration::from_millis(25)).await;
        }
    })
    .await
    .expect("sccache left a newly started live process outside its owned session");
}

#[tokio::test]
async fn filtered_cargo_with_no_executed_tests_cannot_grant_a_pass() {
    use agz_rust_mcp::gate::ValidationOptions;
    let project = TestProject::new("empty-filter", "#[test] fn works() {}\n", None);
    let service = project.service();
    for (filter, expected) in [
        ("works", GateStatus::FastPass),
        ("does_not_exist", GateStatus::Inconclusive),
    ] {
        let result = service
            .run(
                GateRequest::new(&project.root, GateTargetId::Test).with_options(
                    ValidationOptions {
                        test_filter: Some(filter.into()),
                        ..Default::default()
                    },
                ),
                None,
                None,
            )
            .await;
        assert_eq!(result.status, expected, "{result:#?}");
    }
    service.close().await;
}

#[cfg(target_os = "linux")]
fn live_sccache_pids() -> std::collections::BTreeSet<u32> {
    let wrapper =
        fs::canonicalize(std::env::var_os("RUSTC_WRAPPER").expect("explicit sccache wrapper"))
            .expect("canonical sccache binary");
    fs::read_dir("/proc")
        .expect("read process table")
        .filter_map(Result::ok)
        .filter_map(|entry| {
            let pid = entry.file_name().to_str()?.parse::<u32>().ok()?;
            if fs::read_link(entry.path().join("exe")).ok()? != wrapper {
                return None;
            }
            let stat = fs::read_to_string(entry.path().join("stat")).ok()?;
            let (_, fields) = stat.rsplit_once(')')?;
            (fields.split_whitespace().next() != Some("Z")).then_some(pid)
        })
        .collect()
}

#[cfg(unix)]
const COMPILER_PROBE: &str = r#"
fn main() {
    let rustc = std::env::var_os("RUSTC").expect("cargo sets RUSTC for build scripts");
    let output = std::process::Command::new(rustc)
        .arg("-vV")
        .output()
        .expect("probe rustc");
    let out_dir = std::env::var_os("OUT_DIR").expect("cargo sets OUT_DIR");
    std::fs::write(std::path::Path::new(&out_dir).join("compiler-probe.txt"), output.stdout)
        .expect("write compiler probe");
    println!("cargo:rerun-if-changed=build.rs");
}
"#;

#[cfg(unix)]
fn rustup_home() -> PathBuf {
    std::env::var_os("RUSTUP_HOME")
        .map(PathBuf::from)
        .unwrap_or_else(|| {
            PathBuf::from(std::env::var_os("HOME").unwrap_or_default()).join(".rustup")
        })
}

#[cfg(unix)]
fn installed_toolchain(prefix: &str) -> Option<String> {
    let mut names = fs::read_dir(rustup_home().join("toolchains"))
        .ok()?
        .filter_map(Result::ok)
        .filter_map(|entry| entry.file_name().to_str().map(str::to_owned))
        .filter(|name| name.starts_with(prefix))
        .collect::<Vec<_>>();
    names.sort();
    names.into_iter().next()
}

#[cfg(unix)]
fn ambient_toolchain_excluding(prefix: &str) -> Option<String> {
    let home = rustup_home();
    let default = fs::read_to_string(home.join("settings.toml"))
        .ok()
        .and_then(|text| {
            text.lines().find_map(|line| {
                let (key, value) = line.split_once('=')?;
                (key.trim() == "default_toolchain")
                    .then(|| value.trim().trim_matches('"').to_owned())
            })
        });
    if let Some(default) = default.filter(|name| !name.starts_with(prefix)) {
        return Some(default);
    }
    let mut names = fs::read_dir(home.join("toolchains"))
        .ok()?
        .filter_map(Result::ok)
        .filter_map(|entry| entry.file_name().to_str().map(str::to_owned))
        .filter(|name| !name.starts_with(prefix))
        .collect::<Vec<_>>();
    names.sort();
    names.into_iter().next()
}

#[cfg(unix)]
fn find_file(root: &Path, name: &str) -> Option<PathBuf> {
    let mut pending = vec![(root.to_owned(), 0_usize)];
    while let Some((directory, depth)) = pending.pop() {
        if depth > 12 {
            continue;
        }
        let entries = match fs::read_dir(&directory) {
            Ok(entries) => entries,
            Err(_) => continue,
        };
        for entry in entries.filter_map(Result::ok) {
            let path = entry.path();
            let Ok(file_type) = entry.file_type() else {
                continue;
            };
            if file_type.is_dir() {
                if path.file_name().and_then(|value| value.to_str()) == Some(".git") {
                    continue;
                }
                pending.push((path, depth + 1));
            } else if file_type.is_file()
                && path.file_name().and_then(|value| value.to_str()) == Some(name)
            {
                return Some(path);
            }
        }
    }
    None
}

/// Runs the child with a different ambient toolchain. A gate that trusts the
/// ambient compiler instead of the requested toolchain fails here.
#[cfg(unix)]
#[tokio::test]
async fn toolchain_request_runs_the_selected_compiler_for_direct_and_shim_selection() {
    const MARKER: &str = "AGZ_CHECK_TOOLCHAIN_CHILD";
    if std::env::var_os(MARKER).is_none() {
        let Some(ambient) = ambient_toolchain_excluding("1.88") else {
            eprintln!("skipping toolchain-binding test: no differing toolchain installed");
            return;
        };
        let executable = std::env::current_exe().expect("current test binary");
        let status = Command::new(&executable)
            .args([
                "--exact",
                "toolchain_request_runs_the_selected_compiler_for_direct_and_shim_selection",
                "--test-threads=1",
                "--nocapture",
            ])
            .env(MARKER, "1")
            .env("RUSTUP_TOOLCHAIN", ambient)
            .env_remove("RUSTC")
            .status()
            .expect("spawn toolchain-binding child test");
        assert!(status.success(), "toolchain-binding child test failed");
        return;
    }
    if installed_toolchain("1.88").is_none() {
        eprintln!("skipping toolchain-binding test: no 1.88 toolchain installed");
        return;
    }
    let project = TestProject::new(
        "toolchain-binding",
        "pub fn value() -> usize { 1 }\n",
        Some(COMPILER_PROBE),
    );
    let service = project.service();
    let outcome = service
        .run(
            GateRequest::new(&project.root, GateTargetId::Check)
                .with_toolchain(installed_toolchain("1.88")),
            None,
            None,
        )
        .await;
    assert_eq!(outcome.status, GateStatus::FastPass, "{outcome:#?}");
    let selected = installed_toolchain("1.88").expect("selected toolchain");
    let command = &outcome.steps[0].command;
    if command.contains(&format!("toolchains/{selected}")) {
        assert!(
            !command.contains(&format!("+{selected}")),
            "direct toolchain cargo must not need a shim selector: {command}"
        );
    } else {
        assert!(
            command.contains(&format!("+{selected}")),
            "shim fallback must pass +toolchain: {command}"
        );
    }
    let probe = find_file(
        project.root.parent().expect("fixture base directory"),
        "compiler-probe.txt",
    )
    .expect("build script compiler probe");
    let observed = fs::read_to_string(&probe).expect("read compiler probe");
    let expected = Command::new(
        rustup_home()
            .join("toolchains")
            .join(&selected)
            .join("bin")
            .join("rustc"),
    )
    .arg("-vV")
    .output()
    .expect("probe selected toolchain rustc");
    assert_eq!(
        observed,
        String::from_utf8(expected.stdout).expect("rustc -vV is UTF-8"),
        "the gate must run {selected}, not an ambient compiler"
    );
    assert!(
        observed.starts_with("rustc 1.88"),
        "unexpected compiler probe: {observed}"
    );
    service.close().await;
}
