//! Handler/MCP integration for `explain`: typed status mapping, source
//! binding (`sha256`/`revision`/`rootEpoch`), `executed` flags,
//! `untrustedData`, and request cancellation.

use std::{
    env, fs,
    path::PathBuf,
    process::Command,
    sync::atomic::{AtomicU64, Ordering},
    time::{Duration, SystemTime, UNIX_EPOCH},
};

use agz_rust_mcp::{Config, RustCoderServer, config::WorkspaceCode};
use anyhow::{Context, Result};
use rmcp::{
    ServiceExt,
    model::{
        CallToolRequestParams, CallToolResponse, CallToolResult, ClientCapabilities, ClientInfo,
        Implementation,
    },
};
use serde_json::{Value, json};

static NEXT_STATE_ID: AtomicU64 = AtomicU64::new(0);

struct TestWorkspace {
    base: PathBuf,
    root: PathBuf,
    state: PathBuf,
}

impl TestWorkspace {
    fn new(label: &str, files: &[(&str, &str)]) -> Self {
        let stamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("system clock is after the Unix epoch")
            .as_nanos();
        let sequence = NEXT_STATE_ID.fetch_add(1, Ordering::Relaxed);
        let base = fs::canonicalize(std::env::temp_dir())
            .expect("canonical temp directory")
            .join(format!(
                "agz-rust-mcp-explain-protocol-{label}-{}-{stamp}-{sequence}",
                std::process::id()
            ));
        let root = base.join("workspace");
        let state = base.join("state");
        fs::create_dir_all(&root).expect("create workspace directory");
        fs::create_dir_all(&state).expect("create state directory");
        for (relative, contents) in files {
            let path = root.join(relative);
            if let Some(parent) = path.parent() {
                fs::create_dir_all(parent).expect("create fixture parent directory");
            }
            fs::write(&path, contents).expect("write fixture file");
        }
        for args in [
            vec!["init", "--quiet"],
            vec!["config", "user.email", "explain@example.invalid"],
            vec!["config", "user.name", "Explain Protocol Fixture"],
            vec!["add", "."],
            vec!["commit", "--quiet", "-m", "fixture"],
        ] {
            let status = Command::new("git")
                .args(&args)
                .current_dir(&root)
                .status()
                .expect("run git");
            assert!(status.success(), "git {args:?} failed");
        }
        Self { base, root, state }
    }

    fn clean(label: &str) -> Self {
        Self::new(
            label,
            &[
                (
                    "Cargo.toml",
                    "[package]\nname = \"explain-protocol\"\nversion = \"0.1.0\"\nedition = \"2024\"\n\n[features]\nextra = []\n\n[workspace]\n",
                ),
                (
                    "Cargo.lock",
                    "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"explain-protocol\"\nversion = \"0.1.0\"\n",
                ),
                (
                    "src/lib.rs",
                    "#[cfg(feature = \"extra\")]\npub fn gated() {}\n\npub fn value() -> u8 {\n    1\n}\n",
                ),
            ],
        )
    }

    fn config(&self, lsp: bool) -> Config {
        let mut config = Config::defaults_at(&self.root);
        config.gate.debounce_ms = 10;
        config.gate.cache_dir = self.state.join("gate");
        config.gate.lease_dir = self.state.join("leases");
        config.docs.cache_dir = self.state.join("docs");
        config.telemetry.enabled = false;
        config.telemetry.path = self.state.join("activity.jsonl");
        config.tools.lsp = lsp;
        config
    }
}

impl Drop for TestWorkspace {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.base);
    }
}

fn spawn_server(config: Config) -> (tokio::io::DuplexStream, tokio::task::JoinHandle<Result<()>>) {
    let (server_transport, client_transport) = tokio::io::duplex(1 << 20);
    let task = tokio::spawn(async move {
        let service = Box::pin(RustCoderServer::new(config)?.serve(server_transport)).await?;
        service.waiting().await?;
        Ok(())
    });
    (client_transport, task)
}

fn client_info() -> ClientInfo {
    ClientInfo::new(
        ClientCapabilities::default(),
        Implementation::new("agz-rust-mcp-explain-test", "0.1.0"),
    )
}

fn compile_ra_fixture(name: &str) -> PathBuf {
    let source =
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../tests/fixtures/lsp/semantic_ra.rs");
    let output_dir = fs::canonicalize(env::temp_dir())
        .expect("canonical temp directory")
        .join(format!(
            "agz-rust-mcp-explain-protocol-fixture-{}",
            std::process::id()
        ));
    fs::create_dir_all(&output_dir).expect("create fixture output directory");
    let output = output_dir.join(format!("{name}{}", env::consts::EXE_SUFFIX));
    let rustc = env::var_os("RUSTC")
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("rustc"));
    let status = Command::new(rustc)
        .args(["--edition=2024"])
        .arg(source)
        .arg("-o")
        .arg(&output)
        .status()
        .expect("compile semantic fixture");
    assert!(status.success(), "semantic fixture compilation failed");
    output
}

fn explain_params(arguments: Value) -> CallToolRequestParams {
    let arguments = arguments
        .as_object()
        .cloned()
        .expect("explain arguments must be an object");
    CallToolRequestParams::new("explain").with_arguments(arguments)
}

fn structured(result: &CallToolResult) -> &Value {
    result
        .structured_content
        .as_ref()
        .expect("explain returns structured content")
}

fn explain_result(response: CallToolResponse) -> CallToolResult {
    match response {
        CallToolResponse::Complete(result) => result,
        other => panic!("explain must return a complete response, got {other:?}"),
    }
}

#[tokio::test]
async fn explain_cfg_binds_the_anchor_and_reports_metadata_only() -> Result<()> {
    let workspace = TestWorkspace::clean("cfg");
    let (transport, server_task) = spawn_server(workspace.config(false));
    let client = client_info().serve(transport).await?;

    let result = explain_result(
        client
            .call_tool_once(explain_params(json!({
                "action": "cfg",
                "anchor": {"path": "src/lib.rs", "line": 2},
                "configuration": {"features": ["extra"]}
            })))
            .await?,
    );
    let data = structured(&result);
    assert_eq!(result.is_error, Some(false));
    assert_eq!(data["status"], "OK");
    assert_eq!(data["data"]["action"], "cfg");
    assert_eq!(data["data"]["anchorLine"], 2);
    assert_eq!(data["data"]["configuration"]["executed"], false);
    assert_eq!(data["data"]["configuration"]["features"], json!(["extra"]));
    assert_eq!(data["data"]["configuration"]["allFeatures"], false);

    let sha = data["data"]["source"]["sha256"]
        .as_str()
        .context("missing source sha256")?;
    assert_eq!(sha.len(), 64);
    let revision = data["data"]["source"]["revision"]
        .as_str()
        .context("missing git revision")?;
    assert!(
        (7..=64).contains(&revision.len()) && revision.bytes().all(|byte| byte.is_ascii_hexdigit()),
        "unexpected revision: {revision}"
    );
    assert!(data["data"]["source"]["rootEpoch"].as_u64().unwrap_or(0) >= 1);

    let fragments = data["data"]["fragments"]
        .as_array()
        .context("missing fragments")?;
    assert!(fragments.iter().any(|fragment| {
        fragment["kind"] == "cfgCondition"
            && fragment["provenance"] == "inferred"
            && fragment["detail"]
                .as_str()
                .is_some_and(|detail| detail.contains("enables"))
    }));
    assert!(fragments.iter().any(|fragment| {
        fragment["kind"] == "featureState" && fragment["provenance"] == "observedCompiler"
    }));

    assert_eq!(data["untrustedData"], true);
    assert!(data["warnings"].as_array().is_some_and(|warnings| {
        warnings.iter().any(|warning| {
            warning
                .as_str()
                .is_some_and(|warning| warning.contains("UNTRUSTED DATA"))
        })
    }));

    client.cancel().await?;
    server_task.await??;
    Ok(())
}

#[tokio::test]
async fn explain_maps_unsupported_and_not_found_statuses() -> Result<()> {
    let workspace = TestWorkspace::clean("status");
    let (transport, server_task) = spawn_server(workspace.config(false));
    let client = client_info().serve(transport).await?;

    // No analyzer is configured, so macro provenance has no advisory fallback.
    let result = explain_result(
        client
            .call_tool_once(explain_params(json!({
                "action": "macro",
                "anchor": {"path": "src/lib.rs"}
            })))
            .await?,
    );
    let data = structured(&result);
    assert_eq!(data["status"], "UNSUPPORTED_CAPABILITY");
    assert_eq!(result.is_error, Some(false));
    assert!(!data["data"]["unsupported"].as_array().unwrap().is_empty());
    assert_eq!(data["data"]["configuration"]["executed"], true);

    // The trait action ran a compiler check with no matching diagnostic.
    let result = explain_result(
        client
            .call_tool_once(explain_params(json!({
                "action": "trait",
                "anchor": {"path": "src/lib.rs"}
            })))
            .await?,
    );
    let data = structured(&result);
    assert_eq!(data["status"], "NOT_FOUND");
    assert_eq!(data["data"]["configuration"]["executed"], true);
    assert_eq!(data["data"]["diagnosticsMatched"], 0);

    client.cancel().await?;
    server_task.await??;
    Ok(())
}

#[tokio::test]
async fn explain_unreadable_anchor_is_unavailable() -> Result<()> {
    let workspace = TestWorkspace::clean("unreadable");
    let (transport, server_task) = spawn_server(workspace.config(false));
    let client = client_info().serve(transport).await?;

    for action in ["cfg", "macro"] {
        let result = explain_result(
            client
                .call_tool_once(explain_params(json!({
                    "action": action,
                    "anchor": {"path": "src/missing.rs"}
                })))
                .await?,
        );
        let data = structured(&result);
        assert_eq!(data["status"], "UNAVAILABLE", "{action}");
        assert_eq!(result.is_error, Some(true), "{action}");
        assert_eq!(data["data"]["source"]["sha256"], "", "{action}");
        assert!(
            data["data"]["reason"]
                .as_str()
                .is_some_and(|reason| reason.contains("could not be read")),
            "{action}: {:?}",
            data["data"]["reason"]
        );
    }

    client.cancel().await?;
    server_task.await??;
    Ok(())
}

#[tokio::test]
async fn explain_trait_conflict_keeps_compiler_authority() -> Result<()> {
    let analyzer = compile_ra_fixture("semantic-ra-explain-conflict-expand-macro");
    let workspace = TestWorkspace::clean("conflict");
    let mut config = workspace.config(true);
    config.rust_analyzer.workspace_code = WorkspaceCode::Allow;
    config.rust_analyzer.path = Some(analyzer);
    let (transport, server_task) = spawn_server(config);
    let client = client_info().serve(transport).await?;

    let result = explain_result(
        client
            .call_tool_once(explain_params(json!({
                "action": "trait",
                "anchor": {"path": "src/lib.rs", "line": 4}
            })))
            .await?,
    );
    let data = structured(&result);
    assert_eq!(data["status"], "OK");
    let fragments = data["data"]["fragments"]
        .as_array()
        .context("missing fragments")?;
    assert!(fragments.iter().any(|fragment| {
        fragment["kind"] == "failedBound" && fragment["provenance"] == "advisoryAnalyzer"
    }));

    let conflicts = data["data"]["conflicts"]
        .as_array()
        .context("missing conflicts")?;
    assert_eq!(conflicts.len(), 1, "{conflicts:?}");
    assert!(
        conflicts[0]["compiler"]
            .as_str()
            .is_some_and(|text| text.contains("no failed trait obligation"))
    );
    assert!(
        conflicts[0]["analyzer"]
            .as_str()
            .is_some_and(|text| text.contains("failed obligation"))
    );

    // Advisory obligation text is not reused as macro expansion bytes.
    assert_eq!(data["data"]["bounds"]["expansionBytes"], 0);

    client.cancel().await?;
    server_task.await??;
    Ok(())
}

#[tokio::test]
async fn explain_request_cancellation_reports_cancelled() -> Result<()> {
    let pid_file = "build-script.pid";
    let workspace = TestWorkspace::new(
        "cancel",
        &[
            (
                "Cargo.toml",
                "[package]\nname = \"explain-protocol-cancel\"\nversion = \"0.1.0\"\nedition = \"2024\"\n\n[workspace]\n",
            ),
            (
                "Cargo.lock",
                "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"explain-protocol-cancel\"\nversion = \"0.1.0\"\n",
            ),
            ("src/lib.rs", "pub fn value() -> u8 {\n    1\n}\n"),
            (
                "build.rs",
                "fn main() {\n    std::fs::write(\"build-script.pid\", std::process::id().to_string()).unwrap();\n    std::thread::sleep(std::time::Duration::from_secs(10));\n}\n",
            ),
        ],
    );
    let (transport, server_task) = spawn_server(workspace.config(false));
    let client = client_info().serve(transport).await?;

    let peer = client.peer().clone();
    let call = tokio::spawn(async move {
        peer.call_tool_once(explain_params(json!({
            "action": "trait",
            "anchor": {"path": "src/lib.rs"}
        })))
        .await
    });

    let pid_path = workspace.root.join(pid_file);
    for _ in 0..500 {
        if pid_path.is_file() {
            break;
        }
        tokio::time::sleep(Duration::from_millis(10)).await;
    }
    assert!(pid_path.is_file(), "slow Cargo build did not start");

    // Root-epoch cancellation flows through the same request bridge as MCP
    // request cancellation, so the tool must report its typed CANCELLED state.
    client.peer().notify_roots_list_changed().await?;
    let response = call.await??;
    let CallToolResponse::Complete(result) = response else {
        anyhow::bail!("explain must complete after cancellation");
    };
    let data = structured(&result);
    assert_eq!(data["status"], "CANCELLED");
    assert_eq!(result.is_error, Some(true));

    client.cancel().await?;
    server_task.await??;
    Ok(())
}
