use std::{
    fs,
    path::{Path, PathBuf},
    process::Command,
    sync::Arc,
    time::{SystemTime, UNIX_EPOCH},
};

use agz_rust_mcp::{
    Config,
    config::VerifyConfig,
    gate::{ProgressCallback, ProgressEvent, ProgressStage},
    tools::{
        CheckService, RequiredConfigurations, VerifyAction, VerifyBudget, VerifyOutcome,
        VerifyRequest, VerifyRunner, VerifyService, VerifyStage,
    },
    workspace::{ClientRoots, RootGuard},
};

struct TestProject {
    root: PathBuf,
    state: PathBuf,
}

impl TestProject {
    fn new(label: &str, extra_manifest: &str, source: &str) -> Self {
        Self::build(label, None, extra_manifest, source, None)
    }

    fn with_rust_version(label: &str, version: &str, extra_manifest: &str, source: &str) -> Self {
        Self::build(label, Some(version), extra_manifest, source, None)
    }

    fn with_build_script(
        label: &str,
        extra_manifest: &str,
        source: &str,
        build_script: &str,
    ) -> Self {
        Self::build(label, None, extra_manifest, source, Some(build_script))
    }

    #[cfg(unix)]
    fn with_rust_version_and_build_script(
        label: &str,
        version: &str,
        extra_manifest: &str,
        source: &str,
        build_script: &str,
    ) -> Self {
        Self::build(
            label,
            Some(version),
            extra_manifest,
            source,
            Some(build_script),
        )
    }

    fn build(
        label: &str,
        rust_version: Option<&str>,
        extra_manifest: &str,
        source: &str,
        build_script: Option<&str>,
    ) -> Self {
        let stamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map_or(0, |duration| duration.as_nanos());
        let base = fs::canonicalize(std::env::temp_dir())
            .expect("canonical temp directory")
            .join(format!(
                "agz-rust-mcp-verify-{label}-{}-{stamp}",
                std::process::id()
            ));
        let root = base.join("workspace");
        let state = base.join("state");
        fs::create_dir_all(root.join("src")).expect("create project source directory");
        fs::create_dir_all(&state).expect("create project state directory");
        let rust_version = rust_version.map_or_else(String::new, |version| {
            format!("rust-version = \"{version}\"\n")
        });
        fs::write(
            root.join("Cargo.toml"),
            format!(
                "[package]\nname = \"verify-fixture\"\nversion = \"0.1.0\"\nedition = \"2024\"\n\
                 {rust_version}\n[workspace]\n{extra_manifest}\n"
            ),
        )
        .expect("write manifest");
        fs::write(
            root.join("Cargo.lock"),
            "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"verify-fixture\"\nversion = \"0.1.0\"\n",
        )
        .expect("write lockfile");
        fs::write(root.join("src/lib.rs"), source).expect("write source");
        if let Some(build_script) = build_script {
            fs::write(root.join("build.rs"), build_script).expect("write build script");
        }
        git(&root, &["init", "--quiet"]);
        git(&root, &["config", "user.email", "verify@example.invalid"]);
        git(&root, &["config", "user.name", "Verify Fixture"]);
        git(&root, &["add", "."]);
        git(&root, &["commit", "--quiet", "-m", "fixture"]);
        Self { root, state }
    }

    fn service(&self) -> Arc<VerifyService> {
        let mut config = Config::defaults_at(&self.root);
        config.gate.debounce_ms = 10;
        config.gate.hard_timeout_ms = 120_000;
        config.gate.cache_dir = self.state.join("cache");
        config.gate.lease_dir = self.state.join("leases");
        let guard = Arc::new(
            RootGuard::new([self.root.clone()], std::iter::empty()).expect("create root guard"),
        );
        let check = Arc::new(CheckService::new(config, guard));
        Arc::new(VerifyService::new(
            check,
            VerifyConfig {
                max_cells: 8,
                max_wall_ms: 300_000,
                max_tests: 8,
                repeats: 2,
            },
        ))
    }
}

impl Drop for TestProject {
    fn drop(&mut self) {
        if let Some(base) = self.root.parent() {
            let _ = fs::remove_dir_all(base);
        }
    }
}

fn git(root: &Path, arguments: &[&str]) {
    let status = Command::new("git")
        .args(arguments)
        .current_dir(root)
        .status()
        .expect("run git fixture command");
    assert!(status.success(), "git command failed: {arguments:?}");
}

/// Build script that records the compiler Cargo actually asks it to use.
#[cfg(unix)]
const COMPILER_PROBE: &str = r#"
fn main() {
    let rustc = std::env::var_os("RUSTC").expect("cargo sets RUSTC for build scripts");
    let output = std::process::Command::new(rustc)
        .arg("-vV")
        .output()
        .expect("probe rustc");
    let out_dir = std::env::var_os("OUT_DIR").expect("cargo sets OUT_DIR");
    std::fs::write(std::path::Path::new(&out_dir).join("compiler-probe.txt"), output.stdout)
        .expect("write compiler probe");
    println!("cargo:rerun-if-changed=build.rs");
}
"#;

#[cfg(unix)]
fn rustup_home() -> PathBuf {
    std::env::var_os("RUSTUP_HOME")
        .map(PathBuf::from)
        .unwrap_or_else(|| {
            PathBuf::from(std::env::var_os("HOME").unwrap_or_default()).join(".rustup")
        })
}

#[cfg(unix)]
fn installed_toolchain(prefix: &str) -> Option<String> {
    let mut names = fs::read_dir(rustup_home().join("toolchains"))
        .ok()?
        .filter_map(Result::ok)
        .filter_map(|entry| entry.file_name().to_str().map(str::to_owned))
        .filter(|name| name.starts_with(prefix))
        .collect::<Vec<_>>();
    names.sort();
    names.into_iter().next()
}

/// Pick an installed toolchain with a different version than `prefix`, so an
/// ambient compiler that ignores the requested toolchain is observable.
#[cfg(unix)]
fn ambient_toolchain_excluding(prefix: &str) -> Option<String> {
    let home = rustup_home();
    let default = fs::read_to_string(home.join("settings.toml"))
        .ok()
        .and_then(|text| {
            text.lines().find_map(|line| {
                let (key, value) = line.split_once('=')?;
                (key.trim() == "default_toolchain")
                    .then(|| value.trim().trim_matches('"').to_owned())
            })
        });
    if let Some(default) = default.filter(|name| !name.starts_with(prefix)) {
        return Some(default);
    }
    let mut names = fs::read_dir(home.join("toolchains"))
        .ok()?
        .filter_map(Result::ok)
        .filter_map(|entry| entry.file_name().to_str().map(str::to_owned))
        .filter(|name| !name.starts_with(prefix))
        .collect::<Vec<_>>();
    names.sort();
    names.into_iter().next()
}

#[cfg(unix)]
fn find_file(root: &Path, name: &str) -> Option<PathBuf> {
    let mut pending = vec![(root.to_owned(), 0_usize)];
    while let Some((directory, depth)) = pending.pop() {
        if depth > 12 {
            continue;
        }
        let entries = match fs::read_dir(&directory) {
            Ok(entries) => entries,
            Err(_) => continue,
        };
        for entry in entries.filter_map(Result::ok) {
            let path = entry.path();
            let Ok(file_type) = entry.file_type() else {
                continue;
            };
            if file_type.is_dir() {
                if path.file_name().and_then(|value| value.to_str()) == Some(".git") {
                    continue;
                }
                pending.push((path, depth + 1));
            } else if file_type.is_file()
                && path.file_name().and_then(|value| value.to_str()) == Some(name)
            {
                return Some(path);
            }
        }
    }
    None
}

fn request(
    action: VerifyAction,
    root: &Path,
    required: RequiredConfigurations,
    budget: VerifyBudget,
) -> VerifyRequest {
    VerifyRequest {
        action,
        directory: Some(root.to_path_buf()),
        client_roots: ClientRoots::unsupported(),
        root_epoch: 0,
        change_id: Some("change-42".to_owned()),
        required,
        budget,
        test_configuration: agz_rust_mcp::gate::ValidationOptions::default(),
        test_mappings: Vec::new(),
        changed_paths: Vec::new(),
        semantic_references: Vec::new(),
        test_patch: None,
        behavior_contract: None,
        workspace: None,
    }
}

fn check_only_budget(cells: u32) -> VerifyBudget {
    VerifyBudget {
        max_cells: Some(cells),
        max_wall_ms: Some(240_000),
        max_tests: None,
        repeats: None,
    }
}

fn cell<'a>(outcome: &'a VerifyOutcome, id_part: &str) -> &'a agz_rust_mcp::tools::CellOutcome {
    outcome
        .cells
        .iter()
        .find(|cell| cell.id.contains(id_part))
        .unwrap_or_else(|| panic!("missing cell {id_part}: {:#?}", outcome.cells))
}

#[tokio::test]
async fn default_pass_and_no_default_failure_are_distinct_and_bound() {
    let project = TestProject::new(
        "default",
        "[features]\ndefault = [\"ok\"]\nok = []",
        "#[cfg(feature = \"ok\")]\npub fn value() -> usize { 1 }\n\n\
         #[cfg(not(feature = \"ok\"))]\ncompile_error!(\"no-default configuration is broken\");\n",
    );
    let service = project.service();
    let required = RequiredConfigurations {
        include_default: true,
        include_no_default: true,
        include_policy: false,
        stages: vec![VerifyStage::Check],
        ..RequiredConfigurations::default()
    };
    let outcome = service
        .execute(
            request(
                VerifyAction::MatrixRun,
                &project.root,
                required.clone(),
                check_only_budget(4),
            ),
            None,
            None,
        )
        .await;

    assert_eq!(outcome.cells.len(), 2, "{outcome:#?}");
    let default = cell(&outcome, "default--host--default--check");
    let no_default = cell(&outcome, "no-default--host--default--check");
    assert_eq!(default.status, "PASS", "{default:#?}");
    assert_eq!(no_default.status, "FAIL", "{no_default:#?}");
    assert_eq!(outcome.status, "FULL_REQUESTED_MATRIX", "{outcome:#?}");
    assert!(outcome.complete);
    assert!(!outcome.all_pass);
    assert_eq!(outcome.completed_cell_ids.len(), 2);
    assert!(outcome.missing_cell_ids.is_empty());
    assert_eq!(outcome.change_id.as_deref(), Some("change-42"));
    assert!(!outcome.exhaustive);
    assert_eq!(outcome.resolver, "edition-default (3)", "{outcome:#?}");
    assert!(outcome.feature_unification.contains("resolver"));

    // Evidence binds each result to source/lock/config/toolchain.
    assert!(
        default
            .input_hash
            .as_deref()
            .is_some_and(|hash| !hash.is_empty())
    );
    assert_ne!(default.input_hash, no_default.input_hash);
    assert_ne!(default.command_hash, no_default.command_hash);
    assert!(
        default
            .command_hash
            .as_deref()
            .is_some_and(|hash| !hash.is_empty())
            && default
                .environment_hash
                .as_deref()
                .is_some_and(|hash| !hash.is_empty())
    );
    assert!(default.job_id.as_deref().is_some_and(|id| !id.is_empty()));
    assert!(no_default.duration_ms > 0);
    assert!(outcome.package_scope == "workspace");
    assert_eq!(default.strategy.as_deref(), Some("shadow"));
    assert_eq!(no_default.strategy.as_deref(), Some("workspace"));

    // A plan reports the same cells without executing them.
    let plan = service
        .execute(
            request(
                VerifyAction::MatrixPlan,
                &project.root,
                required,
                check_only_budget(4),
            ),
            None,
            None,
        )
        .await;
    assert_eq!(plan.status, "PLANNED");
    assert!(plan.cells.iter().all(|cell| cell.status == "PLANNED"));
    assert!(plan.cells.iter().all(|cell| cell.job_id.is_none()));
}

#[tokio::test]
async fn unsupported_feature_combinations_are_typed_and_never_green() {
    let project = TestProject::new(
        "unsupported",
        "[features]\ndefault = []\ntls-native = []\ntls-rustls = []\n\n\
         [workspace.metadata.agz-verify]\nfeature-groups = [[\"tls-native\", \"tls-rustls\"], [\"missing-feature\"]]\n\
         mutually-exclusive-features = [[\"tls-native\", \"tls-rustls\"]]",
        "pub fn value() -> usize { 1 }\n",
    );
    let service = project.service();
    let required = RequiredConfigurations {
        include_default: false,
        include_policy: true,
        stages: vec![VerifyStage::Check],
        ..RequiredConfigurations::default()
    };
    let plan = service
        .execute(
            request(
                VerifyAction::MatrixPlan,
                &project.root,
                required.clone(),
                check_only_budget(8),
            ),
            None,
            None,
        )
        .await;
    assert_eq!(plan.status, "PLANNED", "{plan:#?}");
    assert!(plan.cells.is_empty(), "{:#?}", plan.cells);
    assert_eq!(plan.skipped.len(), 2);
    assert!(
        plan.skipped
            .iter()
            .all(|cell| cell.status == "UNSUPPORTED_CONFIGURATION")
    );
    assert!(
        plan.skipped
            .iter()
            .any(|cell| cell.reason.contains("mutually exclusive"))
    );
    assert!(
        plan.skipped
            .iter()
            .any(|cell| cell.reason.contains("not declared"))
    );
    assert!(plan.policy_source.contains("agz-verify"));

    let run = service
        .execute(
            request(
                VerifyAction::MatrixRun,
                &project.root,
                required,
                check_only_budget(8),
            ),
            None,
            None,
        )
        .await;
    assert_eq!(run.status, "PARTIAL", "{run:#?}");
    assert!(!run.complete);
    assert!(!run.all_pass);
    assert!(run.cells.is_empty());
    assert!(run.completed_cell_ids.is_empty());
    assert_eq!(run.missing_cell_ids.len(), 2);
}

#[tokio::test]
async fn budget_exhaustion_separates_completed_and_skipped_cells() {
    let project = TestProject::new(
        "budget",
        "[features]\ndefault = []\na = []\nb = []\n\n\
         [workspace.metadata.agz-verify]\nfeature-groups = [[\"a\"], [\"b\"]]",
        "pub fn value() -> usize { 1 }\n",
    );
    let service = project.service();
    let required = RequiredConfigurations {
        include_default: true,
        include_no_default: true,
        include_policy: true,
        stages: vec![VerifyStage::Check],
        ..RequiredConfigurations::default()
    };
    let outcome = service
        .execute(
            request(
                VerifyAction::MatrixRun,
                &project.root,
                required,
                check_only_budget(1),
            ),
            None,
            None,
        )
        .await;
    assert_eq!(outcome.status, "PARTIAL", "{outcome:#?}");
    assert!(!outcome.complete);
    assert_eq!(outcome.budget.executed, 1);
    assert_eq!(outcome.cells.len(), 1);
    assert_eq!(outcome.cells[0].status, "PASS");
    assert_eq!(outcome.completed_cell_ids.len(), 1);
    assert!(
        outcome
            .skipped
            .iter()
            .all(|cell| cell.status == "SKIPPED_BUDGET")
    );
    assert_eq!(outcome.skipped.len(), 3);
    assert_eq!(outcome.missing_cell_ids.len(), 3);
    // Skipped cells are never green and never appear as completed.
    assert!(
        outcome
            .completed_cell_ids
            .iter()
            .all(|id| !outcome.missing_cell_ids.contains(id))
    );
}

#[tokio::test]
async fn not_installed_target_is_reported_without_download() {
    let project = TestProject::new("target", "", "pub fn value() -> usize { 1 }\n");
    let service = project.service();
    let target = "thumbv7em-none-eabi";
    let required = RequiredConfigurations {
        include_default: false,
        include_policy: false,
        targets: vec![target.to_owned()],
        stages: vec![VerifyStage::Check],
        ..RequiredConfigurations::default()
    };
    let outcome = service
        .execute(
            request(
                VerifyAction::MatrixPlan,
                &project.root,
                required.clone(),
                check_only_budget(4),
            ),
            None,
            None,
        )
        .await;
    let installed = outcome.installed_targets.iter().any(|item| item == target);
    if installed {
        let planned = cell(&outcome, target);
        assert_eq!(planned.stage, "check");
        assert!(planned.compile_only);
    } else {
        assert!(
            outcome
                .cells
                .iter()
                .all(|cell| cell.target_triple.as_deref() != Some(target)),
            "an uninstalled target must never be planned as a runnable cell: {outcome:#?}"
        );
        assert!(
            outcome
                .skipped
                .iter()
                .any(|cell| { cell.status == "NOT_INSTALLED" && cell.reason.contains(target) })
        );
        assert!(!outcome.installed_targets.iter().any(|item| item == target));
    }
    let run = service
        .execute(
            request(
                VerifyAction::MatrixRun,
                &project.root,
                required,
                check_only_budget(4),
            ),
            None,
            None,
        )
        .await;
    if installed {
        assert!(!run.status.is_empty());
    } else {
        assert_eq!(run.status, "PARTIAL", "{run:#?}");
        assert!(!run.complete);
        assert!(
            run.skipped
                .iter()
                .any(|cell| cell.status == "NOT_INSTALLED")
        );
        assert!(
            run.cells
                .iter()
                .all(|cell| cell.target_triple.as_deref() != Some(target))
        );
    }
}

#[tokio::test]
async fn installed_cross_target_is_compile_only_and_never_claims_tests() {
    let project = TestProject::new("cross", "", "pub fn value() -> usize { 1 }\n");
    let service = project.service();
    let target = "x86_64-pc-windows-gnu";
    let required = RequiredConfigurations {
        include_default: false,
        include_policy: false,
        targets: vec![target.to_owned()],
        stages: vec![VerifyStage::Check, VerifyStage::Test],
        ..RequiredConfigurations::default()
    };
    let plan = service
        .execute(
            request(
                VerifyAction::MatrixPlan,
                &project.root,
                required.clone(),
                check_only_budget(4),
            ),
            None,
            None,
        )
        .await;
    let target_installed = plan.installed_targets.iter().any(|item| item == target);
    if target_installed {
        let cross = cell(&plan, target);
        assert_eq!(cross.stage, "check");
        assert!(cross.compile_only);
        assert!(!cross.test_execution_claimed);
    } else {
        assert!(
            plan.skipped
                .iter()
                .any(|cell| cell.status == "NOT_INSTALLED" && cell.reason.contains(target))
        );
    }
    // A requested non-check stage on a foreign target is explicitly unsupported.
    assert!(plan.skipped.iter().any(|cell| {
        cell.status == "UNSUPPORTED_CONFIGURATION" && cell.reason.contains("compile-only")
    }));
    if target_installed {
        let run = service
            .execute(
                request(
                    VerifyAction::MatrixRun,
                    &project.root,
                    required,
                    check_only_budget(4),
                ),
                None,
                None,
            )
            .await;
        for cell in &run.cells {
            if cell.target_triple.is_some() {
                assert_eq!(cell.stage, "check");
                assert!(cell.compile_only);
            }
            assert!(!cell.test_execution_claimed);
        }
        assert_eq!(
            run.cells
                .iter()
                .filter(|cell| cell.target_triple.is_some())
                .count(),
            1
        );
    }
}

#[tokio::test]
async fn completed_pass_is_not_reused_for_a_new_explicit_run() {
    let project = TestProject::new("reuse", "", "pub fn value() -> usize { 1 }\n");
    let service = project.service();
    let required = RequiredConfigurations {
        include_default: true,
        include_policy: false,
        stages: vec![VerifyStage::Check],
        ..RequiredConfigurations::default()
    };
    let first = service
        .execute(
            request(
                VerifyAction::MatrixRun,
                &project.root,
                required.clone(),
                check_only_budget(2),
            ),
            None,
            None,
        )
        .await;
    let second = service
        .execute(
            request(
                VerifyAction::MatrixRun,
                &project.root,
                required,
                check_only_budget(2),
            ),
            None,
            None,
        )
        .await;
    let first_cell = cell(&first, "default--host--default--check");
    let second_cell = cell(&second, "default--host--default--check");
    assert_eq!(first_cell.status, "PASS", "{first:#?}");
    assert_eq!(second_cell.status, "PASS", "{second:#?}");
    assert_ne!(first_cell.job_id, second_cell.job_id);
}

#[tokio::test]
async fn msrv_cell_uses_the_installed_toolchain_when_present() {
    let project =
        TestProject::with_rust_version("msrv", "1.88", "", "pub fn value() -> usize { 1 }\n");
    let service = project.service();
    let required = RequiredConfigurations {
        include_default: false,
        include_policy: false,
        include_msrv: true,
        stages: vec![VerifyStage::Check],
        ..RequiredConfigurations::default()
    };
    let plan = service
        .execute(
            request(
                VerifyAction::MatrixPlan,
                &project.root,
                required.clone(),
                check_only_budget(2),
            ),
            None,
            None,
        )
        .await;
    let msrv_cell = plan.cells.iter().find(|cell| cell.toolchain.is_some());
    match msrv_cell {
        Some(cell) => {
            assert!(
                cell.msrv
                    .as_deref()
                    .is_some_and(|msrv| msrv.starts_with("1.88")),
                "{cell:#?}"
            );
            let toolchain = cell.toolchain.clone().expect("toolchain");
            let outcome = service
                .execute(
                    request(
                        VerifyAction::MatrixRun,
                        &project.root,
                        required,
                        check_only_budget(2),
                    ),
                    None,
                    None,
                )
                .await;
            let executed = outcome
                .cells
                .iter()
                .find(|cell| cell.toolchain.as_deref() == Some(toolchain.as_str()))
                .expect("msrv cell");
            assert_eq!(executed.status, "PASS", "{executed:#?}");
            assert_eq!(executed.gate_status.as_deref(), Some("FAST_PASS"));
            assert!(executed.command_hash.is_some());
        }
        None => {
            assert!(plan.skipped.iter().any(|cell| {
                cell.status == "NOT_INSTALLED" || cell.status == "UNSUPPORTED_CONFIGURATION"
            }));
        }
    }
}

#[tokio::test]
async fn nextest_missing_runner_is_typed_as_runner_unavailable() {
    let project = TestProject::new(
        "runner",
        "",
        "pub fn value() -> usize { 1 }\n#[test]\nfn works() { value(); }\n",
    );
    let service = project.service();
    let required = RequiredConfigurations {
        include_default: true,
        include_policy: false,
        stages: vec![VerifyStage::Test],
        runner: VerifyRunner::Nextest,
        ..RequiredConfigurations::default()
    };
    let outcome = service
        .execute(
            request(
                VerifyAction::MatrixRun,
                &project.root,
                required,
                check_only_budget(2),
            ),
            None,
            None,
        )
        .await;
    let cell = &outcome.cells[0];
    assert_eq!(cell.runner, "nextest");
    // Either nextest is available and may pass/fail, or the runner is typed
    // unavailable; the cell is never silently treated as a green check.
    assert!(
        matches!(
            cell.status.as_str(),
            "RUNNER_UNAVAILABLE" | "PASS" | "FAIL" | "INCONCLUSIVE"
        ),
        "{cell:#?}"
    );
    if cell.status == "RUNNER_UNAVAILABLE" {
        assert!(!cell.test_execution_claimed);
        assert!(!outcome.complete);
    }
}

#[tokio::test]
async fn wall_budget_expiry_skips_the_running_cell_and_the_rest() {
    let project = TestProject::with_build_script(
        "wall-budget",
        "",
        "pub fn value() -> usize { 1 }\n",
        "fn main() { std::thread::sleep(std::time::Duration::from_secs(5)); }\n",
    );
    let service = project.service();
    let required = RequiredConfigurations {
        include_default: true,
        include_policy: false,
        stages: vec![VerifyStage::Check],
        ..RequiredConfigurations::default()
    };
    let outcome = service
        .execute(
            request(
                VerifyAction::MatrixRun,
                &project.root,
                required,
                VerifyBudget {
                    max_cells: Some(4),
                    max_wall_ms: Some(1_000),
                    ..VerifyBudget::default()
                },
            ),
            None,
            None,
        )
        .await;
    assert_eq!(outcome.status, "PARTIAL", "{outcome:#?}");
    assert!(!outcome.complete);
    assert_eq!(outcome.budget.executed, 1);
    assert_eq!(outcome.cells.len(), 1, "{outcome:#?}");
    assert_eq!(outcome.cells[0].status, "SKIPPED_BUDGET", "{outcome:#?}");
    assert!(outcome.cells[0].duration_ms < 5_000, "{outcome:#?}");
    assert_eq!(outcome.missing_cell_ids.len(), 1);
    assert!(outcome.completed_cell_ids.is_empty());
}

#[tokio::test]
async fn pre_cancelled_request_is_typed_without_starting_cells() {
    let project = TestProject::new("pre-cancel", "", "pub fn value() -> usize { 1 }\n");
    let service = project.service();
    let cancellation = tokio_util::sync::CancellationToken::new();
    cancellation.cancel();
    let outcome = service
        .execute(
            request(
                VerifyAction::MatrixRun,
                &project.root,
                RequiredConfigurations {
                    include_policy: false,
                    stages: vec![VerifyStage::Check],
                    ..RequiredConfigurations::default()
                },
                check_only_budget(2),
            ),
            None,
            Some(cancellation),
        )
        .await;
    assert_eq!(outcome.status, "CANCELLED", "{outcome:#?}");
    assert!(!outcome.complete);
    assert!(!outcome.all_pass);
    assert!(outcome.cells.is_empty(), "{outcome:#?}");
    assert!(outcome.completed_cell_ids.is_empty());
}

#[tokio::test]
async fn mid_run_cancellation_marks_running_and_skipped_cells() {
    let project = TestProject::new("cancel", "", "pub fn value() -> usize { 1 }\n");
    let service = project.service();
    let cancellation = tokio_util::sync::CancellationToken::new();
    let trigger = cancellation.clone();
    let cancel_on_first_run: ProgressCallback = std::sync::Arc::new(move |event: ProgressEvent| {
        if event.stage == ProgressStage::Running {
            trigger.cancel();
        }
    });
    let required = RequiredConfigurations {
        include_default: true,
        include_no_default: true,
        include_policy: false,
        stages: vec![VerifyStage::Check],
        ..RequiredConfigurations::default()
    };
    let outcome = service
        .execute(
            request(
                VerifyAction::MatrixRun,
                &project.root,
                required,
                check_only_budget(4),
            ),
            Some(cancel_on_first_run),
            Some(cancellation),
        )
        .await;
    assert_eq!(outcome.status, "PARTIAL", "{outcome:#?}");
    assert_eq!(outcome.budget.executed, 1);
    assert_eq!(outcome.cells.len(), 2, "{outcome:#?}");
    assert_eq!(outcome.cells[0].status, "CANCELLED", "{outcome:#?}");
    assert_eq!(outcome.cells[1].status, "SKIPPED_CANCELLED", "{outcome:#?}");
    assert!(outcome.completed_cell_ids.is_empty());
}

#[tokio::test]
async fn msrv_toolchain_missing_is_a_separate_not_installed_branch() {
    let project = TestProject::with_rust_version(
        "msrv-missing",
        "1.200.0",
        "",
        "pub fn value() -> usize { 1 }\n",
    );
    let service = project.service();
    let required = RequiredConfigurations {
        include_default: false,
        include_policy: false,
        include_msrv: true,
        stages: vec![VerifyStage::Check],
        ..RequiredConfigurations::default()
    };
    let plan = service
        .execute(
            request(
                VerifyAction::MatrixPlan,
                &project.root,
                required.clone(),
                check_only_budget(2),
            ),
            None,
            None,
        )
        .await;
    assert!(plan.cells.is_empty(), "{plan:#?}");
    assert!(plan.skipped.iter().any(|cell| {
        cell.id == "msrv" && cell.status == "NOT_INSTALLED" && cell.reason.contains("1.200.0")
    }));

    let run = service
        .execute(
            request(
                VerifyAction::MatrixRun,
                &project.root,
                required,
                check_only_budget(2),
            ),
            None,
            None,
        )
        .await;
    assert_eq!(run.status, "PARTIAL", "{run:#?}");
    assert!(!run.complete);
    assert!(run.cells.iter().all(|cell| cell.toolchain.is_none()));
}

/// The child process observes a different ambient toolchain, so an MSRV cell
/// that does not actually bind the selected compiler fails instead of silently
/// compiling with the ambient rustc.
#[cfg(unix)]
#[tokio::test]
async fn msrv_cell_actually_invokes_the_selected_compiler() {
    const MARKER: &str = "AGZ_VERIFY_MSRV_CHILD";
    if std::env::var_os(MARKER).is_none() {
        let Some(ambient) = ambient_toolchain_excluding("1.88") else {
            eprintln!("skipping compiler-binding test: no differing toolchain installed");
            return;
        };
        let executable = std::env::current_exe().expect("current test binary");
        let status = Command::new(&executable)
            .args([
                "--exact",
                "msrv_cell_actually_invokes_the_selected_compiler",
                "--test-threads=1",
                "--nocapture",
            ])
            .env(MARKER, "1")
            .env("RUSTUP_TOOLCHAIN", ambient)
            .env_remove("RUSTC")
            .status()
            .expect("spawn compiler-binding child test");
        assert!(status.success(), "MSRV compiler-binding child test failed");
        return;
    }
    if installed_toolchain("1.88").is_none() {
        eprintln!("skipping compiler-binding test: no 1.88 toolchain installed");
        return;
    }
    let project = TestProject::with_rust_version_and_build_script(
        "msrv-compiler",
        "1.88",
        "",
        "pub fn value() -> usize { 1 }\n",
        COMPILER_PROBE,
    );
    let service = project.service();
    let required = RequiredConfigurations {
        include_default: false,
        include_policy: false,
        include_msrv: true,
        stages: vec![VerifyStage::Check],
        ..RequiredConfigurations::default()
    };
    let outcome = service
        .execute(
            request(
                VerifyAction::MatrixRun,
                &project.root,
                required,
                check_only_budget(2),
            ),
            None,
            None,
        )
        .await;
    let executed = outcome
        .cells
        .iter()
        .find(|cell| cell.toolchain.is_some())
        .unwrap_or_else(|| panic!("MSRV cell missing: {outcome:#?}"));
    assert_eq!(executed.status, "PASS", "{outcome:#?}");
    let selected = executed.toolchain.clone().expect("selected toolchain");
    let probe = find_file(
        project.root.parent().expect("fixture base directory"),
        "compiler-probe.txt",
    )
    .expect("build script compiler probe");
    let observed = fs::read_to_string(&probe).expect("read compiler probe");
    let expected = Command::new(
        rustup_home()
            .join("toolchains")
            .join(&selected)
            .join("bin")
            .join("rustc"),
    )
    .arg("-vV")
    .output()
    .expect("probe selected toolchain rustc");
    assert_eq!(
        observed,
        String::from_utf8(expected.stdout).expect("rustc -vV is UTF-8"),
        "the MSRV cell must run {selected}, not an ambient compiler"
    );
    assert!(
        observed.starts_with("rustc 1.88"),
        "unexpected compiler probe: {observed}"
    );
    // The binding must be visible in the evidence: a host cell runs with a
    // different command and environment hash than the toolchain cell.
    let host = service
        .execute(
            request(
                VerifyAction::MatrixRun,
                &project.root,
                RequiredConfigurations {
                    include_default: true,
                    include_policy: false,
                    stages: vec![VerifyStage::Check],
                    include_msrv: false,
                    ..RequiredConfigurations::default()
                },
                check_only_budget(2),
            ),
            None,
            None,
        )
        .await;
    let host_cell = cell(&host, "default--host--default--check");
    assert_ne!(
        host_cell.environment_hash, executed.environment_hash,
        "toolchain binding must change the environment hash"
    );
    assert_ne!(
        host_cell.command_hash, executed.command_hash,
        "toolchain binding must change the command hash"
    );
}
