#![cfg(windows)]
use agz_rust_mcp::workspace::{
    ClientRoots, IdentityInput, RootError, RootGuard, StdGitProbe, build_package_graph,
    compute_input_identity,
};
use cargo_metadata::Metadata;
use serde_json::json;
use std::{collections::BTreeMap, ffi::OsString, fs, path::PathBuf, sync::Arc, time::SystemTime};

/// Cargo reports ordinary drive paths for packages while authorized roots are
/// canonical. The package graph must expose the canonical spelling so anchor
/// containment and target selection compare one identity.
#[test]
fn package_graph_roots_use_the_canonical_verbatim_spelling() {
    let id = "fixture 0.1.0 (path+file:///C:/fake/workspace)";
    let metadata: Metadata = serde_json::from_value(json!({
        "packages": [{
            "name": "fixture",
            "version": "0.1.0",
            "id": id,
            "license": null,
            "license_file": null,
            "description": null,
            "source": null,
            "dependencies": [],
            "targets": [{
                "kind": ["lib"],
                "crate_types": ["lib"],
                "name": "fixture",
                "src_path": "C:\\fake\\workspace\\src\\lib.rs",
                "edition": "2024",
                "doc": true,
                "doctest": true,
                "test": true
            }],
            "features": {},
            "manifest_path": "C:\\fake\\workspace\\Cargo.toml",
            "metadata": null,
            "publish": null,
            "authors": [],
            "categories": [],
            "keywords": [],
            "readme": null,
            "repository": null,
            "homepage": null,
            "documentation": null,
            "edition": "2024",
            "links": null,
            "default_run": null,
            "rust_version": null
        }],
        "workspace_members": [id],
        "workspace_default_members": [id],
        "resolve": null,
        "workspace_root": "C:\\fake\\workspace",
        "target_directory": "C:\\fake\\workspace\\target",
        "metadata": null,
        "version": 1
    }))
    .expect("metadata fixture");

    let graph = build_package_graph(&metadata);
    let node = graph.nodes().values().next().expect("package node");
    assert_eq!(node.root, PathBuf::from(r"\\?\C:\fake\workspace"));
    assert_eq!(
        node.manifest_path,
        PathBuf::from(r"\\?\C:\fake\workspace\Cargo.toml")
    );
}

/// Change candidates are copied without `.git`, so the gate identity must
/// complete from the workspace walk alone. An incomplete identity makes every
/// candidate gate return INCONCLUSIVE before Cargo starts.
#[test]
fn candidate_input_identity_is_complete_without_git() {
    let stamp = SystemTime::now()
        .duration_since(SystemTime::UNIX_EPOCH)
        .expect("clock")
        .as_nanos();
    let base = fs::canonicalize(std::env::temp_dir())
        .expect("canonical temporary directory")
        .join(format!(
            "agz-candidate-identity-{}-{stamp}",
            std::process::id()
        ));
    let root = base.join("workspace");
    fs::create_dir_all(root.join("src")).expect("create src");
    fs::create_dir_all(root.join("dep/src")).expect("create dep src");
    fs::write(
        root.join("Cargo.toml"),
        "[package]\nname = \"probe-fixture\"\nversion = \"0.1.0\"\nedition = \"2024\"\n\n[workspace]\n\n[dependencies]\ndep = { path = \"dep\" }\n",
    )
    .expect("write manifest");
    fs::write(
        root.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"dep\"\nversion = \"0.1.0\"\n\n[[package]]\nname = \"probe-fixture\"\nversion = \"0.1.0\"\ndependencies = [\n \"dep\",\n]\n",
    )
    .expect("write lockfile");
    fs::write(root.join("src/lib.rs"), "pub fn value() -> u8 { 1 }\n").expect("write source");
    fs::write(
        root.join("src/__agz_api_probe_fixture.rs"),
        "// probe harness\n",
    )
    .expect("write harness");
    fs::write(
        root.join("dep/Cargo.toml"),
        "[package]\nname = \"dep\"\nversion = \"0.1.0\"\nedition = \"2024\"\n",
    )
    .expect("write dep manifest");
    fs::write(
        root.join("dep/src/lib.rs"),
        "pub fn old_api(value: u8) -> u8 { value }\n",
    )
    .expect("write dep source");

    let guard = Arc::new(RootGuard::new([root.clone()], std::iter::empty()).expect("root guard"));
    let workspace = guard
        .snapshot(ClientRoots::unsupported())
        .expect("root snapshot")
        .select(Some(&root))
        .expect("select workspace");
    let manifest = workspace.path().join("Cargo.toml");
    let command = [OsString::from("test")];
    let environment = std::env::vars_os().collect::<BTreeMap<_, _>>();
    let git = StdGitProbe::new("git");
    let identity = compute_input_identity(&IdentityInput::new(
        &workspace,
        &manifest,
        &base.join("cargo"),
        &command,
        &environment,
        &git,
    ))
    .expect("input identity");
    assert!(
        identity.complete,
        "candidate identity was incomplete: {:?}",
        identity.incomplete_reason
    );
    drop(identity);
    drop(workspace);
    drop(guard);
    let _ = fs::remove_dir_all(&base);
}

#[test]
fn ordinary_and_verbatim_drive_paths_share_authority_without_expanding_it() {
    let stamp = SystemTime::now()
        .duration_since(SystemTime::UNIX_EPOCH)
        .expect("clock")
        .as_nanos();
    let base = fs::canonicalize(std::env::temp_dir())
        .expect("canonical temporary directory")
        .join(format!("agz-path-identity-{}-{stamp}", std::process::id()));
    let root = base.join("root");
    let sibling = base.join("root-sibling");
    fs::create_dir_all(root.join("child")).expect("create root");
    fs::create_dir_all(&sibling).expect("create sibling");
    fs::write(root.join("child/source.rs"), "pub fn item() {}\n").expect("write source");
    let guard = RootGuard::new([root.clone()], std::iter::empty()).expect("root guard");
    let authority = guard.configured_roots()[0].clone();
    let plain = PathBuf::from(
        root.to_str()
            .expect("UTF-8 root")
            .strip_prefix(r"\\?\")
            .expect("verbatim drive"),
    );
    assert!(authority.contains(&plain));
    assert_eq!(
        authority
            .authorize_dir(&plain.join("child"))
            .expect("ordinary authorized child")
            .path(),
        root.join("child")
    );
    let snapshot = guard
        .snapshot(ClientRoots::unsupported())
        .expect("snapshot");
    assert!(snapshot.select(Some(&plain)).is_ok());
    assert!(!authority.contains(&sibling));
    assert!(authority.authorize_dir(&sibling).is_err());
    let escape = PathBuf::from(format!("{}\\..\\root-sibling", plain.display()));
    assert!(matches!(
        snapshot.select(Some(&escape)),
        Err(RootError::ParentComponent)
    ));
    drop(snapshot);
    drop(authority);
    drop(guard);
    fs::remove_dir_all(base).expect("remove fixture");
}
